<?php

namespace App\Repository;
//use V1Bundle\Common\Shared;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends BaseRepository
{
    public function availableSlots($schedule_detail_id)
    {
         $classSlots = $this->getEntityManager()->getRepository("CoredirectionBundle:ScheduleDetail")->findOneBy(array("id"=>$schedule_detail_id, "isDeleted"=>0, "isCancel"=>0));
            if(empty($classSlots)){
              return false;  
            }

            $usedSlots = $this->getEntityManager()->getRepository("CoredirectionBundle:MemberScheduleActivity")->getUsedSlots($schedule_detail_id);
            
           
            $slots = $classSlots->getSlots();
           
            $availableSlots = intval($slots) - $usedSlots;
            return  ($availableSlots < 1 ) ? false : $availableSlots; 

       
    }
    
    public function availableSlotsForClass($class_id)
    {
        $totalSlots = 0;
        $schedules=array();
        
         $objSchedulesDetails = $this->getEntityManager()->getRepository("CoredirectionBundle:ScheduleDetail")->getAllScheduleAllSlots($class_id);
         if(!empty($objSchedulesDetails))
         {
             foreach($objSchedulesDetails as $scheduleDetail)
             {
                 
                 $totalSlots += $scheduleDetail->getSlots();
                 $schedules[]=$scheduleDetail->getId();
             }
         }
         
         $usedSlots = $this->getEntityManager()->getRepository("CoredirectionBundle:MemberScheduleActivity")->getUsedSlots($schedules);
         
         //print_r($usedSlots);
         return $totalSlots;
         
            

       
    }
    
    
}
