<?php

namespace App\Repository;
use V1Bundle\Common\Shared;

/**
 * ActivityScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityScheduleRepository extends BaseRepository
{

    public function getAllScheduleActivity()
    {
        return $this->findBy(['isDeleted' => 0]);
    }


    public function getPackageClass($currentChoiceKey)
    {

        $choices_classes = array();
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('p')
            ->select('p')
            ->from('CoredirectionBundle:Package', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $currentChoiceKey);

        $results = $query->getQuery()->getResult();

        if ($results) {
            foreach ($results as $result) {
                return $ids = $result->getFacility()->getId();
            }
        }

    }


    public function getInstructorClass($currentChoiceKey)
    {


        $choices_classes = array();
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('u')
            ->from('ApplicationSonataUserBundle:User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('g.name IN  ( :name ) ')
            ->andWhere('u.username = :username')
            ->setParameter("name", 'Instructor')
            ->setParameter("username", $currentChoiceKey);


        $results = $query->getQuery()->getResult();

        if ($results) {
            foreach ($results as $result) {
                return $ids = $result->getParentUser()->getId();

            }
        }


    }


    public function getFacilityInstructor($userId, $facilityId = -1)
    {

        $users = $this->getAllChildrenByParentId($userId);
        $users[] = $userId;

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('u')
            ->from('ApplicationSonataUserBundle:User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('u.id IN  ( :users ) ')
            ->andWhere('g.name IN  ( :name ) ')
            ->setParameter("users", $users)
            ->setParameter("name", 'Instructor');

        if ($facilityId > 0)
            $query->andWhere('u.parentUser IN  ( :parentUserId ) ')
                ->setParameter("parentUserId", $facilityId);

        return $query;

    }

    public function getAllActivePackage($userId, $groups)
    {
        $em = $this->getEntityManager();
        $date = new \dateTime();
        $date = $date->format("Y-m-d");
        //TODO: have to rectify this flow
        if (in_array('facility', $groups) || in_array('superfranchise', $groups)) {

            $query = $em->createQueryBuilder('p')
                ->select('p')
                ->from('CoredirectionBundle:Package', 'p')
                ->where('p.isDeleted = 0 ')
                ->andWhere('p.facility = :user')
//                ->andWhere('DATE(p.expireson)> :curdate ')
                ->setParameter('user', $userId);
//                ->setParameter('curdate', $date);

        } else {

            $users = $this->getAllChildrenByParentId($userId);

//           print_r($users);
//           exit;


            $users[] = $userId;
            $query = $em->createQueryBuilder('p')
                ->select('p')
                ->from('CoredirectionBundle:Package', 'p')
                ->where('p.isDeleted = 0 ')
                ->andWhere('p.facility IN ( :users ) ')
//                ->andWhere('DATE(p.expireson)> :curdate ')
                ->setParameter('users', $users);
//                ->setParameter('curdate', $date);
        }
//        echo $userId. ' '. $date;
//        echo $query->getQuery()->getSQL();
//        exit;
        return $query;
    }

    public function getFacilityNameById($packageId)
    {
        $choices_classes = array();
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('p')
            ->select('p')
            ->from('CoredirectionBundle:Package', 'p')
            ->where('p.id = :id')
            ->setParameter('id', $packageId);

        $results = $query->getQuery()->getResult();

        if ($results) {
            foreach ($results as $result) {
                return $result->getFacility()->getUsername();
            }
        }
    }


    public function getActivitySchedule($facilityId, $roleArr, $filterbydate, $activity = null,$startDate=null,
                                        $endDate=null)
    {
        $start_date = $end_date = '';
        $date  = new \DateTime();
        if ($filterbydate == 1) {

            $start_date = $date->format('Y-m-d'). ' 00:00:00';
            $end_date =  $date->format('Y-m-d'). ' 23:59:59';

        } elseif ($filterbydate == 2) {

            $start_date = $date->format('Y-m-d'). ' 00:00:00';
            $end_date = date('Y-m-d', strtotime("+7 days")) . ' 23:59:59';

        } elseif ($filterbydate == 3) {
            $start_date = $date->format('Y-m-d'). ' 00:00:00';
            $end_date = date('Y-m-d', strtotime("+30 days")) . ' 23:59:59';

        } /////for last 7 days
        elseif ($filterbydate == 4) {
            $end_date = $date->format('Y-m-d') . ' 00:00:00';
            $start_date = date('Y-m-d', strtotime("-7 days")) . ' 23:59:59';
        } //for last 30 days
        elseif ($filterbydate == 5) {
            $end_date = $date->format('Y-m-d') . ' 00:00:00';
            $start_date = date('Y-m-d', strtotime("-30 days")) . ' 23:59:59';

        } elseif ($filterbydate == 6) {
            $start_date = new \DateTime($startDate);
            $end_date = new \DateTime($endDate.' +1 day');

        }
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('sd')
            ->select('sd')
            ->from('CoredirectionBundle:ScheduleDetail', 'sd')
            ->innerJoin('sd.schedule', 'sch')
            ->innerJoin('sch.activity', 'a')
            ->where('sd.isDeleted = 0')
            ->andWhere('sch.isDeleted = 0')
            ->andWhere('sch.facility = :facility')
            ->setParameter('facility', $facilityId)
            ->andWhere('sd.scheduleDate >= :start_date')
            ->setParameter('start_date', $start_date)
            ->andWhere('sd.scheduleDate <= :end_date')
            ->setParameter('end_date', $end_date);
        if ($activity) {
            $query->andWhere('a.id = ' . $activity);
        }
        $query->orderBy('sd.scheduleDate', 'ASC');
        $results = $query->getQuery()->getResult();//echo Count($results);exit;
        return $results;
    }

    public function getActivityScheduleCount($facilityId, $roleArr, $start_date = null, $end_date = null, $activity = null, $is_free = null)
    {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('sd')
            ->select('count(sd.id)')
            ->from('CoredirectionBundle:ScheduleDetail', 'sd')
            ->innerJoin('sd.schedule', 'sch')
            ->innerJoin('sch.activity', 'a')
            ->where('sd.isDeleted = 0');
        $query->andWhere('sch.facility = :facility')
            ->setParameter('facility', $facilityId);
        $query->andWhere('sd.scheduleDate >= :end_date');
        $query->setParameter('end_date', new \DateTime('now'));

        if ($activity) {
            $query->andWhere('a.id = ' . $activity);
        }
        //return $query->getQuery()->getSingleScalarResult();
        return $query->getQuery()->getSingleScalarResult();

    }


    public function getMemberListing($scheduleId, $offset, $limit, $memberName, $memberEmail, $memberPhone,$orderBy,$ordertype)
    {//echo $scheduleId;exit;

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('msa')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
            ->innerJoin('msa.member', 'm');
        $query->andWhere('msa.isDeleted = 0');
        $query->andWhere('msa.scheduleDetail = :schedule_detail_id');
        $query->andWhere('msa.status != :status' );
        $query->setParameter('schedule_detail_id', $scheduleId);
        $query->setParameter('status', Shared::$CANCELLED);
        if ($memberName) {
            $searchIn = $query->expr()->concat(
                $query->expr()->concat($query->expr()->literal(''), 'm.firstname'),
                $query->expr()->concat($query->expr()->literal(' '), 'm.lastname')
            );
            $query->andWhere($query->expr()->like($searchIn, ':keyword'));
            $query->setParameter('keyword', '%' . trim($memberName) . '%');
            $query->orWhere($query->expr()->like('m.username', ':username'));
            $query->setParameter('username', $memberName);
        }
        if ($memberEmail) {
            $query->andWhere('m.email like :email');
            $query->setParameter('email', '%' . $memberEmail . '%');
        }
        if ($memberPhone) {
            $query->andWhere('m.phone like :phone');
            $query->setParameter('phone', '%' . $memberPhone . '%');
        }
        $query->setFirstResult($offset);
        $query->setMaxResults($limit);
        $query->orderBy($orderBy, $ordertype);
        $query->groupBy('msa.member');
        $results = $query->distinct()->getQuery()->getResult();
        return $results;
    }

    public function getMemberCount($scheduleDetailId, $memberName, $memberEmail, $memberPhone)
    {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('count(msa)')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
            ->innerJoin('msa.member', 'm');
        $query->andWhere('msa.isDeleted = 0');
        $query->andWhere('msa.scheduleDetail = :schedule_detail_id');
        $query->setParameter('schedule_detail_id', $scheduleDetailId);
        if ($memberName) {
            $query->andWhere('m.firstname like :username');
            $query->andWhere('m.lastname like :username');
            $query->setParameter('username', '%' . $memberName . '%');
        }
        if ($memberEmail) {
            $query->andWhere('m.email like :email');
            $query->setParameter('email', '%' . $memberEmail . '%');
        }
        if ($memberPhone) {
            $query->andWhere('m.phone like :phone');
            $query->setParameter('phone', '%' . $memberPhone . '%');
        }

        return $query->distinct()->getQuery()->getSingleScalarResult();

    }


    public function memberCheckInIncrement($member_schedule_activity_id)
    {

        $em = $this->getEntityManager();
//        $query = $em->createQueryBuilder()
//            ->select('msa')
//            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa');
//        $query->andWhere( 'msa.id = :member_schedule_activity_id' );
//        $query->setParameter('member_schedule_activity_id', $member_schedule_activity_id );

    }


    public function getMemberCheckIn($member_schedule_activity_id)
    {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('mst')
            ->from('CoredirectionBundle:MemberScheduleTimelog', 'mst')
            ->innerJoin('mst.book', 'b');
        $query->andWhere('mst.book = :member_schedule_activity_id');//getCheckin
        $query->setParameter('member_schedule_activity_id', $member_schedule_activity_id);

        return $query->getQuery()->getResult();


    }

    public function isClassBooked($classId)
    {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('count(msa.id)')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
            ->innerJoin('msa.scheduleDetail', 'sd')
            ->innerJoin('sd.schedule', 'act')
            ->where('msa.isDeleted = 0');
        $query->andWhere('act.id = :classid');
        $query->andWhere('msa.status = :status');
        $query->setParameter('classid', $classId);
        $query->setParameter('status', 'booked');


        return $query->getQuery()->getSingleScalarResult();


    }

}
