<?php

namespace App\Repository;

/**
 * AppVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppVersionRepository extends \Doctrine\ORM\EntityRepository
{

    public function updateCurrentRelease($id,$deviceType)
    {


            $qb = $this->createQueryBuilder('av');
            $qb = $qb->update()
                ->set("av.currentRelease",0)
                ->where("av.id !=:id")
                ->andWhere("av.deviceType =:deviceType")
                ->setParameter(":id",$id)
                ->setParameter(":deviceType",$deviceType);
            $qb->getQuery()->execute();
    }
}
