<?php

namespace App\Repository;

/**
 * ArticleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;

class ArticleTypeRepository extends BaseRepository
{
    function Get_All_Tags(){
        $results = array();
        $choices_list = array();
        $results = $this->findAll();
        if($results){
            foreach($results as $result){
                $tags = $result->getTags();
                $ids = $result->getId();
                if($tags){
                    $explode_tags = explode(',',$tags);
                    if($explode_tags){
                        foreach($explode_tags as $explode_tag){
                            if($explode_tag){
                                $choices_list[] = $explode_tag;
                            }
                        }
                    }
                }
            }
        }
        return $results[] = array('tags' => $choices_list);
    }

    function Article_Tag_Class($gettagid){
        $choices_classes = array();
        $results = $this->findAll();
        if($results){
            foreach($results as $result){
                $tags = $result->getTags();
                $ids = $result->getId();
                if($tags){
                    $explode_tags = explode(',',$tags);
                    if($explode_tags){
                        foreach($explode_tags as $explode_tag){
                            if($explode_tag){
                                $choices_classes[] = $ids;
                            }
                        }
                    }
                }
            }
        }
        if(isset($choices_classes[$gettagid])){
            return $choices_classes[$gettagid];
        }else {
            return '';
        }

    }

    function getAllArabicTags(){
        $results = array();
        $choices_list = array();
        $results = $this->findAll();
        if($results){
            foreach($results as $result){
                $tags = $result->getTagsAr();
                $ids = $result->getId();
                if($tags){
                    $explode_tags = explode(',',$tags);
                    if($explode_tags){
                        foreach($explode_tags as $explode_tag){
                            if($explode_tag){
                                $choices_list[] = $explode_tag;
                            }
                        }
                    }
                }
            }
        }
        return  $choices_list;
    }

    public function getActiveArticleType()
    {

        $qb = $this->createQueryBuilder('at')
                ->where('at.isDeleted =:isDeleted')
                ->setParameter('isDeleted',false);

        return $qb;
    }
}
