<?php

namespace App\Repository;



/**
 * CorporateDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateDepartmentRepository extends BaseRepository
{
}
