<?php

namespace App\Repository;
use Application\Sonata\UserBundle\Entity\User;
use V1Bundle\Common\Shared;


/**
 * CorporateKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateKeyRepository extends BaseRepository
{

    public function getPackagesByFacility($userId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('p')
            ->select('p')
            ->from('CoredirectionBundle:Package', 'p')
            ->where('p.isDeleted = 0 ')
            ->andWhere('p.facility = :user')
            ->andWhere('p.expireson >= :curdate')
            ->setParameter('curdate', new \DateTime())
            ->setParameter('user', $userId);


        return $query->getQuery()->getResult();
    }

    public function getCorePassPackage(){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('p')
            ->select('p')
            ->from('CoredirectionBundle:Package', 'p')
            ->where('p.isDeleted = 0 ')
            ->andWhere('p.isCorepass = 1')
            ->andWhere('p.expireson >= :curdate')
            ->setParameter('curdate', new \DateTime())
            ;


        return $query->getQuery()->getResult();
    }

    public function getAllPackageForCorporateKey($userId)
    {

        $em = $this->getEntityManager();
        $users = $this->getAllChildrenByParentId($userId);

        $users[] = $userId;
        $query = $em->createQueryBuilder('p')
            ->select('p')
            ->from('CoredirectionBundle:Package', 'p')
            ->where('p.isDeleted = 0 ')
            ->andWhere('p.facility IN ( :users ) ')
            ->setParameter('users', $users);

        return $query;
    }

    public function keySummaryCount($username){

        $countQuery = "SELECT 
                            COUNT(A.id)
                       FROM 
                            fos_user_user A 
                       INNER JOIN fos_user_user_group B ON A.id = B.user_id
                       INNER JOIN fos_user_group C ON B.group_id = C.id
                       LEFT JOIN corporate_key D ON A.id=D.corporate_id
                       LEFT JOIN 
                            (
                             SELECT id 
                             FROM 
                             corporate_key
                             WHERE
                             DATE_FORMAT(validate_date,\"%Y-%m-%d\") < NOW()
                            ) E ON D.id = E.id
                            
                            WHERE C.code = 'Corporate' ";

        if ($username) {
            $countQuery .= " AND A.company_name like '%$username%'";
        }
        $countQuery .= " GROUP BY A.id ";
         
        return $countQuery;
    }

    public function keySummaryDQL($username, $sortby, $sortOrder, $offset, $limit, $timeperiod = null){
        
        $dateLimit = '';
        if($timeperiod){
				
	        if ($timeperiod == "1") {
	            $start = date('Y-m-d', strtotime('Monday last week'));
	            $end = date('Y-m-d', strtotime('Sunday last week'));
	            $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

	        } elseif ($timeperiod == "2") {
	            $last_month = date('m', strtotime('last month'));
	            $last_year_month = date('Y-m', strtotime('last month'));
	            $end_months = array('01', '03', '05', '07', '08', '10', '12');
	            if (in_array($last_month, $end_months)) {
	                $month_end = '31';
	            } else {
	                $month_end = '30';
	            }

	            $start = $last_year_month . '-01';
	            $end = $last_year_month . '-' . $month_end;
	            $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
	            $groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

	        } else {

	            $interval = $timeperiod;
	            $end = date('Y-m-d');
	            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

	            $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
	            $groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
	            $orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
	        }
	        $dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }
        
        $dql = "SELECT 
                        A.id,A.company_name,
                        A.company_logo,
                        COUNT(D.id) AS total, 
                        COUNT(E.id) active,
                        (COUNT(D.id)- COUNT(E.id)) expired 
                 FROM 
                    fos_user_user A 
                 INNER JOIN fos_user_user_group B ON A.id = B.user_id
                 INNER JOIN fos_user_group C ON B.group_id = C.id
                 LEFT JOIN corporate_key D ON A.id=D.corporate_id
                 LEFT JOIN 
                    (
                     SELECT id 
                     FROM 
                     corporate_key
                     WHERE
                     DATE_FORMAT(validate_date,\"%Y-%m-%d\") < NOW()
                    ) E ON D.id = E.id
                    
                    WHERE C.code = 'Corporate' {$dateLimit} 
";
        if ($username) {
            $dql .= " AND A.company_name like '%$username%' ";
        }
        $dql .= "GROUP BY A.id  ";
        $dql .= "ORDER BY $sortby $sortOrder";
        if($limit){
            $dql .= " limit $offset , $limit ";
        }

        return $dql;
    }

    public function franchiseKeyCount(){
        $countQuery = "SELECT 
                            count(A.id) as total
                       FROM 
                            fos_user_user A 
                       INNER JOIN fos_user_user_group B ON A.id = B.user_id
                       INNER JOIN fos_user_group C ON B.group_id = C.id
                       INNER JOIN corporate_key ck ON A.id = ck.corporate_id     
                       INNER JOIN key_profile_group kpg ON kpg.corporatekey_id = ck.id     
                       INNER JOIN profile_key pk ON pk.id = kpg.profilekey_id     

                       WHERE C.code = 'MasterFranchise' 
                       AND A.enabled = 1";



        return $countQuery;
    }

    public function getFranchisekeys($username, $sortby, $orderby, $offset, $limit){

        $dql = "SELECT 
                         A.company_name,
                         A.company_logo,
                         A.username,
                         A.email,
                         ck.company_key,
                         ck.id as keyid,
                         pk.name as profile_key_name
                       FROM 
                            fos_user_user A 
                       INNER JOIN fos_user_user_group B ON A.id = B.user_id
                       INNER JOIN fos_user_group C ON B.group_id = C.id
                       INNER JOIN corporate_key ck ON A.id = ck.corporate_id     
                       INNER JOIN key_profile_group kpg ON kpg.corporatekey_id = ck.id     
                       INNER JOIN profile_key pk ON pk.id = kpg.profilekey_id     
                       WHERE C.code = 'MasterFranchise' 
                       AND A.enabled = 1";

        if ($username) {
            $dql .= " AND A.username like '%$username%' ";
        }

        $dql .= " ORDER BY $sortby $orderby";
        if($limit){
            $dql .= " limit $offset , $limit ";
        }

        return $dql;
    }


    /**
     * @param User $corporate
     * @return array
     */
    public function getRedeemedUsersByCorporate(User $corporate)
    {

        $params['corporateUserId'] = $corporate->getId();
        $sql = 'SELECT ck.id as key_id,
                    mk.member_id as member_id,
                    u.username as username,
                    u.email as email,
                    u.firstname as firstname,
                    u.lastname as lastname,
                    u.phone as mobile_number,
                    u.id as user_id,
                    ck.company_key as redeemed_code,
                    ck.type as redeemed_code_type,
                    mk.created  as redeemed_date,
                    ck.is_active as redeemed_key_status
                FROM corporate_key ck
                INNER JOIN member_key mk ON ck.id = mk.key_id
                INNER JOIN fos_user_user u ON mk.member_id = u.id
                  WHERE  ck.corporate_id = :corporateUserId
                  ORDER BY mk.id DESC
                  ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }


    /**
     * @param User $corporate
     * @return array
     */
    public function getRedeemedUsersIdByCorporate(User $corporate)
    {

        $params['corporateUserId'] = $corporate->getId();
        $params['REFERRAL'] = Shared::$KEY_TYPE_Referral;
//        $params['PROFILE'] = Shared::$KEY_TYPE_PROFILE;
        $sql = 'SELECT DISTINCT u.id as id
                FROM corporate_key ck
                INNER JOIN member_key mk ON ck.id = mk.key_id
                INNER JOIN fos_user_user u ON mk.member_id = u.id
                  WHERE  ck.corporate_id = :corporateUserId
                  AND ck.type in (:REFERRAL)
                  ORDER BY mk.id DESC
                  ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }


    /**
     * @param User $corporate
     * @return array
     */
    public function getRedeemedUsersIdByCorporateStatus(User $corporate,User $member)
    {

        $params['corporateUserId'] = $corporate->getId();
        $params['REFERRAL'] = Shared::$KEY_TYPE_Referral;
        $params['memberId'] = $member->getId();
//        $params['PROFILE'] = Shared::$KEY_TYPE_PROFILE;
        $sql = 'SELECT DISTINCT ck.id as id,ck.is_active as is_active
                FROM corporate_key ck
                INNER JOIN member_key mk ON ck.id = mk.key_id
                INNER JOIN fos_user_user u ON mk.member_id = u.id
                  WHERE  ck.corporate_id = :corporateUserId
                  AND ck.type in (:REFERRAL)
                  AND u.id in (:memberId)
                  ORDER BY mk.id DESC
                  ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }


    /**
     * @param User $corporate
     * @return array
     */
    public function getRedeemedUsersByCorporateFromEmail($emai,User $corporate)
    {

        $params['corporateUserId'] = $corporate->getId();
        $params['email'] = $emai;
        $params['profile'] = Shared::$KEY_TYPE_PROFILE;
        $params['refrrel'] = Shared::$KEY_TYPE_Referral;
        $sql = 'SELECT ck.id as key_id,
                    ck.company_key as redeemed_code,
                    ck.type as redeemed_code_type,
                    ck.is_active as redeemed_key_status
                FROM corporate_key ck
                INNER JOIN member_invitation mi ON ck.id = mi.corporate_key_id
                  WHERE  ck.corporate_id = :corporateUserId
                  AND mi.email = :email
                  AND (ck.type = :profile OR ck.type = :refrrel)
                  ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }



    /**
     * @param User $corporate
     * @return array
     */
    public function getRedeemedUsersGraph(User $corporate,$dateFrom,$dateTo,$filterType)
    {
        if($filterType == 'month'){
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $params['corporateUserId'] = $corporate->getId();
            $params['start_date'] = $dateFrom->format('y-m-d H:i:s');
            $params['end_date'] = $dateTo->format('y-m-d H:i:s');
            $sql = ' SELECT
                     COUNT( member_id) objects ,
                     DATE_FORMAT(mk.created, "%Y-%M") as created_at,
                     MONTH(mk.created) by_month
                     FROM member_key mk 
                     INNER JOIN fos_user_user u ON u.id = mk.member_id
                     INNER JOIN corporate_key  c ON c.id = mk.key_id
                     INNER JOIN fos_user_user uc ON uc.id = c.corporate_id 
                     WHERE  uc.id = :corporateUserId
                     AND   mk.created >= :start_date 
                     AND   mk.created <= :end_date
                     GROUP BY created_at
                  ';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute($params);
            return $stmt->fetchAll();
        }else{
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $params['corporateUserId'] = $corporate->getId();
            $params['start_date'] = $dateFrom->format('y-m-d H:i:s');
            $params['end_date'] = $dateTo->format('y-m-d H:i:s');
            $sql = ' SELECT
                     COUNT(DISTINCT member_id) objects ,
                     DATE_FORMAT(mk.created, "%M-%d") as created_at,
                     DAY (mk.created) by_month
                     FROM member_key mk 
                     INNER JOIN fos_user_user u ON u.id = mk.member_id
                     INNER JOIN corporate_key  c ON c.id = mk.key_id
                     INNER JOIN fos_user_user uc ON uc.id = c.corporate_id 
                     WHERE  uc.id = :corporateUserId
                     AND   mk.created >= :start_date 
                     AND   mk.created <= :end_date
                     GROUP BY created_at
                  ';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute($params);
            return $stmt->fetchAll();
        }
    }

    /**
     * @param User $corporate
     * @return array
     */
    public function getArticlesGraphByCorporate(User $corporate,$dateFrom,$dateTo,$filterType)
    {
        if($filterType == 'month'){
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $sql = 'SELECT
                    COUNT( DISTINCT PKA.article_id ) objects,
                    MONTH ( PKA.created_date ) months,
                    DATE_FORMAT(PKA.created_date, "%Y-%M") as created_at
                FROM
                    profile_key_articles PKA
                    INNER JOIN profile_key PF ON PF.id = PKA.profile_key_id 
                WHERE
                    PF.company_id = '.$corporate->getId().' 
                AND PKA.created_date >=  "'.$dateFrom->format('y-m-d H:i:s').'"
                AND PKA.created_date <= "'.$dateTo->format('y-m-d H:i:s').'"
                GROUP BY
                    months';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute();
            return $stmt->fetchAll();
        }else{
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $sql = 'SELECT
                    COUNT( DISTINCT PKA.article_id ) objects,
                    DAY ( PKA.created_date ) months,
                    DATE_FORMAT(PKA.created_date, "%M-%d") as created_at
                FROM
                    profile_key_articles PKA
                    INNER JOIN profile_key PF ON PF.id = PKA.profile_key_id 
                WHERE
                    PF.company_id = '.$corporate->getId().' 
                AND PKA.created_date >=  "'.$dateFrom->format('y-m-d H:i:s').'"
                AND PKA.created_date <= "'.$dateTo->format('y-m-d H:i:s').'"
                GROUP BY
                    months';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute();
            return $stmt->fetchAll();
        }

    }

    /**
     * @param User $corporate
     * @return array
     */
    public function getWorkoutGraphByCorporate(User $corporate,$dateFrom,$dateTo,$filterType)
    {
        if($filterType == 'month'){
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $sql = 'SELECT
                    COUNT( DISTINCT PKW.workout_id ) objects,
                    MONTH ( PKW.created_date ) months,
                    DATE_FORMAT( PKW.created_date, "%Y-%M" ) AS created_at 
                FROM
                    profile_key_workouts PKW
                    INNER JOIN profile_key PF ON PF.id = PKW.profile_key_id 
                WHERE
                    PF.company_id = '.$corporate->getId().' 
                AND PKW.created_date >=  "'.$dateFrom->format('y-m-d H:i:s').'"
                AND PKW.created_date <= "'.$dateTo->format('y-m-d H:i:s').'"
                GROUP BY
                    months';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute();
            return $stmt->fetchAll();
        }else{
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $sql = 'SELECT
                    COUNT( DISTINCT PKW.workout_id ) objects,
                    DAY ( PKW.created_date ) months,
                    DATE_FORMAT( PKW.created_date, "%M-%d" ) AS created_at 
                FROM
                    profile_key_workouts PKW
                    INNER JOIN profile_key PF ON PF.id = PKW.profile_key_id 
                WHERE
                    PF.company_id = '.$corporate->getId().' 
                AND PKW.created_date >=  "'.$dateFrom->format('y-m-d H:i:s').'"
                AND PKW.created_date <= "'.$dateTo->format('y-m-d H:i:s').'"
                GROUP BY
                    months';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute();
            return $stmt->fetchAll();
        }

    }

    /**
     * @param User $corporate
     * @return array
     */
    public function getBookingsGraphByCorporate(User $corporate,$dateFrom,$dateTo,$filterType)
    {
        if($filterType == 'month'){
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $params['corporateUserId'] = $corporate->getId();
            $params['start_date'] = $dateFrom->format('y-m-d H:i:s');
            $params['end_date'] = $dateTo->format('y-m-d H:i:s');
            $params['status_cancelled'] = Shared::$CANCELLED;
            $params['status_reserved'] = Shared::$RESERVED;
            $sql = 'SELECT
                    COUNT( DISTINCT msa.id ) objects,
                    DATE_FORMAT( msa.created_date, "%Y-%M" ) AS created_at,
                    MONTH ( msa.created_date ) by_month 
                FROM
                    member_schedule_activity msa
                    INNER JOIN member_package mp on mp.id = msa.member_package_id
                    INNER JOIN corporate_key_package ckp ON ckp.package_id = mp.package_id
                    INNER JOIN corporate_key c ON c.id = ckp.corporatekey_id
                    INNER JOIN fos_user_user uc ON uc.id = c.corporate_id 
                WHERE
                    uc.id = :corporateUserId 
                    AND msa.created_date >=  :start_date
                    AND msa.created_date <=  :end_date
                    AND msa.`STATUS` NOT IN (:status_cancelled,:status_reserved)
                GROUP BY
                    by_month ';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute($params);
            return $stmt->fetchAll();
        }else{
            $dateFrom = new \DateTime($dateFrom);
            $dateTo = new \DateTime($dateTo);
            $params['corporateUserId'] = $corporate->getId();
            $params['start_date'] = $dateFrom->format('y-m-d H:i:s');
            $params['end_date'] = $dateTo->format('y-m-d H:i:s');
            $params['status_cancelled'] = Shared::$CANCELLED;
            $params['status_reserved'] = Shared::$RESERVED;
            $sql = 'SELECT
                    COUNT( DISTINCT msa.id ) objects,
                    DATE_FORMAT( msa.created_date, "%M-%d" ) AS created_at,
                    DAY ( msa.created_date ) by_month 
                FROM
                    member_schedule_activity msa
                    INNER JOIN member_package mp on mp.id = msa.member_package_id
                    INNER JOIN corporate_key_package ckp ON ckp.package_id = mp.package_id
                    INNER JOIN corporate_key c ON c.id = ckp.corporatekey_id
                    INNER JOIN fos_user_user uc ON uc.id = c.corporate_id 
                WHERE
                    uc.id = :corporateUserId 
                    AND msa.created_date >=  :start_date
                    AND msa.created_date <=  :end_date
                    AND msa.`STATUS` NOT IN (:status_cancelled,:status_reserved)
                GROUP BY
                    by_month ';
            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute($params);
            return $stmt->fetchAll();
        }

    }

    /**
     * @param User $corporate
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getBookingsCountByCorporate(User $corporate)
    {
        $params['corporateUserId'] = $corporate->getId();
        $params['status_cancelled'] = Shared::$CANCELLED;
        $params['status_reserved'] = Shared::$RESERVED;
        $sql = 'SELECT
                    COUNT( DISTINCT msa.id ) objects
                FROM
                    member_schedule_activity msa
                    INNER JOIN member_package mp on mp.id = msa.member_package_id
                    INNER JOIN corporate_key_package ckp ON ckp.package_id = mp.package_id
                    INNER JOIN corporate_key c ON c.id = ckp.corporatekey_id
                    INNER JOIN fos_user_user uc ON uc.id = c.corporate_id 
                WHERE
                    uc.id = :corporateUserId 
                    AND msa.`STATUS` NOT IN (:status_cancelled,:status_reserved)
               ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

    /**
     * @param User $corporate
     * @return array
     */
    public function getWorkoutCountByCorporate(User $corporate)
    {

        $sql = 'SELECT
                    COUNT( DISTINCT PKW.workout_id ) objects
                FROM
                    profile_key_workouts PKW
                    INNER JOIN profile_key PF ON PF.id = PKW.profile_key_id 
                WHERE
                    PF.company_id = '.$corporate->getId().' 
               ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    /**
     * @param User $corporate
     * @return array
     */
    public function getArticlesCountByCorporate(User $corporate)
    {
        $sql = 'SELECT
                    COUNT( DISTINCT PKA.article_id ) objects
                FROM
                    profile_key_articles PKA
                    INNER JOIN profile_key PF ON PF.id = PKA.profile_key_id 
                WHERE
                    PF.company_id = '.$corporate->getId().' 
                ';
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }







}
