<?php

namespace App\Repository;

/**
 * DeviceConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
