<?php

namespace App\Repository;

/**
 * ErrorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorLogRepository extends BaseRepository
{
}
