<?php

namespace App\Repository;

use App\Entity\ExerciseLookup;
/**
 * ExerciseLookupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseLookupRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getExerciseData($exerciseId, $allchoices)
    {
        $return_data = array('MOVEMENT_TYPE' => array(),'EQUIPMENT_REQUIREMENTS' => array(), 'TARGETED_MUSCLE_GROUP' => array(), 'EXERCISE_TYPE' => array(), 'EXERCISE_ENVIRONMENT' => array(),'MODEL' => array());

        $results = $this->findBy(array('exercise' => $exerciseId));

        $array_1 = $allchoices['Movement Type'];
        $array_2 = $allchoices['Equipment requirements'];
        $array_3 = $allchoices['Targeted muscle group'];
        $array_4 = $allchoices['Exercise type'];
        $array_5 = $allchoices['Exercise Environment'];
        $array_6 = $allchoices['Model'];

        foreach($results as $result){
            $lookupid = $result->getBaseLookup()->getId();
            if(isset($array_1[$lookupid])) {
                $return_data['MOVEMENT_TYPE'][] = $lookupid;
            }elseif(isset($array_2[$lookupid])) {
                $return_data['EQUIPMENT_REQUIREMENTS'][] = $lookupid;
            }elseif(isset($array_3[$lookupid])) {
                $return_data['TARGETED_MUSCLE_GROUP'][] = $lookupid;
            }elseif(isset($array_4[$lookupid])) {
                $return_data['EXERCISE_TYPE'][] = $lookupid;
            }elseif(isset($array_5[$lookupid])) {
                $return_data['EXERCISE_ENVIRONMENT'][] = $lookupid;
            }elseif(isset($array_6[$lookupid])) {
                $return_data['MODEL'][] = $lookupid;
            }
        }

        return $return_data;
    }
    
    
    public function removeExerciseData($exerciseId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->delete('CoredirectionBundle:ExerciseLookup', 'el')
            ->where("el.exercise =  ( :exercise_id )")
            ->setParameter("exercise_id", $exerciseId)
                ;
        $results = $query->getQuery()->getResult();
        return $results;
    }
    
    
    public function saveBaseLookups($exerciseId, $formData, $loginedUserId)
    {
        $lookups_ids = array();
        $types = array('movementType','equipmentRequirements','targetedMuscleGroup','exerciseType','exerciseEnvironment','model');

        foreach($types as $type){
            if(isset($formData[$type])){
                if($type == 'model'){
                    $type_data = array($formData[$type]);
                }else {
                    $type_data = $formData[$type];
                }
                if(count($type_data)>0){
                    foreach($type_data as $data){
                        $lookups_ids[] = $data;
                    }
                }
            }
        }

        if($lookups_ids){
            $em = $this->getEntityManager();
            $exercise = $em->getReference('App\Entity\Exercise', $exerciseId);

            foreach($lookups_ids as $lookups_id){
                $exercise_lookup = new ExerciseLookup();

                $base_lookup = $em->getReference('App\Entity\BaseLookup',$lookups_id);
                $exercise_lookup->setExercise($exercise);
                $exercise_lookup->setBaseLookup($base_lookup);
                $exercise_lookup->setModifiedBy($loginedUserId);
                $exercise_lookup->setCreatedDate(new \DateTime());

                $em->persist($exercise_lookup);
            }
            $em->flush();
        }
    }
    
    
    public function findExercisebyNameAndLookup($lookupId, $exerciseName){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->select('count(el.id)')
            ->from('CoredirectionBundle:ExerciseLookup', 'el')
            ->innerJoin('el.exercise', 'exe')
            ->where('exe.name  =  :name ')
            ->andWhere('el.baseLookup = :lookup ')
            ->setParameter("name", $exerciseName)
            ->setParameter("lookup", $lookupId)
        ;
        return  $query->getQuery()->getSingleScalarResult();

    }

    public function findExercisebyNameAndLookupEditCase($lookupId, $exerciseName, $exerciseId ){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->select('count(el.id)')
            ->from('CoredirectionBundle:ExerciseLookup', 'el')
            ->innerJoin('el.exercise', 'exe')
            ->where('exe.name  =  :name ')
            ->andWhere('el.baseLookup = :lookup ')
            ->andWhere('exe.id NOT IN ( :exeId ) ')
            ->setParameter("exeId", $exerciseId)
            ->setParameter("name", $exerciseName)
            ->setParameter("lookup", $lookupId)
        ;
        return  $query->getQuery()->getSingleScalarResult();

    }

    public function getExerciseByModelId($modelId){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('el,exe.id, exe.name ')
            ->from('CoredirectionBundle:ExerciseLookup', 'el')
            ->innerJoin('el.exercise', 'exe')
            ->innerJoin('el.baseLookup', 'bl')
            ->where('bl.id  =  :model_id ')

            ->setParameter("model_id", $modelId)

        ;

        return  $query->getQuery()->getResult();

    }


    public function deleteExerciseByLookup($lookupId){

        $results  = $this->findBy(array('baseLookup' => $lookupId));
        $exercise_ids = array();
        if(!empty($results)) {

            foreach ($results as $result){
                $exercise_ids[] = $result->getExercise()->getId();
            }

            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder()
                ->update('CoredirectionBundle:Exercise', 'exe')
                ->set('exe.isDeleted',  '1')
                ->where('exe.id  IN (  :exercise_ids ) ')
                ->setParameter("exercise_ids", $exercise_ids)
            ;

            $query->getQuery()->execute();
        }
    }


    public function getExerciseModelByExerciseId($exerciseId){

        $em =$this->getEntityManager();
        $modelId = $em->getRepository('CoredirectionBundle:BaseLookup')
            ->findOneBy(array('code' => 'MODEL'));

        $full_model_list  = $em->getRepository('CoredirectionBundle:BaseLookup')
            ->findBy(array('parentId' => $modelId->getId(), 'isDeleted' => 0));
        $model_array = array();

        foreach($full_model_list as $mod_list){
           $model_array[] = $mod_list->getId();
        }
        

        

        $query = $em->createQueryBuilder()
            ->select('bl.id ')
            ->from('CoredirectionBundle:ExerciseLookup', 'el')
            ->innerJoin('el.exercise', 'exe')
            ->innerJoin('el.baseLookup', 'bl')
            ->where('el.exercise  =  :exe_id ')
            ->andWhere('el.baseLookup  IN (  :model_id  )')

            ->setParameter("exe_id", $exerciseId)
            ->setParameter("model_id", $model_array)

        ;



       $results =   $query->getQuery()->getResult();

        $data = '';
        foreach($results as $result){
            $data =  $result['id'];
        }

       
           return $data;
    }
}