<?php

namespace App\Repository;

/**
 * FacilityPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilityPackageRepository extends BaseRepository
{
    public function BookingCount($username, $name){

        $countQuery = "SELECT count(*)
                        FROM fos_user_user A
                JOIN fos_user_user_group C ON C.user_id = A.id
                JOIN fos_user_group K ON K.id = C.group_id
                JOIN activity_schedule D ON   D.facility_id=A.id 
                JOIN schedule_detail SD ON   D.id=SD.schedule_id
                JOIN activity B ON D.activity_id=B.id 
                LEFT JOIN 
                (
                SELECT id,schedule_detail_id,package_id FROM member_schedule_activity WHERE STATUS LIKE 'booked'
                ) 
                E ON SD.id=E.schedule_detail_id 
                INNER JOIN  member_package M ON M.package_id = E.package_id 
              
                LEFT JOIN member_billing_detail  F  ON  M.id=F.member_package_id
                WHERE K.code IN ('Facility','SuperFranchise')
                        ";

        if ($username) {
            $countQuery .= " AND A.company_name like '%$username%'";
        }
        if ($name) {
            $countQuery .= " AND B.name like '%$name%'";
        }
        $countQuery .= " GROUP BY A.id,B.name,SD.schedule_date ";

        return $countQuery;
    }
    
    public function BookingSummary($username, $name, $sortby, $sortOrder, $offset, $limit){

        $dql = "SELECT A.company_name ,
                B.name,
                D.startDate,
                D.endDate,
                COUNT(E.id) total_booking ,
                SUM(F.amount) total_amt
                
                FROM fos_user_user A
                JOIN fos_user_user_group C ON C.user_id = A.id
                JOIN fos_user_group K ON K.id = C.group_id
                JOIN activity_schedule D ON   D.facility_id=A.id 
                JOIN schedule_detail SD ON   D.id=SD.schedule_id
                JOIN activity B ON D.activity_id=B.id 
                LEFT JOIN 
                (
                SELECT id,schedule_detail_id,package_id FROM member_schedule_activity WHERE STATUS LIKE 'booked'
                ) 
                E ON SD.id=E.schedule_detail_id 
                INNER JOIN  member_package M ON M.package_id = E.package_id 
              
                LEFT JOIN member_billing_detail  F  ON  M.id=F.member_package_id
                WHERE K.code IN ('Facility','SuperFranchise')";

        if ($username) {
            $dql .= " AND A.company_name like '%$username%' ";
        }
        if ($name) {
            $dql .= " AND B.name like '%$name%'";
        }

        $dql .= "GROUP BY A.id,B.name,D.id ";
        $dql .= "ORDER BY $sortby $sortOrder";
        $dql .= " limit $offset , $limit ";

        return $dql;
    }
}
