<?php

namespace App\Repository;

/**
 * FacilityAmenityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilityAmenityRepository extends BaseRepository
{
}
