<?php

namespace App\Repository;

/**
 * InvitationTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
