<?php

namespace App\Repository;

/**
 * MemberPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberPackageRepository extends BaseRepository
{
    public function getDashboardPackageCount($users, $packageType, $timeperiod = null)
    {

        $dateLimit = '';
        if ($timeperiod) {

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }


        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder('mp')
            ->select('count(mp.id)')
            ->from('CoredirectionBundle:MemberPackage', 'mp')
            ->innerJoin('mp.member', 'u')
            ->innerJoin('mp.package', 'pkg')
            ->innerJoin('pkg.packageType', 'ptype')
            ->where('ptype.name = :type ')
            ->andWhere('mp.isDeleted = 0 ')
            ->andWhere('pkg.facility IN ( :user )')
            ->setParameter("type", $packageType)
            ->setParameter("user", $users);

        if ($timeperiod) {
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime($start))
                ->setParameter('end', new \DateTime($end));
        }


        return $query->getQuery()->getSingleScalarResult();


    }

    public function getSoldPackageCountByType($childs, $packageType)
    {
//            dump($packageType);die;
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder('mp');
        if($packageType == 'SESSION') {
            $query->select('sum(mp.checkin)');
        }else{
            $query->select('count(mp.id)');

        }

            $query->from('CoredirectionBundle:MemberPackage', 'mp')
            ->innerJoin('mp.package', 'p')
            ->innerJoin('p.packageType', 'pt')
            ->innerJoin('mp.member', 'm')
            ->innerJoin('mp.memberBillingDetail', 'mbd')
            ->where('p.facility IN  ( :facility ) ')
            ->andWhere('pt.code = :code')
//            ->andWhere('p.name LIKE :word')  /////remove due to sessions were not comming for Sub <Franchise
//            ->andWhere('mp.checkin >  ')
            ->setParameter('code', $packageType)
            ->setParameter("facility", $childs);

//        ->setParameter('word', '%Membership');
        $result = $query->getQuery()->getSingleScalarResult();
        if(isset($result)){
            return $result;
        }else{
          return 0;
        }


    }


    public function getSoldPackageCountByTypeGraphRepresent($timePeriod,$childs, $packageType)
    {

        if($timePeriod == 1 || $timePeriod == 2 || $timePeriod == 'today' ){

            $em = $this->getEntityManager();

            $query = $em->createQueryBuilder('mp');
            if($packageType == 'SESSION') {
                $query->select('sum(mp.checkin) as total_sold,  DATE_FORMAT(mp.createdDate,\'%Y-%M-%d\') as createdDate');
            }else{
                $query->select('count(mp.id)');

            }

            $query->from('CoredirectionBundle:MemberPackage', 'mp')
                ->innerJoin('mp.package', 'p')
                ->innerJoin('p.packageType', 'pt')
                ->innerJoin('mp.member', 'm')
                ->innerJoin('mp.memberBillingDetail', 'mbd')
                ->where('p.facility IN  ( :facility ) ')
                ->andWhere('pt.code = :code')
                ->orderBy('mp.createdDate','ASC')
                ->groupBy('createdDate')
//            ->andWhere('p.name LIKE :word')  /////remove due to sessions were not comming for Sub <Franchise
//            ->andWhere('mp.checkin >  ')
                ->setParameter('code', $packageType)
                ->setParameter("facility", $childs);

//        ->setParameter('word', '%Membership');
            $result = $query->getQuery()->getResult();
            if(isset($result)){
                return $result;
            }else{
                return 0;
            }

        }else{

            $em = $this->getEntityManager();

            $query = $em->createQueryBuilder('mp');
            if($packageType == 'SESSION') {
                $query->select('sum(mp.checkin) as total_sold,  DATE_FORMAT(mp.createdDate,\'%Y-%M\') as createdDate');
            }else{
                $query->select('count(mp.id)');

            }

            $query->from('CoredirectionBundle:MemberPackage', 'mp')
                ->innerJoin('mp.package', 'p')
                ->innerJoin('p.packageType', 'pt')
                ->innerJoin('mp.member', 'm')
                ->innerJoin('mp.memberBillingDetail', 'mbd')
                ->where('p.facility IN  ( :facility ) ')
                ->andWhere('pt.code = :code')
                ->orderBy('mp.createdDate','ASC')
                ->groupBy('createdDate')
//            ->andWhere('p.name LIKE :word')  /////remove due to sessions were not comming for Sub <Franchise
//            ->andWhere('mp.checkin >  ')
                ->setParameter('code', $packageType)
                ->setParameter("facility", $childs);

//        ->setParameter('word', '%Membership');
            $result = $query->getQuery()->getResult();
            if(isset($result)){
                return $result;
            }else{
                return 0;
            }

        }


    }






    public function getSoldPackageCount($packageType)
    {
        if($packageType == 'SESSION'){
            $packageType = 'Session';
        }

        $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
        $connection = $em->getConnection();
        $statement = $connection->prepare("select member_package.package_id,package.name, package_type.name,sum(member_package.checkin) as t_count from member_package
join package on member_package.package_id = package.id
join package_type on package.package_type_id = package_type.id where package_type.name like :type");
        $statement->bindValue('type', $packageType);
        $statement->execute();
        $results = $statement->fetch();
        return $results['t_count'];
//        dump($results);die;


    }

    public function getTotalSoldPackageForGraph($facilityId, $pkgType, $timeperiod, $role)
    {
        $start = $end = "";
        if ($timeperiod == "1") {

            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d', strtotime("+ 1 day"));
        } elseif ($timeperiod == "today") {
            $start = date('Y-m-d');
            $end = date('Y-m-d');
        } elseif ($timeperiod == "2") {
            $start = date('Y-m-d', strtotime('-30 days'));
            $end = date('Y-m-d', strtotime('+ 1 day'));
        } else {
            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));
        }
        if ($timeperiod == 1 || $timeperiod == 2 || $timeperiod == 'today') {
            $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
            $connection = $em->getConnection();
            $statement = $connection->prepare("select member_package.package_id,package.name, package_type.name,sum(member_package.checkin) as total_sold ,DATE_FORMAT(member_package.created_date, '%Y-%M-%d') createdDate   from member_package
join package on member_package.package_id = package.id
join package_type on package.package_type_id = package_type.id where package_type.name like :type 
  AND (DATE_FORMAT(member_package.created_date, '%Y-%m-%d') BETWEEN '.$start.' AND '$end') 
GROUP BY createdDate");
            $statement->bindValue('type', $pkgType);
            $statement->execute();
            $results = $statement->fetchAll();
            return $results;
        } else {
            $em = $this->getEntityManager();
            $connection = $em->getConnection();
            $statement = $connection->prepare("select member_package.package_id,package.name, package_type.name,sum(member_package.checkin) as total_sold ,DATE_FORMAT(member_package.created_date, '%Y-%M') createdDate   from member_package
join package on member_package.package_id = package.id
join package_type on package.package_type_id = package_type.id where package_type.name like :type 
  AND (DATE_FORMAT(member_package.created_date, '%Y-%m') BETWEEN '.$start.' AND '$end') 
GROUP BY createdDate");
            $statement->bindValue('type', $pkgType);
            $statement->execute();
            $results = $statement->fetchAll();
            return $results;
        }
    }















 public function getTotalSoldPackageForGraphMembership($facilityId, $pkgType, $timeperiod, $role)
 {
     $start = $end = "";
//     $results = [];
     if ($timeperiod == "1") {

         $start = date('Y-m-d', strtotime('-7 days'));
         $end = date('Y-m-d', strtotime("+ 1 day"));
     } elseif ($timeperiod == "today") {
         $start = date('Y-m-d');
         $end = date('Y-m-d');
     } elseif ($timeperiod == "2") {
         $start = date('Y-m-d', strtotime('-30 days'));
         $end = date('Y-m-d', strtotime('+ 1 day'));
     } else {
         $interval = $timeperiod;
         $end = date('Y-m-d');
         $start = date('Y-m-d', strtotime("-" . $interval . " month"));
     }
     if ($timeperiod == 1 || $timeperiod == 2 || $timeperiod == 'today') {
         if($role == 'HQ-Admin'){
             $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
             $connection = $em->getConnection();
             $statement = $connection->prepare("SELECT
                count( m0_.id ) AS total_sold, DATE_FORMAT(m0_.created_date, '%Y-%M-%d') createdDate 
            FROM
                member_package m0_
                INNER JOIN package p1_ ON m0_.package_id = p1_.id
                INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
                INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
                INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id 
            WHERE
                 p2_.CODE = 'MEMBERSHIP' 
                 group by DAY(m0_.created_date)");
//             $statement->execute();
//             $results = $statement->fetchAll();

         }elseif ($role == 'SubFranchise'){
             $em = $this->getEntityManager();
             $connection = $em->getConnection();
             $statement = $connection->prepare("SELECT
                count( m0_.id ) AS total_sold, DATE_FORMAT(m0_.created_date, '%Y-%M-%d') createdDate 
            FROM
                member_package m0_
                INNER JOIN package p1_ ON m0_.package_id = p1_.id
                INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
                INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
                INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id 
            WHERE
                 p2_.CODE = 'MEMBERSHIP' 
                 AND
             p1_.facility_id IN (:facilities) 
                 group by DAY(m0_.created_date)");
             $facilityId = implode(',',$facilityId);
             $statement->bindValue('facilities', $facilityId);

         }
         $statement->execute();
         $results = $statement->fetchAll();
         return $results;


     } else {

         if($role == 'HQ-Admin'){
             $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
             $connection = $em->getConnection();
             $statement = $connection->prepare("SELECT
                count( m0_.id ) AS total_sold, DATE_FORMAT(m0_.created_date, '%Y-%M') createdDate 
            FROM
                member_package m0_
                INNER JOIN package p1_ ON m0_.package_id = p1_.id
                INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
                INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
                INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id 
            WHERE
                 p2_.CODE = 'MEMBERSHIP' 
                 group by MONTH (m0_.created_date)");
             $statement->execute();
             $results = $statement->fetchAll();
         }elseif ($role == 'SubFranchise'){
             $em = $this->getEntityManager();
             $connection = $em->getConnection();
             $statement = $connection->prepare("SELECT
                count( m0_.id ) AS total_sold, DATE_FORMAT(m0_.created_date, '%Y-%M') createdDate 
            FROM
                member_package m0_
                INNER JOIN package p1_ ON m0_.package_id = p1_.id
                INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
                INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
                INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id 
            WHERE
                 p2_.CODE = 'MEMBERSHIP' 
                 AND
             p1_.facility_id IN (:facilities) 
                 group by DAY(m0_.created_date)");
             $facilityId = implode(',',$facilityId);
             $statement->bindValue('facilities', $facilityId);
             $statement->execute();
             $results = $statement->fetchAll();
             return $results;
         }

         return $results;
     }

//     $statement->bindValue('type', $pkgType);
//     $statement->bindValue('facilities', $facilityId);

//     dump($results);die;



 }














//
//
//
//
//
//
//
//
//        $query = $em->createQueryBuilder('mp');
//            if($pkgType == 'SESSION') {
//                //->select('sum(mp.checkin) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%m-%d\') as createdDate')
//                $query->select('sum(mp.checkin) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%M-%d\') as createdDate');
//            }else{
//                $query->select('sum(mp.id) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%M-%d\') as createdDate');
//
//            }
//            $query->from('CoredirectionBundle:MemberPackage', 'mp')
//            ->innerJoin('mp.package', 'pkg')
//            ->innerJoin('pkg.packageType', 'ptype')
//            ->where('ptype.name = :type ')
//            ->andWhere('mp.checkin > 0 ')
//            ->andWhere('pkg.facility IN ( :user )')
//            ->setParameter("type", $pkgType)
//            ->setParameter("user", $facilityId)
//            ->orderBy('mp.createdDate','ASC')
//            ->groupBy('createdDate');
//
//        if ($timeperiod) {
//            $query->andWhere("DATE_FORMAT(mp.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
//                ->setParameter('start', $start)
//                ->setParameter('end', $end);
//        }
//
////        echo $start;
////        echo $end;
////
////        print_r($facilityId);
////
////        echo $query->getQuery()->getSQL(); exit;
//        return $query->getQuery()->getResult();



	public function getTotalSoldPackageForGraphMonthView($facilityId, $pkgType, $timeperiod, $role)
	{

//   dump($pkgType);die;
		$start = $end = "";


		if ($timeperiod == "1") {
//            $start = date('Y-m-d', strtotime('Monday last week'));
//            $end = date('Y-m-d', strtotime('Sunday last week'));
			$start = date('Y-m-d', strtotime('-7 days'));
			$end = date('Y-m-d',strtotime("+ 1 day"));


		} elseif ($timeperiod == "today") {
			$start = date('Y-m-d');
			$end = date('Y-m-d');


		} elseif ($timeperiod == "2") {
			$start = date('Y-m-d', strtotime('-30 days'));
			$end = date('Y-m', strtotime('+ 1 day'));
//            $end_months = array('01', '03', '05', '07', '08', '10', '12');
//            if (in_array($last_month, $end_months)) {
//                $month_end = '31';
//            } else {
//                $month_end = '30';
//            }
//
//            $start = $last_year_month . '-01';
//            $end = $last_year_month . '-' . $month_end;

		} else {

			$interval = $timeperiod;
			$end = date('Y-m-d');
			$start = date('Y-m-d', strtotime("-" . $interval . " month"));

		}


		$em = $this->getEntityManager();

		$query = $em->createQueryBuilder('mp');
		if($pkgType == 'SESSION') {
			//->select('sum(mp.checkin) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%m-%d\') as createdDate')
			$query->select('sum(mp.checkin) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%M\') as createdDate');
		}else{
			$query->select('sum(mp.id) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%M\') as createdDate');

		}
		$query->from('CoredirectionBundle:MemberPackage', 'mp')
		      ->innerJoin('mp.package', 'pkg')
		      ->innerJoin('pkg.packageType', 'ptype')
		      ->where('ptype.name = :type ')
		      ->andWhere('mp.checkin > 0 ')
		      ->andWhere('pkg.facility IN ( :user )')
		      ->setParameter("type", $pkgType)
		      ->setParameter("user", $facilityId)
		      ->orderBy('mp.createdDate','ASC')
		      ->groupBy('createdDate');

		if ($timeperiod) {
			$query->andWhere("DATE_FORMAT(mp.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
			      ->setParameter('start', $start)
			      ->setParameter('end', $end);
		}

//        echo $start;
//        echo $end;
//
//        print_r($facilityId);
//
//        echo $query->getQuery()->getSQL(); exit;
		return $query->getQuery()->getResult();
	}

    public function getTotalSoldPackageForGraphByFromAndToTime($facilityId, $pkgType, $fromDate, $toDate, $role)
    {
        $start = $fromDate;
        $end = $toDate;
//        $em = $this->getEntityManager();

//        $query = $em->createQueryBuilder('mp');
//        if ($pkgType == 'SESSION') {
//            //->select('sum(mp.checkin) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%m-%d\') as createdDate')
//            $query->select('sum(mp.checkin) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%m-%b\') as createdDate');
//        } else {
//            $query->select('sum(mp.id) as total_sold, DATE_FORMAT(mp.createdDate,\'%Y-%m-%b\') as createdDate');
//
//        }
//        $query->from('CoredirectionBundle:MemberPackage', 'mp')
//            ->innerJoin('mp.package', 'pkg')
//            ->innerJoin('pkg.packageType', 'ptype')
//            ->where('ptype.name = :type ')
//            ->andWhere('mp.checkin > 0 ')
//            ->andWhere('pkg.facility IN ( :user )')
//            ->setParameter("type", $pkgType)
//            ->setParameter("user", $facilityId)
//            ->orderBy('mp.createdDate', 'ASC')
//            ->groupBy('createdDate');
//        $query->andWhere("DATE_FORMAT(mp.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
//            ->setParameter('start', $start)
//            ->setParameter('end', $end);
//        return $query->getQuery()->getResult();

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("select member_package.package_id,package.name, package_type.name,sum(member_package.checkin) as total_sold ,DATE_FORMAT(member_package.created_date, '%Y-%M') createdDate   from member_package
join package on member_package.package_id = package.id
join package_type on package.package_type_id = package_type.id where package_type.name like :type 
  AND (DATE_FORMAT(member_package.created_date, '%Y-%m') BETWEEN '.$start.' AND '$end') 
GROUP BY createdDate");
        $statement->bindValue('type', $pkgType);
        $statement->execute();
        $results = $statement->fetchAll();
        return $results;
    }


}
