<?php

namespace App\Repository;

use V1Bundle\Common\Shared;

/**
 * MemberScheduleActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberScheduleActivityRepository extends BaseRepository
{
    public function getUsedSlots($id)
    {

        /*
                $id = is_array($id) ? implode(",",$id) : $id;

                //Todo: Need to work on it due to structure change
                $qb = $this->createQueryBuilder('n')
                ->select('count(n.id)')
                ->where("n.scheduleDetail IN ({$id})")

                //->setParameter('schedule', $id)
                ->orWhere('n.status = :status')
                ->setParameter('status', Shared::$BOOK)
                ->orWhere('n.status = :status')
                ->setParameter('status', Shared::$RESERVED);
                    */
        $status = array('booked', 'reserved');
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('count(msa.id)')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
            ->innerJoin('msa.scheduleDetail', 'sd')
            ->innerJoin('sd.schedule', 'act')
            ->where('msa.isDeleted = 0');
        $query->andWhere('act.id = :classid');
        $query->andWhere('msa.status in ( :status )');
        $query->setParameter('classid', $id);
        $query->setParameter('status', $status);


        return $query->getQuery()->getSingleScalarResult();
    }
    public function getAllBookedSlots($id)
    {

        $status = array('booked', 'reserved','expired');
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('count(msa.id)')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
            ->innerJoin('msa.scheduleDetail', 'sd')
            ->where('msa.isDeleted = 0');

        $query->andWhere('msa.status in ( :status )');
        $query->andWhere('sd.id = :id')
            ->setParameter('id', $id);

        $query->setParameter('status', $status);


        return $query->getQuery()->getSingleScalarResult();
    }

    public function getBookedSlots($id)
    {

        $status = array('booked', 'reserved');
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('count(msa.id)')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
            ->innerJoin('msa.scheduleDetail', 'sd')
            ->where('msa.isDeleted = 0');

        $query->andWhere('msa.status in ( :status )');
        $query->andWhere('sd.id = :id')
            ->setParameter('id', $id);

        $query->setParameter('status', $status);


        return $query->getQuery()->getSingleScalarResult();
    }

    public function getMemberbyScheduleDetailId($scheduleDetailId)
    { //getMemberbyScheduleDetailId

        $qb = $this->createQueryBuilder('n')
            ->select('n')
            ->where('n.scheduleDetail = :scheduleDetail')
            ->setParameter('scheduleDetail', $scheduleDetailId)
            ->andWhere('n.status = :status')
            ->setParameter('status', Shared::$BOOK);

        return $qb->getQuery()->getResult();
    }

    public function getActiveMemberActivity($scheduleDetailId,$bufferTime = 60)
    { //getMemberbyScheduleDetailId

        $bufferStr = $bufferTime." MINUTE";
        $now = date('Y-m-d H:i:s', strtotime($bufferStr));
        $qb = $this->createQueryBuilder('msa')
            ->innerJoin('msa.scheduleDetail', 'sd')
            ->where('msa.id= :id')
            ->andWhere("sd.scheduleDate <=  :end_date")
            ->andWhere('msa.status = :status')
            ->setParameter('id', $scheduleDetailId)
            ->setParameter('end_date',$now)
            ->setParameter('status', Shared::$BOOK);

        return $qb->getQuery()->getResult();
    }

    public function getScheduleDetailBooked($scheduleDetailId)
    {
        $status = array('booked', 'reserved');
        $qb = $this->createQueryBuilder('n')
            ->select('count(n)')
            ->where('n.scheduleDetail = :scheduleDetail')
            ->andWhere('n.status  IN  ( :status )')
            ->setParameter('scheduleDetail', $scheduleDetailId)
            ->setParameter('status', $status);

        return $qb->getQuery()->getSingleScalarResult();

    }


    /**
     * @param $memberId
     * @return array
     * @Author Omair Afzal
     */
    public function getMemberScheduleDetailTillNextHourByMemberId($memberId,$latitude,$longitude,$radius,$autoCheckinTimeBuffer = 0)
    {
        $timeBuffer = "+".$autoCheckinTimeBuffer." Minute";
        $end_date = date('Y-m-d H:i:s', strtotime($timeBuffer));
        $params['timeBuffer'] = $end_date;
        $params['memberId'] = $memberId;
        $params['status'] = Shared::$BOOK;
        $params['lat'] = $latitude;
        $params['lon'] = $longitude;
        $params['unit'] = 6371;
        $params['range'] = $radius;

        $query = "SELECT
                m0_.id AS id,
                (
                    :unit *
                    acos(cos(radians(:lat)) *
                         cos(radians(IF( s.is_location = 0 , u.latitude, s.latitude))) *
                         cos(radians(IF( s.is_location = 0 , u.longitude, s.longitude)) -
                             radians(:lon)) +
                         sin(radians(:lat)) *
                         sin(radians(IF( s.is_location = 0 , u.latitude, s.latitude))))
                  ) AS distance
                FROM member_schedule_activity m0_
                INNER JOIN schedule_detail s1_ ON m0_.schedule_detail_id = s1_.id
                INNER JOIN activity_schedule s ON s1_.schedule_id = s.id
                INNER JOIN fos_user_user u ON s.facility_id = u.id
                WHERE m0_.status IN (:status)
                AND s1_.schedule_date <= :timeBuffer
                AND m0_.member_id = :memberId
                HAVING distance <= :range
                ORDER BY s1_.schedule_date ASC";

        $stmnt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmnt->execute($params);

        return $stmnt->fetchAll();
    }





    /**
     * @param $memberId
     * @return array
     * @Author Omair Afzal
     */
    public function getMemberScheduleDetailTillNextHourByMemberIdForAutoCheckIn($memberId,$latitude,$longitude,$radius,$autoCheckinTimeBuffer = 0)
    {
        $timeBuffer = $autoCheckinTimeBuffer." Minute";
        $end_date = date('Y-m-d H:i:s');
        $params['timeBuffer'] = $end_date;
        $params['memberId'] = $memberId;
        $params['status'] = Shared::$BOOK;
        $params['lat'] = $latitude;
        $params['lon'] = $longitude;
        $params['unit'] = 6371;
        $params['range'] = $radius;

        $query = "SELECT
                m0_.id AS id,
                (
                    :unit *
                    acos(cos(radians(:lat)) *
                         cos(radians(IF( s.is_location = 0 , u.latitude, s.latitude))) *
                         cos(radians(IF( s.is_location = 0 , u.longitude, s.longitude)) -
                             radians(:lon)) +
                         sin(radians(:lat)) *
                         sin(radians(IF( s.is_location = 0 , u.latitude, s.latitude))))
                  ) AS distance
                FROM member_schedule_activity m0_
                INNER JOIN schedule_detail s1_ ON m0_.schedule_detail_id = s1_.id
                INNER JOIN activity_schedule s ON s1_.schedule_id = s.id
                INNER JOIN fos_user_user u ON s.facility_id = u.id
                WHERE m0_.status IN (:status)
                AND DATE_ADD(s1_.schedule_date, INTERVAL $timeBuffer ) <= :timeBuffer
                AND m0_.member_id = :memberId
                HAVING distance <= :range
                ORDER BY s1_.schedule_date ASC";

        $stmnt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmnt->execute($params);

        return $stmnt->fetchAll();
    }

    /**
     * @param $schedule_detail_id
     * @param $user_id
     * @param bool $flgTemp
     * @return int|mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getAvailableSlots($schedule_detail_id, $user_id, $flgTemp=false)
    {
        $schedule_detail_id = is_array($schedule_detail_id) ? implode(",",$schedule_detail_id) : $schedule_detail_id;

        $query = $this->createQueryBuilder('l')
            ->select('count(msa.id)')
            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa');

        if($flgTemp==true){
            $query->where("msa.member != :user_id  ")
                ->setParameter('user_id', $user_id);
        }

        $query->andWhere("msa.scheduleDetail IN ({$schedule_detail_id})")
            ->andWhere(" msa.status = '".Shared::$BOOK."'  or  msa.status = '".Shared::$RESERVED."' ");

        $usedSlots = $query->getQuery()->getSingleScalarResult();


        $query = $this->createQueryBuilder('l')
            ->select('sum(sd.slots)')
            ->from('CoredirectionBundle:ScheduleDetail', 'sd')
            ->andWhere("sd.id IN ({$schedule_detail_id})")
            ->andWhere("sd.isDeleted = :isDeleted  ")
            ->setParameter('isDeleted', 0 )
            ->andWhere("sd.isCancel = :isCancel  ")
            ->setParameter('isCancel', 0 );

        $totalSlots = $query->getQuery()->getSingleScalarResult();

        $availableSlots = $totalSlots - $usedSlots ;
        return ($availableSlots >0 ) ? $availableSlots : 0 ;

    }

}
