<?php

namespace App\Repository;

/**
 * MemberFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberFilterRepository extends BaseRepository
{
}
