<?php

namespace App\Repository;

use Application\Sonata\UserBundle\Entity\User;
use V1Bundle\Common\Shared;

/**
 * MemberKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberKeyRepository extends BaseRepository
{

    public function checkUserPart(User $user,User $corporate)
    {

        $qb = $this->createQueryBuilder('mk')
            ->where('mk.member = :member')
            ->join('App\Entity\CorporateKey','ck','WITH','ck.id = mk.corporateKey')
            ->andWhere('ck.corporate = :corporate')
            ->andWhere('ck.type = :type')
            ->setParameter('member',$user)
            ->setParameter('type',Shared::$KEY_TYPE_Referral)
            ->setParameter('corporate',$corporate)
        ;
        return $qb->getQuery()->getResult();
    }
}
