<?php

namespace App\Repository;

/**
 * MemberArticleFavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberArticleFavoriteRepository extends BaseRepository
{
    function articleAddToFavorite($articleId){
        echo $articleId;
    }

}
