<?php

namespace App\Repository;

use Doctrine\Common\Collections\Criteria;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageRepository extends BaseRepository
{
    public function PackageSalesCount($username){
        $repository = $this->getEntityManager()->getRepository('ApplicationSonataUserBundle:User');

        $query = $repository->createQueryBuilder('u')
            //->select('u')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('pkg.isCorepass  =  0 ');


        $query = $repository->createQueryBuilder('u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')

            ->andWhere('pkg.isCorepass  =  0 ')

            ->select("count(u.username)  
            
          
            
            ")
            ->groupBy('u.id')
        ;

        if ($username) {
            $query->
            andWhere('u.username  =  :username ')
                ->setParameter('username', $username);
        }

        return $query;
    }

    public function PackageSalesSummary($username, $sortby, $orderby, $offset, $limit){

        $repository = $this->getEntityManager()->getRepository('ApplicationSonataUserBundle:User');
        $query = $repository->createQueryBuilder('u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')

            ->andWhere('pkg.isCorepass  =  0 ')

            ->select("u.username, 
            
            (case when ptype.code = 'Session' then COUNT(pkg.id) else 0 end) as total_session,
            (case when ptype.code = 'Membership' then COUNT(pkg.id) else 0 end) as total_membership,
            (case when ptype.code = 'Session' then COUNT(mpkg.id) else 0 end) as total_session_sold,
            (case when ptype.code = 'Membership' then COUNT(mpkg.id) else 0 end) as total_membership_sold,
            (case when ptype.code = 'Session' then sum(mbd.amount) else 0 end) as total_session_amt,
            (case when ptype.code = 'Membership' then sum(mbd.amount) else 0 end) as total_membership_amt
            
            ")
            ->groupBy('u.id')
            ->orderBy($sortby, $orderby)
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        if ($username) {
            $query->
            andWhere('u.username  =  :username ')
                ->setParameter('username', $username);
        }

        return $query;
    }

    public function getFacilityTotalPackageByType($facilityId, $ptype,$timeperiod){

        $start = $end = "";


        if ($timeperiod == "1") {
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');


        } elseif ($timeperiod == "2") {
            $last_month = date('m', strtotime('last month'));
            $last_year_month = date('Y-m', strtotime('last month'));
            $end_months = array('01', '03', '05', '07', '08', '10', '12');
            if (in_array($last_month, $end_months)) {
                $month_end = '31';
            } else {
                $month_end = '30';
            }

            $start = $last_year_month . '-01';
            $end = $last_year_month . '-' . $month_end;


        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));


        }


        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder('p')
            ->select('count(p.id) as total_available, p.createdDate')
            ->from('CoredirectionBundle:Package', 'p')
            ->innerJoin('p.packageType','ptype')
            ->where('ptype.name = :type ')
            ->andWhere('p.isDeleted = 0 ')
            ->andWhere('p.facility IN ( :user )')
            ->setParameter("type", $ptype)
            ->setParameter("user", $facilityId)
            ->groupBy('p.createdDate')
        ;

        if($timeperiod){
            $query->andWhere("DATE_FORMAT(p.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);

        }



        return $query->getQuery()->getResult();

    }

    public function getValidRecordByCode($code)
    {
        $criteria = new Criteria();
        $criteria->where($criteria->expr()->eq('isDeleted', 0))
            ->andWhere($criteria->expr()->eq('code', $code))
            ->andWhere($criteria->expr()->gt('expireson', new \DateTime()));
        return $this->matching($criteria)->first();
    }

}
