<?php

namespace App\Repository;

use App\Entity\ProfileKeyWorkouts;

/**
 * ProfileKeyWorkoutsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileKeyWorkoutsRepository extends BaseRepository
{
    public function removeProfileKeyWorkouts($edit_profile_id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('pw')
            ->delete('CoredirectionBundle:ProfileKeyWorkouts', 'pw')
            ->where("pw.profileKeyId =  ( :profile_key_id )")
            ->setParameter("profile_key_id", $edit_profile_id);

        $results = $query->getQuery()->getResult();
        return $results;
    }

    public function addProfileKeyWorkouts($profile_workouts, $edit_profile_id, $loginedUserId)
    {
        $em = $this->getEntityManager();
        $saved_key = $em->getRepository("CoredirectionBundle:ProfileKey")->findOneBy(array('id' => $edit_profile_id));

        foreach($profile_workouts as $workout){

            $saved_workout = $em->getRepository("CoredirectionBundle:Workout")->findOneBy(array('id' => $workout));

            $prof_workouts = new ProfileKeyWorkouts();
            $prof_workouts->setProfileKeyId($saved_key);
            $prof_workouts->setWorkoutId($saved_workout);
            $prof_workouts->setIsDeleted(0);
            $prof_workouts->setModifiedBy($loginedUserId);

            $em->persist($prof_workouts);
        }
        $em->flush();
    }

    public function getProfileKeyWorkouts($profileId){

        $query = $this->createQueryBuilder('p')
            ->add('select', 'w.name,w.code, w.imageName')
            ->innerJoin('p.workoutId', 'w')
            ->where('p.profileKeyId = :profilekey')
            ->andWhere('w.isDeleted = 0')
            ->setParameter('profilekey', $profileId)
        ;
        $results = $query->getQuery()->getResult();
        return $results;
    }
}
