<?php

namespace App\Repository;

/**
 * ProfileKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileKeyRepository extends BaseRepository
{
    public function getProfileforKey($userId){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('p')
            ->from("CoredirectionBundle:ProfileKey", 'p')
            ->where('p.isDefault = 1')
            ->andWhere("p.companyId = :userId")
            ->andWhere("p.isDeleted = 0")
            ->setParameter("userId" , $userId)

            ->getQuery()->getResult();

        $choices = array();
        foreach ($query as $value) {
            $choices[$value->getId()] = $value->getName();
        }

        return $choices;
    }
}
