<?php

namespace App\Repository;

use App\Entity\ActivitySchedule;
use App\Entity\ScheduleDetail;
use V1Bundle\Common\Shared;

/**
 * ScheduleDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleDetailRepository extends BaseRepository
{
    public function addScheduleDetail($schedule_id, $loginuserid){
        $em = $this->getEntityManager();

        $activity_schedule = $em->getRepository("CoredirectionBundle:ActivitySchedule")->findOneBy(array('id' => $schedule_id));
        $schedule_duration = $activity_schedule->getDuration();
        $schedule_session_type = $activity_schedule->getSessionType();
        $schedule_slots = $activity_schedule->getSlots();
        $recurrences = $activity_schedule->getRecurrence();
        $schedule_start_date = $activity_schedule->getStartDate();
        $schedule_end_date = $activity_schedule->getEndDate();
        $start_date = $schedule_start_date->format('Y-m-d H:i:s');
        $start_time = $schedule_start_date->format('H:i:s');
        $end_date = $schedule_end_date->format('Y-m-d '.$start_time);
        $latitude = $activity_schedule->getLatitude();
        $longitude = $activity_schedule->getLongitude();


        $segmented_days = array();

        if($recurrences){
            foreach($recurrences as $rec) {
                $segmented_days = array_merge($segmented_days, $this->getDateForSpecificDayBetweenDates($start_date, $end_date, $rec));
            }
        }

        if($segmented_days){
            asort($segmented_days);
            foreach($segmented_days as $date){

                $schedule_date = (new \DateTime($date));
                $schedule_recurrence = $schedule_date->format('l');

                $time_table = new ScheduleDetail();
                $time_table->setSchedule($activity_schedule);
                $time_table->setScheduleDate(new \DateTime($date));
                $time_table->setDuration($schedule_duration);
                $time_table->setRecurrence($schedule_recurrence);
                $time_table->setSessionType($schedule_session_type);
                $time_table->setSlots($schedule_slots);
                $time_table->setIsCancel(0);
                $time_table->setIsDeleted(0);
                $time_table->setModifiedBy($loginuserid);
                $time_table->setLatitude($latitude);
                $time_table->setLongitude($longitude);
                $em->persist($time_table);
            }
            $em->flush();
        }
    }

    public function updateScheduleDetail($schedule_id, $formData, $old_data , $loginuserid){
        $em = $this->getEntityManager();
        $delte_schedule_time_table = $this->removeScheduleDetail($schedule_id);
        $old_recurrences = $old_data["recurrence"] ;
        $old_schedule_start_date = $old_data["startDate"]->format('Y-m-d H:i');
        $old_schedule_end_date = $old_data["endDate"]->format('Y-m-d');
        $old_schedule_slots = $old_data["slots"];
        $old_schedule_duration = $old_data["duration"];
        $old_schedule_session_type = $old_data["sessionType"];


        $compare_start_date = $formData['startDate']['date']." ".$formData['startDate']['time'];
        $compare_end_date = $formData['endDate'];

        $recurrences_diff = array_diff($old_recurrences, $formData['recurrence']);
        $new_recurrence_diff = array_diff($formData['recurrence'],$old_recurrences);


        $activity_schedule_timetable = $em->getRepository("CoredirectionBundle:ScheduleDetail")->findBy(array('schedule' => $schedule_id));


        if(!empty($activity_schedule_timetable) && empty($recurrences_diff) && empty($new_recurrence_diff) && $old_schedule_start_date == $compare_start_date && $old_schedule_end_date == $compare_end_date && $old_schedule_slots == $formData['slots'] && $old_schedule_duration == $formData['duration'] && $old_schedule_session_type == $formData['sessionType']){


        }else if(!empty($activity_schedule_timetable) && empty($recurrences_diff) && empty($new_recurrence_diff) && ($old_schedule_slots != $formData['slots'] || $old_schedule_duration != $formData['duration'] || $old_schedule_session_type != $formData['sessionType'])){


            $schedule_duration = $formData['duration'];
            $schedule_session_type = $formData['sessionType'];
            $schedule_slots = $formData['slots'];
            $schedule_latitude = $formData['latitude'];
            $schedule_longitude = $formData['longitude'];

            $get_start_date = $formData['startDate']['date']." ".$formData['startDate']['time'].":00";
            $start_date = (new \DateTime($get_start_date))->format('Y-m-d H:i:s');
            $start_time = (new \DateTime($get_start_date))->format('H:i:s');
            $end_date = (new \DateTime($formData['endDate']))->format('Y-m-d '.$start_time);
            $start_datep = new \DateTime($get_start_date);
            if(strtotime($start_date) > strtotime($end_date)){
                $delte_schedule_time_table = $this->removeScheduleDetail($schedule_id);
            }

            //echo "<br><br>here";
            $schedule_timetable = $em->getRepository("CoredirectionBundle:ScheduleDetail")->findBy(array('schedule' => $schedule_id));
            if($schedule_timetable){
                foreach($schedule_timetable as $timetable){

                    $timetable->setDuration($schedule_duration);
                    $timetable->setSessionType($schedule_session_type);
                    $timetable->setLatitude($schedule_latitude);
                    $timetable->setLongitude($schedule_longitude);
                    $timetable->setScheduleDate($start_datep);

                    $active_schedule_slots = $timetable->getSlots();


                    if(($active_schedule_slots != $old_schedule_slots) && ($schedule_slots != $old_schedule_slots)){
                        // do nothing
                        //                      echo "<br><br>here to set the slots";
                        //$timetable->setSlots($schedule_slots);
                        //$timetable->setSlots($schedule_slots);
                    }else if(($active_schedule_slots == $old_schedule_slots) && ($schedule_slots != $old_schedule_slots)){
                        $timetable->setSlots($schedule_slots);
                    }
                }

                //              die;
                $em->flush();
            }

        }else{


            $delte_schedule_time_table = $this->removeScheduleDetail($schedule_id);


            $activity_schedule = $em->getRepository("CoredirectionBundle:ActivitySchedule")->findOneBy(array('id' => $schedule_id));
            //print_r($formData['startDate']);

            $get_start_date = $formData['startDate']['date']." ".$formData['startDate']['time'].":00";
            $start_date = (new \DateTime($get_start_date))->format('Y-m-d H:i:s');
            $start_time = (new \DateTime($get_start_date))->format('H:i:s');
            $end_date = (new \DateTime($formData['endDate']))->format('Y-m-d '.$start_time);
            //$end_date = (new \DateTime($formData['endDate']))->format('Y-m-d H:i:s');
            $schedule_duration = $formData['duration'];
            $schedule_session_type = $formData['sessionType'];
            $recurrences = $formData['recurrence'];
            $schedule_slots = $formData['slots'];
            $schedule_latitude = $formData['latitude'];
            $schedule_longitude = $formData['longitude'];

            $segmented_days = array();


            if($recurrences){
                foreach($recurrences as $rec) {
                    $segmented_days = array_merge($segmented_days, $this->getDateForSpecificDayBetweenDates($start_date, $end_date, $rec));
                }
            }

//            echo "<br><br>segmented days are: ";
//            print_r($segmented_days);
//            die;
            if($segmented_days){
                asort($segmented_days);
                foreach($segmented_days as $date){

                    $schedule_date = (new \DateTime($date));
                    $schedule_recurrence = $schedule_date->format('l');

                    $time_table = new ScheduleDetail();
                    $time_table->setSchedule($activity_schedule);
                    $time_table->setScheduleDate(new \DateTime($date));
                    $time_table->setDuration($schedule_duration);
                    $time_table->setRecurrence($schedule_recurrence);
                    $time_table->setSessionType($schedule_session_type);
                    $time_table->setSlots($schedule_slots);
                    $time_table->setIsCancel(0);
                    $time_table->setIsDeleted(0);
                    $time_table->setModifiedBy($loginuserid);
                    $time_table->setLatitude($schedule_latitude);
                    $time_table->setLongitude($schedule_longitude);

                    $em->persist($time_table);
                }
                $em->flush();
            }
        }
    }

    public function removeScheduleDetail($edit_schedule_id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('pa')
            ->delete('CoredirectionBundle:ScheduleDetail', 'pa')
            ->where("pa.schedule =  ( :schedule_id )")
            ->setParameter("schedule_id", $edit_schedule_id);

        $results = $query->getQuery()->getResult();
        return $results;
    }

    public function getDateForSpecificDayBetweenDates($startDate, $endDate, $weekdayNumber)
    {
        $weekdays=array("Sunday"=>0,"Monday"=>1,"Tuesday"=>2,"Wednesday"=>3,"Thursday"=>4,"Friday"=>5,"Saturday"=>6);
        $weekdayNumber = $weekdays[$weekdayNumber];

        $startDate = strtotime($startDate);
        $endDate = strtotime($endDate);

//        echo "<br><br>".$weekdayNumber."\n";
//        echo "<br><br>start date is: ".date("Y-m-d",$startDate);
//        echo "<br><br>".date("w", $startDate)."\n";


        $dateArr = array();

        do {
            if(date("w", $startDate) != $weekdayNumber) {
                $startDate += (24 * 3600); // add 1 day
                //echo "<br><br>".date("Y-m-d",$startDate);
            }
        } while(date("w", $startDate) != $weekdayNumber);

//        echo $startDate."\n";
//        echo $endDate."\n";
//        echo date("Y-m-d H:i:s",1503918060)."\n";
//        echo date("Y-m-d H:i:s",1503878400)."\n";

        if(date("Y-m-d",$startDate)== date("Y-m-d",$endDate)) {
            $dateArr[] = date('Y-m-d H:i', $startDate);
        }else {

            while ($startDate <= $endDate) {


                $dateArr[] = date('Y-m-d H:i', $startDate);
                $startDate += (7 * 24 * 3600); // add 7 days
            }
        }

        return($dateArr);
    }

    public function getActiveSchedules($scheduleId){


        $date = date_format( new \datetime(), "Y-m-d" );

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('stt')
            ->from('CoredirectionBundle:ScheduleDetail', 'stt')
            ->where('stt.scheduleDate >= :curdate')
            ->andWhere('stt.schedule = :schedule')
            ->setParameter('curdate', $date)
            ->setParameter('schedule', $scheduleId)
            ->orderBy('stt.scheduleDate','ASC');
        return $query->getQuery()->getResult();
    }

    public function getAllScheduleAllSlots($scheduleId){


        $date = date_format( new \datetime(), "Y-m-d" );

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('stt')
            ->from('CoredirectionBundle:ScheduleDetail', 'stt')
            ->where('stt.scheduleDate >= :curdate')
            ->andWhere('stt.schedule = :schedule')
            ->andWhere('stt.isCancel = 0')
            ->andWhere('stt.isDeleted = 0')
            ->setParameter('curdate', $date)
            ->setParameter('schedule', $scheduleId);
        return $query->getQuery()->getResult();
    }

    public function getScheduleDetail($activity_schedule_id, $schedule_date){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('sd')
            ->from('CoredirectionBundle:ScheduleDetail', 'sd')
            ->where("DATE_FORMAT(sd.scheduleDate, '%Y-%m-%d') = :scheduleDate")
            ->andWhere('sd.schedule = :schedule')
            ->setParameter('scheduleDate', $schedule_date)
            ->setParameter('schedule', $activity_schedule_id);

        return $query->getQuery()->getResult();
    }


    public function updateLongLatFromFacility($object, $isLocation)
    {
//        dump($object);die;
        /**
         * @var  $object ActivitySchedule
         */
        if ($isLocation) {
            $params['scheduleId'] = $object->getId();
            $params['long'] = $object->getLongitude();
            $params['lat'] = $object->getLatitude();

            $sql = "UPDATE `schedule_detail` SET longitude = :long,latitude = :lat WHERE schedule_id = :scheduleId";
            $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
            $connection = $em->getConnection();
            $stmt = $connection->prepare($sql);
            return $stmt->execute($params);
        } else {
            $params['scheduleId'] = $object->getId();
            $params['long'] = $object->getFacility()->getLongitude();
            $params['lat'] = $object->getFacility()->getLatitude();

            $sql = "UPDATE `schedule_detail` SET longitude = :long,latitude = :lat WHERE schedule_id = :scheduleId";
            $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
            $connection = $em->getConnection();
            $stmt = $connection->prepare($sql);
            return $stmt->execute($params);
        }


    }



    public function checkIfIdsInvlovedInBooking($ids = array())
    {


            $childs = implode(",",$ids);
            $params['childs'] = $childs;
            $sql = "SELECT * from `member_schedule_activity`  where schedule_detail_id IN( ".$childs.") and status = '".Shared::$BOOK."' ";
            $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
            $connection = $em->getConnection();
            $stmt = $connection->prepare($sql);
             $stmt->execute($params);
//             dump($ids,$stmt);die;
             return $stmt->fetchAll();


    }

    /**
     * @param $userId
     * @param $latitude
     * @param $longitude
     * @return mixed
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getAllActivities($userId,$latitude,$longitude,$radius,$bufferTime)
    {
        $timeBuffer = "+".$bufferTime." Minute";
        $end_date = date('Y-m-d H:i:s', strtotime($timeBuffer));
        $params['member_id']  = $userId;
        $params['unit']  = 6371;
        $params['status_booked']   = Shared::$BOOK;
        $params['status_reserved'] = Shared::$RESERVED;
        $params['status_expired'] = Shared::$EXPIRED;
        $params['status_cancel'] = Shared::$CANCELLED;
        $params['latitude'] = $latitude;
        $params['longitude'] = $longitude;
        $params['schedule_detail_end_date'] = $end_date;
        $params['range'] = $radius;
        $sqlStr = "SELECT DISTINCT
                                  s3_.schedule_id AS id,
                                  s3_.duration AS duration,
                                  a2_.is_free AS isFree,
                                  IF( a2_.is_location = 1 AND  LENGTH (a2_.pinaddress ) > 0 , a2_.pinaddress, f1_
                                  .address)  AS address,
                                  IF( a2_.is_location = 1 AND  LENGTH (a2_.pinaddress ) > 0 , a2_.pinaddress, f1_.address)  AS activity_schedule_address,
                                  CONCAT('/web/images/member/',f1_.company_logo) AS image_url,
                                  f1_.company_name AS facility_name,
                                  s3_.schedule_date AS classDate,
                                  IF(m0_.STATUS is null  ,0,1) as status,
                                  a4_.name as class_name,
                                  m0_.id AS member_schedule_activity_id,
                                                 (
                                        :unit *
                                        acos(cos(radians(:latitude)) *
                                             cos(radians(IF( a2_.is_location = 0 , f1_.latitude, a2_.latitude))) *
                                             cos(radians(IF( a2_.is_location = 0 , f1_.longitude, a2_.longitude)) -
                                                 radians(:longitude)) +
                                             sin(radians(:latitude)) *
                                             sin(radians(IF( a2_.is_location = 0 , f1_.latitude, a2_.latitude))))
                                   ) AS distance
                                FROM
                                  activity_schedule a2_
                                INNER JOIN schedule_detail s3_ ON a2_.id = s3_.schedule_id
                                INNER JOIN activity a4_ ON a2_.activity_id = a4_.id 
                                INNER JOIN fos_user_user f1_ ON a2_.facility_id = f1_.id
                                LEFT JOIN member_schedule_activity m0_ ON m0_.schedule_detail_id = s3_.id AND m0_.STATUS != :status_cancel AND m0_.member_id = :member_id
                                LEFT JOIN (
                                SELECT
                                    COUNT(id) booked_slots, schedule_detail_id
                                FROM
                                    member_schedule_activity 
                                WHERE
                                  STATUS IN (:status_booked,:status_reserved)
                                  group by schedule_detail_id
                                ) m3_ ON m3_.schedule_detail_id = s3_.id 
                                
                                LEFT JOIN
                                  (SELECT 
                                    schedule_detail_id ,IF(member_id = 359 , 1,0) self_booked
                                    FROM
                                    member_schedule_activity
                                    WHERE
                                    status IN (:status_booked , :status_reserved)
                                    GROUP BY member_id) m4_ ON m4_.schedule_detail_id = s3_.id
                                    
                            WHERE
                                a2_.is_deleted = 0 
                                
                                AND ( f1_.enabled = 1 )
                                AND s3_.is_deleted = 0 
                                AND s3_.is_cancel = 0 
                                AND s3_.schedule_date >= :schedule_detail_end_date
                                AND  (s3_.slots - IFNULL(m3_.booked_slots, 0) > 0 OR IFNULL(m4_.self_booked,1)=1 )
                                AND s3_.id NOT IN
                                (	
                                SELECT
                                    schedule_detail_id
                                FROM
                                    member_schedule_activity 
                                WHERE
                                  STATUS IN (:status_reserved,:status_expired) AND 
                                  member_id = :member_id
                                )
                                
                            GROUP BY s3_.id 
                            HAVING distance <= :range
                                    ORDER BY
                                 schedule_date ,distance
                                 LIMIT 200";

        $stmt = $this->getEntityManager()->getConnection()->prepare($sqlStr);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

}
