<?php

namespace App\Repository;

/**
 * WorkoutLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutLevelRepository extends BaseRepository
{
}
