<?php

namespace App\Repository;

/**
 * workoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workoutRepository extends BaseRepository
{
    public function saveDuration($workoutId, $formData, $loginedUserId){
        $duration = '';
        $total_seconds = 0;



        $exercise_ids = array();
        if(isset($formData['workout_exercise'])){
            $exercises = $formData['workout_exercise'];
            foreach($exercises as $exercise){
                $exercise_ids[] = $exercise ;
            }
        }
//        $exercise_ids = array_unique(array_filter($exercise_ids));
//        $exercise_ids = $exercise_ids;
        $count  = count($exercise_ids);
//       dump($formData);die;
        if(isset($formData['duration_minutes'])){
            $duration_minutes = $formData['duration_minutes'];
            // foreach($duration_minutes as $minute){
            for($i= 0; $i< $count; $i++){
                $total_seconds = $total_seconds + ($duration_minutes[$i] * 60);
            }
        }
       // print_r($formData['duration_minutes']); exit;

        if(isset($formData['duration_seconds'])){
            $duration_seconds = $formData['duration_seconds'];
           // foreach($duration_seconds as $second){
            for($i= 0; $i< $count; $i++){
                $total_seconds = $total_seconds + $duration_seconds[$i];
            }
        }

        $points = 0;
        if($total_seconds > 0){
            $points = ($total_seconds/60)*10;
            $duration = gmdate("H:i:s", $total_seconds);
        }
//        dump($duration);die;
        

        $em = $this->getEntityManager();
        $workout = $this->find($workoutId);
        $workout->setDuration($duration);
        $workout->setPoint($points);
        $em->flush();
    }

    public function Workout_Selected_Durations($workoutid){
        $results = array();
        $workout = $this->find($workoutid);
        $duration = $workout->getDuration();
        if($duration){
            $explode_duration = explode(':',$duration);
            if(isset($explode_duration[0])){
                $results['minutes'] = $explode_duration[0];
            }
            if(isset($explode_duration[1])){
                $results['seconds'] = $explode_duration[1];
            }
        }
        return $results;
    }

    public function getAllCompanyList( $userId , $companyId){

        $roles  = array('MasterFranchise', 'Corporate');
        $query  = $this->getUserByGroupQuery($roles, $userId);
        $results  = $query->getQuery()->getResult();


        $company_list = '';

        if($results) {
            $company_list .= '<div id="all_company_list" style="display: none;">';

            $company_list.='<option  value="'.''.'">Select Company </option>';
            $selected = '';
            foreach($results as $row){
                if($row->getId() == $companyId){
                    $selected = 'selected';
                }else{
                    $selected = '';
                }
                $company_list .= '<option  value="'.$row->getId().'" '.$selected.' >'.$row->getCompanyName().'</option>';
            }
            $company_list .= '</div>';
        }
        return $company_list;

    }
}
