<?php

namespace App\Repository;

/**
 * ActivityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityTypeRepository extends BaseRepository
{
    
}
