<?php

namespace App\Repository;

/**
 * AmenityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmenityRepository extends BaseRepository
{
}
