<?php

namespace App\Repository;

/**
 * AppSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppSettingRepository extends \Doctrine\ORM\EntityRepository
{

    public function getMobileInfo($param){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('Distinct u')
            ->from('CoredirectionBundle:MemberDeviceToken', 'u')
            ->where('u.isDeleted = 0 ')
        ;
        $results = $query->getQuery()->getResult();

        $array = array();
        foreach($results as $result){
            if($param == 'build')
                $array[$result->getBuild()] = $result->getBuild();
            else{
                $array[$result->getVersion()] = $result->getVersion();
            }
        }
       return $array;


    }
}
