<?php

namespace App\Repository;
use App\Entity\AppSettingLayout;

/**
 * AppSettingLayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppSettingLayoutRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveAppsettingLayouts($appsettingId, $formData, $loginedUserId){


        $layout_id = $sequence  = array();
        if(isset($formData['appsetting_layout'])){
            $layouts = $formData['appsetting_layout'];
            foreach($layouts as $layout){
                $layout_id[] = $layout ;
            }
        }

        if(isset($formData['sequence'])){
            $sequences = $formData['sequence'];
            foreach($sequences as $seq){
                $sequence[] = $seq ;
            }
        }



        if($layout_id){
            $em = $this->getEntityManager();
            $appSetting = $em->getReference('App\Entity\AppSetting', $appsettingId);

            foreach($layout_id as $key => $sec_id){
                $appsetting_layout = new AppSettingLayout();

                $appsetting_layout_sequence = '';
                if(isset($sequence[$key])){
                    $appsetting_layout_sequence .= $sequence[$key];
                }


                $layout = $em->getReference('App\Entity\Layout', $sec_id);

                $appsetting_layout->setLayout($layout);
                $appsetting_layout->setAppSetting($appSetting);
                $appsetting_layout->setModifiedBy($loginedUserId);
                $appsetting_layout->setCreatedDate(new \DateTime());
                $appsetting_layout->setSequence($appsetting_layout_sequence);


                $em->persist($appsetting_layout);

            }
            $em->flush();

        }
    }

    public function appsettingSelectedLayouts($app_setting_id){

        $full_layout_list = $this->getEntityManager('App\Entity\Layout')
            ->getRepository('App\Entity\Layout')->findBy(array('isDeleted' => 0));
        $appsetting_layouts = $this->findBy(array('appSetting' => $app_setting_id, 'isDeleted' => 0),array('sequence' => 'ASC'));
        $output = "";

        $output .= $this->getAllLayoutList();

        if($appsetting_layouts){
            $sequence = 1;
            $output .= '<div id="sortable">';
            foreach($appsetting_layouts as $layout){
                $layout_code = $layout->getLayout();
                $layout_sequence = $layout->getSequence();


                $output .= '<div class="row wrk_exerciseInput">
                            <div class="col-md-1">
                                <div class="form-group">
                                    <label class="col-md-12 control-label sequence" sequence="">'.$sequence.'</label>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Layout</label>
                                        <div class="col-md-6" id="selected_exercises_lists">
                                            <datalist name="appsetting_layout[]" class="selects">';
                if($full_layout_list){
                    foreach($full_layout_list as $exe_list){

                        if(trim($exe_list->getCode()) == trim($layout_code)){

                            $output .= '<option selected="selected" value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
                        }else{
                            $output .= '<option value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
                        }
                    }
                }
                $output .=   '</datalist>
                                                  <span class="help-block " >Select layout</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">Sequence</label>';

                $output .= '<div class="col-md-4" id="minutes_list">
                                                <datalist name="sequence[]" class="form-control selects" data-live-search="true">';
                for($i=0; $i<=120; $i++) {
                    if($layout_sequence == $i){
                        $selected = 'selected="selected"';
                    }else{
                        $selected = '';
                    }
                    $output .= '<option '.$selected.' value="'.$i.'">'.$i.'</option>';
                }
                $output .= '</datalist>
                                                <span class="help-block">Enter sequence</span>
                                            </div>
                                            
                                                ';



                $output .=  '
                                                
                                            
                                        </div>
                                    </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <button class="btn btn-primary col-md-3 control-label btnDel wrk_exerciseInput_del" INPUT_CLASS="wrk_exerciseInput">X</button>
                                    </div>
                                </div>
                        </div>';
                $sequence++;
            }
            $output .= '</div>';
        }else{
            $output .= '<div id="sortable"><div class="row wrk_exerciseInput"></div></div>';
        }

        return $output;
    }

    public function getAllLayoutList(){


        $layout_list = '';
        $full_layouts_list = $this->getEntityManager('App\Entity\Layout')
            ->getRepository('App\Entity\Layout')->findBy(array('isDeleted' => 0));

        if($full_layouts_list) {
            $layout_list .= '<div id="all_layouts_list" style="display: none;">';
            foreach($full_layouts_list as $exe_list){
                $layout_list .= '<option value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
            }
            $layout_list .= '</div>';
        }
        return $layout_list;


    }

    public function removeAppSettingLayoutData($appSettingId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->delete('CoredirectionBundle:AppSettingLayout', 'el')
            ->where("el.appSetting =  ( :appSetting_id )")
            ->setParameter("appSetting_id", $appSettingId);

        $results = $query->getQuery()->getResult();
        return $results;
    }

}
