<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use V1Bundle\Common\Shared;

/**
 * BaseLookupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseLookupRepository extends BaseRepository
{
    public function getBaseLookupQuery()
    {
        $return_data = array();

        $base_lookups = $this->findAll(array('isDeleted' => 0));


        if($base_lookups){
            foreach($base_lookups as $base_lookup){
                if($base_lookup->getIsDeleted() == 1 ){
                    continue;
                }
                if($base_lookup->getParentId()){
                    $parentname = $base_lookup->getParentId();
                    $return_data["$parentname"][$base_lookup->getId()] = $base_lookup->getName();
                }
            }
        }
        
        return $return_data;
    }

    public function getLookupsForWorkout($userGroups = array() ,$userId = null ){

        $full_model_list = $this->getModelLookups($userGroups , $userId  );

        $model_list = '';

        if($full_model_list) {
            $model_list .= '<div id="all_model_list" style="display: none;">';

            $model_list .= '<option value=""> Select</option>';
            foreach($full_model_list as $mod_list){
                $model_list .= '<option  value="'.$mod_list->getId().'">'.$mod_list->getName().'</option>';
            }
            $model_list .= '</div>';
        }
        return $model_list;


    }

    public function getLookupsForExercise($userGroups = array() ,$loginedUserId = null){

        $full_model_list = $this->getModelLookups($userGroups  ,$loginedUserId );
        $model_list = array();
        foreach($full_model_list as $mod_list){
            $model_list[$mod_list->getId()] = $mod_list->getName();
        }
        return $model_list ;
    }

    public function getModelLookups($userGroups = array()  , $userId = null ){


        $em =$this->getEntityManager();

        $modelId = $em->getRepository('CoredirectionBundle:BaseLookup')
            ->findOneBy(array('code' => 'MODEL'));


        if(in_array('superfranchise', $userGroups) ||  in_array('facility',$userGroups)
                || in_array('instructor',$userGroups)){

            $users = $this->getAllChildrenByParentId($userId);

            $users[]= $userId;

            $full_model_list  = $em->getRepository('CoredirectionBundle:BaseLookup')
                ->findBy(array('parentId' => $modelId->getId(), 'isDeleted' => 0, 'modifiedBy' => $users));

        }else {
            $full_model_list  = $em->getRepository('CoredirectionBundle:BaseLookup')
                ->findBy(array('parentId' => $modelId->getId(), 'isDeleted' => 0));
        }


        return $full_model_list;
    }

    public function getModelNameByExerciseId($exercise_id){

        $model_lists = $this->getModelLookups();
        $model_ids = array();
        foreach($model_lists as $model_list){
            $model_ids[]= $model_list->getId();
        }

        $em= $this->getEntityManager();

        $query =  $em->createQueryBuilder()
            ->select('bl.name')
            ->from('CoredirectionBundle:ExerciseLookup', 'el')
            ->innerJoin('el.exercise', 'exe')
            ->innerJoin('el.baseLookup', 'bl')
            ->where('exe.id = :exe_id')
            ->andWhere('el.baseLookup IN ( :model_ids )')
            ->setParameter('exe_id', $exercise_id)
            ->setParameter('model_ids' , $model_ids)
        ;

        $results =  $query->getQuery()->getResult();

        $name = '';
        if($results){
            foreach($results as $result){
                $name = $result['name'];
            }
        }

        return $name ;

    }

    public function getConfigurations()
    {

        $qb = $this->createQueryBuilder('base_lookup')
            ->innerJoin('base_lookup.parentId','parent_id')
            ->where('parent_id.code = :parent_id')
            ->setParameter('parent_id',Shared::APP_CONFIGURATION);
        return $qb->getQuery()->getResult();
    }
}
