<?php

namespace App\Repository;

use V1Bundle\Common\Shared;

/**
 * CorporateMemberEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateMemberEmailRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllCorporateMembers()
    {

        $now = new  \DateTime();
        $qb = $this->createQueryBuilder('cme')
            ->andWhere('cme.actionDate <= :actionDate')
            ->setParameter('actionDate',$now)
            ->andWhere('cme.status = :status')
            ->setParameter('status',Shared::PENDING);
        return $qb->getQuery()->getResult();
    }
}
