<?php

namespace App\Repository;

use App\Entity\ExerciseImage;
/**
 * ExerciseImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseImageRepository extends BaseRepository
{
    public function saveExerciseImages($exerciseId, $formData, $loginedUserId){
        $em = $this->getEntityManager();

        $sort_order = 1;
        if(isset($formData['sorting_order'])){
            $sorting_ids = $formData['sorting_order'];
            $sort_ids = explode(',',$sorting_ids);
            if(count($sort_ids) > 0){
                foreach($sort_ids as $sort_id){
                    if($sort_id){
                        $exercise_image = $this->find($sort_id);
                        $exercise_image->setSequence($sort_order);
                        $sort_order++;
                    }
                }
                $em->flush();
            }
        }

        if(isset($formData['file_names'])){
            $uploaded_images = $formData['file_names'];
            $sequence_order = $em->createQueryBuilder()
                ->select('e')
                ->from('CoredirectionBundle:ExerciseImage', 'e')
                ->where('e.exercise = :id')
                ->setParameter('id',$exerciseId)
                ->orderBy('e.sequence', 'DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();

            if($sequence_order){
                if($sequence_order->getSequence()){
                    $sorting_order = $sequence_order->getSequence() + 1;
                }else{
                    $sorting_order = 1;
                }
            }else{
                $sorting_order = 1;
            }

            $uploaded_images = explode(",",$formData['file_names']);
            if($uploaded_images){
                foreach($uploaded_images as $image){
                    if($image){
                        $decode_image = json_decode($image);
                        $image_name = $decode_image->uploaded_file_name;

                        $exercise_image = new ExerciseImage();
                        $exercise = $em->getReference('App\Entity\Exercise', $exerciseId);

                        $exercise_image->setExercise($exercise);
                        $exercise_image->setName($image_name);
                        $exercise_image->setModifiedBy($loginedUserId);
                        $exercise_image->setCreatedDate(new \DateTime());
                        $exercise_image->setSequence($sorting_order);

                        $em->persist($exercise_image);
                        $sorting_order++;
                    }
                }
                $em->flush();
            }
        }

        if(isset($formData['deleted_image_ids'])){
            $deleted_images_ids = $formData['deleted_image_ids'];
            $delete_ids = explode(',',$deleted_images_ids);
            if(count($delete_ids) > 0){
                foreach($delete_ids as $del_id){
                    if($del_id){
                        $exercise_image = $this->find($del_id);
                        $exercise_image->setIsDeleted(1);
                    }
                }
                $em->flush();
            }
        }
    }

    public function getExerciseImagesList($exerciseId, $container){

        $excercise_images_list = '';
        $exercise_images = $this->findBy(array('exercise' => $exerciseId, 'isDeleted' => 0), array('sequence' => 'ASC'));
        if ($exercise_images) {
            foreach ($exercise_images as $exercise_image) {
                if ($container->get('request')->getSchemeAndHttpHost() == 'http://localhost') {
                    $image_path = $container->get('request_stack')->getCurrentRequest()->getBasePath() . "/images/exercise/" . $exercise_image->getName();
                } else {
                    $image_path = $container->get('request_stack')->getCurrentRequest()->getBasePath() . "/web/images/exercise/" . $exercise_image->getName();
                }

                $excercise_images_list .= '<li class="ui-state-default images_seq_info" image_id="' . $exercise_image->getId() . '" image_name="' . $exercise_image->getName() . '" ><div class="ui-icon ui-icon-circle-minus" > </div><img src="' . $image_path . '" width="97px" height="80px" /></li>';
            }
        }
        return $excercise_images_list;
    }
}
