<?php

namespace App\Repository;

/**
 * FacilityActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilityActivityRepository extends BaseRepository
{
    
}
