<?php

namespace App\Repository;

/**
 * FacilityCheckinHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilityCheckinHistoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function checkIfAlreadyCheckIn($facilityObj,$userObj)
    {

        $now = new \DateTime();
        $now =$now->setTime(00, 00, 00);
        $end = new \DateTime();
        $end = $end->setTime(23,23,59);
        $query = $this->createQueryBuilder('fch');
        $query
            ->where('fch.facility = :facility_id')
            ->andWhere('fch.member = :member')
            ->andWhere('fch.time BETWEEN :today_start_time AND :today_end_time ')
            ->setParameter('facility_id',$facilityObj)
            ->setParameter('member',$userObj)
            ->setParameter('today_end_time',$end)
            ->setParameter('today_start_time',$now);

        $result = $query->getQuery()->getResult();
        return count($result) ? 1 : 0;
    }
}
