<?php

namespace App\Repository;

use App\Entity\FacilityGallery;

/**
 * FacilityGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilityGalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveFacilityGalleryImages($facilityid, $formData, $loginedUserId){
        $em = $this->getEntityManager();

        $sort_order = 1;
        if(isset($formData['sorting_order'])){
            $sorting_ids = $formData['sorting_order'];
            $sort_ids = explode(',',$sorting_ids);
            if(count($sort_ids) > 0){
                foreach($sort_ids as $sort_id){
                    if($sort_id){
                        $facility_gallery_image = $this->find($sort_id);
                        $facility_gallery_image->setSequence($sort_order);
                        $sort_order++;
                    }
                }
                $em->flush();
            }
        }

        if(isset($formData['file_names'])){
            $uploaded_images = $formData['file_names'];
            $sequence_order = $em->createQueryBuilder()
                ->select('e')
                ->from('CoredirectionBundle:FacilityGallery', 'e')
                ->where('e.facility = :id')
                ->setParameter('id',$facilityid)
                ->orderBy('e.sequence', 'DESC')
                ->setMaxResults(1)
                ->getQuery()
                ->getOneOrNullResult();

            if($sequence_order){
                if($sequence_order->getSequence()){
                    $sorting_order = $sequence_order->getSequence() + 1;
                }else{
                    $sorting_order = 1;
                }
            }else{
                $sorting_order = 1;
            }

            $uploaded_images = explode(",",$formData['file_names']);
            if($uploaded_images){
                foreach($uploaded_images as $image){
                    if($image){
                        $decode_image = json_decode($image);
                        $image_name = $decode_image->uploaded_file_name;

                        $facility_gallery = new FacilityGallery();
                        $facility = $em->getReference('Application\Sonata\UserBundle\Entity\User', $facilityid);

                        $facility_gallery->setFacility($facility);
                        $facility_gallery->setImageName($image_name);
                        $facility_gallery->setModifiedby($loginedUserId);
                        $facility_gallery->setCreatedDate(new \DateTime());
                        $facility_gallery->setSequence($sorting_order);

                        $em->persist($facility_gallery);
                        $sorting_order++;
                    }
                }
                $em->flush();
            }
        }

        if(isset($formData['deleted_image_ids'])){
            $deleted_images_ids = $formData['deleted_image_ids'];
            $delete_ids = explode(',',$deleted_images_ids);
            if(count($delete_ids) > 0){
                foreach($delete_ids as $del_id){
                    if($del_id){
                        $facility_gallery_image = $this->find($del_id);
                        $facility_gallery_image->setIsDeleted(1);
                    }
                }
                $em->flush();
            }
        }
    }

    public function getFacilityImagesList($facilityId, $container){

        $facility_images_list = '';
        $facility_images = $this->findBy(array('facility' => $facilityId, 'isDeleted' => 0), array('sequence' => 'ASC'));
        if ($facility_images) {
            foreach ($facility_images as $facility_image) {
                if ($container->get('request')->getSchemeAndHttpHost() == 'http://localhost') {
                    $image_path = $container->get('request_stack')->getCurrentRequest()->getBasePath() . "/images/gallery/facility/" . $facility_image->getImageName();
                } else {
                    $image_path = $container->get('request_stack')->getCurrentRequest()->getBasePath() . "/web/images/gallery/facility/" . $facility_image->getImageName();
                }

                $facility_images_list .= '<li class="ui-state-default images_seq_info" image_id="' . $facility_image->getId() . '" image_name="' . $facility_image->getImageName() . '" ><div class="ui-icon ui-icon-circle-minus" > </div><img src="' . $image_path . '" width="190px" height="185px" /></li>';
            }
        }
        return $facility_images_list;
    }
}
