<?php

namespace App\Repository;
use App\Entity\LayoutSections;
/**
 * LayoutSectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LayoutSectionsRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveLayoutSections($layoutId, $formData, $loginedUserId){


        $section_id = $sequence  = array();
        if(isset($formData['layout_section'])){
            $sections = $formData['layout_section'];
            foreach($sections as $section){
                $section_id[] = $section ;
            }
        }

        if(isset($formData['sequence'])){
            $sequences = $formData['sequence'];
            foreach($sequences as $seq){
                $sequence[] = $seq ;
            }
        }

     

        if($section_id){
            $em = $this->getEntityManager();
            $layout = $em->getReference('App\Entity\Layout', $layoutId);

            foreach($section_id as $key => $sec_id){
                $layout_section = new LayoutSections();

                $layout_section_sequence = '';
                if(isset($sequence[$key])){
                    $layout_section_sequence .= $sequence[$key];
                }


                $section = $em->getReference('App\Entity\Sections', $sec_id);

                $layout_section->setLayout($layout);
                $layout_section->setSection($section);
                $layout_section->setModifiedBy($loginedUserId);
                $layout_section->setCreatedDate(new \DateTime());
                $layout_section->setSequence($layout_section_sequence);


                $em->persist($layout_section);

            }
            $em->flush();

        }
    }

    public function layoutSelectedSections($layout_id){

        $full_section_list = $this->getEntityManager('App\Entity\Layout')->getRepository('App\Entity\Sections')->findBy(array('isDeleted' => 0));
        $layout_sections = $this->findBy(array('layout' => $layout_id, 'isDeleted' => 0),array('sequence' => 'ASC'));
        $output = "";

        $output .= $this->getAllSectionsList();

        if($layout_sections){
            $sequence = 1;
            $output .= '<div id="sortable">';
            foreach($layout_sections as $section){
                $section_code = $section->getSection();
                $section_sequence = $section->getSequence();


                $output .= '<div class="row wrk_exerciseInput">
                            <div class="col-md-1">
                                <div class="form-group">
                                    <label class="col-md-12 control-label sequence" sequence="">'.$sequence.'</label>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Section</label>
                                        <div class="col-md-6" id="selected_exercises_lists">
                                            <datalist name="workout_exercise[]" class="selects">';
                if($full_section_list){
                    foreach($full_section_list as $exe_list){
                        if(trim($exe_list->getCode()) == trim($section_code)){
                            $output .= '<option selected="selected" value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
                        }else{
                            $output .= '<option value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
                        }
                    }
                }
                $output .=   '</datalist>
                                                  <span class="help-block " >Select section</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">Sequence</label>';

                $output .= '<div class="col-md-4" id="minutes_list">
                                                <datalist name="duration_minutes[]" class="form-control selects" data-live-search="true">';
                for($i=0; $i<=120; $i++) {
                    if($section_sequence == $i){
                        $selected = 'selected="selected"';
                    }else{
                        $selected = '';
                    }
                    $output .= '<option '.$selected.' value="'.$i.'">'.$i.'</option>';
                }
                $output .= '</datalist>
                                                <span class="help-block">Enter sequence</span>
                                            </div>
                                            
                                                ';



                $output .=  '
                                                
                                            
                                        </div>
                                    </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <button class="btn btn-primary col-md-3 control-label btnDel wrk_exerciseInput_del" INPUT_CLASS="wrk_exerciseInput">X</button>
                                    </div>
                                </div>
                        </div>';
                $sequence++;
            }
            $output .= '</div>';
        }else{
            $output .= '<div id="sortable"><div class="row wrk_exerciseInput"></div></div>';
        }

        return $output;
    }

    public function getAllSectionsList(){


        $sections_list = '';
        $full_sections_list = $this->getEntityManager('App\Entity\Sections')
            ->getRepository('App\Entity\Sections')->findBy(array('isDeleted' => 0));

        if($full_sections_list) {
            $sections_list .= '<div id="all_sections_list" style="display: none;">';
            foreach($full_sections_list as $exe_list){
                $sections_list .= '<option value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
            }
            $sections_list .= '</div>';
        }
        return $sections_list;


    }

    public function removeWorkoutExerciseData($layoutId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->delete('CoredirectionBundle:LayoutSections', 'el')
            ->where("el.layout =  ( :layout_id )")
            ->setParameter("layout_id", $layoutId);

        $results = $query->getQuery()->getResult();
        return $results;
    }

}
