<?php

namespace App\Repository;



/**
 * LookupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LookupRepository extends BaseRepository {

   

}
