<?php

namespace App\Repository;

/**
 * ManualCheckinHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManualCheckinHistoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function checkIfAlreadyCheckIn($activityObj,$userObj,$now)
    {

        $now =$now->setTime(00, 00, 00);
        $end = new \DateTime();
        $end = $end->setTime(23,23,59);
        $query = $this->createQueryBuilder('mch');
        $query
            ->where('mch.activity= :activity_id')
            ->andWhere('mch.member = :member')
            ->andWhere('mch.time BETWEEN :today_start_time AND :today_end_time ')
            ->setParameter('activity_id',$activityObj)
            ->setParameter('member',$userObj)
            ->setParameter('today_end_time',$end)
            ->setParameter('today_start_time',$now);

        $result = $query->getQuery()->getResult();
        return count($result) ? 1 : 0;
    }
}
