<?php

namespace App\Repository;

/**
 * BillingHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getScheduleDataByBillingId($memberBillingHistoryId){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('msa.createdDate')
            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
            ->innerJoin('mbd.memberbilling', 'mb')
            ->innerJoin('mbd.booking', 'msa')
            ->where('mb.id = :memberbilingId');
        $query->setParameter('memberbilingId', $memberBillingHistoryId);

        $result  =   $query->getQuery()->getResult();

        if($result) {
            return $result[0]['createdDate']->format("Y-m-d");
        }else{
            return '';
        }
    }
}
