<?php

namespace App\Repository;

/**
 * MemberDeviceTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberDeviceTokenRepository extends BaseRepository
{
    public function getUserByGroupQuery($group_name, $userId = null)
    {
        if ($userId) {
            $users = $this->getAllChildrenByParentId($userId);
        }
        $users[] = $userId;

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('u')
            ->from('ApplicationSonataUserBundle:User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('u.id IN ( :parent) ')
            ->orWhere("g.code IN  ( :code )")
            //->orWhere('u.id IN ( :currentUser) ')
            ->setParameter("parent", $users)
            ->setParameter("code", $group_name)//->setParameter("currentUser", $userId)
        ;

        return $query;
    }

    /**
     * @param string $deviceType
     * @return mixed
     */
    public function getDeviceSpecificUsersCount($timePeriod,$deviceType = 'iphone')
    {

        if($timePeriod == 1){
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder('d')
                ->select('count(d.id) as no_of_users , DATE_FORMAT(d.createdDate,\'%Y-%b\') as created_at')
                ->from('CoredirectionBundle:MemberDeviceToken', 'd')
                ->where('d.deviceType  = :deviceType ')
                ->andWhere('d.createdDate  >= :intervalTime')
                 ->groupBy('created_at')
                ->setParameter('deviceType',$deviceType)
                ->setParameter('intervalTime', new \DateTime('-7 days'));
//          dump($query->getQuery()->getResult());die;
            return $query->getQuery()->getResult();
        }elseif ($timePeriod == 2){
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder('d')
                ->select('count(d.id) as no_of_users , DATE_FORMAT(d.createdDate,\'%Y-%b\') as created_at')
                ->from('CoredirectionBundle:MemberDeviceToken', 'd')
                ->where('d.deviceType  = :deviceType ')
                ->andWhere('d.createdDate  >= :intervalTime')
                ->groupBy('created_at')
                ->setParameter('deviceType',$deviceType)
                ->setParameter('intervalTime', new \DateTime('-30 days'));
//          dump($query->getQuery()->getResult());die;
            return $query->getQuery()->getResult();
        }elseif ($timePeriod == 3){
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder('d')
                ->select('count(d.id) as no_of_users , DATE_FORMAT(d.createdDate,\'%Y-%b\') as created_at')
                ->from('CoredirectionBundle:MemberDeviceToken', 'd')
                ->where('d.deviceType  = :deviceType ')
                ->andWhere('d.createdDate  >= :intervalTime')
                ->groupBy('created_at')
                ->setParameter('deviceType',$deviceType)
                ->setParameter('intervalTime', new \DateTime('-2 months'));
//          dump($query->getQuery()->getResult());die;
            return $query->getQuery()->getResult();
        }elseif ($timePeriod == 6){
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder('d')
                ->select('count(d.id) as no_of_users , DATE_FORMAT(d.createdDate,\'%Y-%b\') as created_at')
                ->from('CoredirectionBundle:MemberDeviceToken', 'd')
                ->where('d.deviceType  = :deviceType ')
                ->andWhere('d.createdDate  >= :intervalTime')
                ->groupBy('created_at')
                ->setParameter('deviceType',$deviceType)
                ->setParameter('intervalTime', new \DateTime('-6 months'));
//          dump($query->getQuery()->getResult());die;
            return $query->getQuery()->getResult();
        }elseif ($timePeriod == 12){


//    die('sdsds');

            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder('d')
                ->select(' COUNT(DISTINCT d.id)  as no_of_users , DATE_FORMAT(d.createdDate,\'%Y-%b\') as created_at')->distinct(true)
                ->from('CoredirectionBundle:MemberDeviceToken', 'd')
                ->where('d.deviceType  = :deviceType ')
                ->andWhere('d.createdDate  >= :intervalTime')
                ->groupBy('created_at')
                ->setParameter('deviceType',$deviceType)
                ->setParameter('intervalTime', new \DateTime('-12 months'));
//          dump($query->getQuery()->getResult());die;
            return $query->getQuery()->getResult();
        }elseif ($timePeriod == 'today'){
            $em = $this->getEntityManager();
            $query = $em->createQueryBuilder('d')
                ->select('count(d.id) as no_of_users , DATE_FORMAT(d.createdDate,\'%Y-%b\') as created_at')
                ->from('CoredirectionBundle:MemberDeviceToken', 'd')
                ->where('d.deviceType  = :deviceType ')
                ->andWhere('d.createdDate  >= :intervalTime')
                ->groupBy('created_at')
                ->setParameter('deviceType',$deviceType)
                ->setParameter('intervalTime', new \DateTime('-1 day'));
//          dump($query->getQuery()->getResult());die;
            return $query->getQuery()->getResult();
        }


    }
}
