<?php

namespace App\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * MemberBillingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberBillingDetailRepository extends \Doctrine\ORM\EntityRepository
{
    public function isUserPaymentComplete($memberId, $memberPackageId){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('mbd')
            ->select('count(mbd.id)')
            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
            ->innerJoin('mbd.memberbilling', 'mb')
            ->where('mbd.memberPackage = :memberPackageId')
            ->andWhere('mb.user = :memberId')
            ->setParameter('memberPackageId',$memberPackageId)
            ->setParameter('memberId', $memberId);
        $result = $query->getQuery()->getSingleScalarResult();
      
        if($result >0 ){
            return true;
        }else{
            return false;
        }
    }

    public function getTotalSale($users){

        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder('mbd')
            ->select('sum(mbd.amount)')
            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
            ->innerJoin('mbd.memberPackage','mp')
            ->innerJoin('mp.package','pkg')
            ->where('pkg.facility IN ( :user ) ')
            ->setParameter("user", $users)
        ;
//        dump($query->getQuery());die();
        $result =  $query->getQuery()->getSingleScalarResult();
        if(!$result){
            $result = 0;
        }
        return  $result;
    }


	public function getTotalSaleForGraphView($users,$viewType,$start='',$end=''){

		if($viewType == 'month'){
			$em = $this->getEntityManager();
			$query = $em->createQueryBuilder('mbd')
			            ->select('sum(mbd.amount) as total_amount,  DATE_FORMAT(mbd.createdDate,\'%Y-%M\') AS createdDate')
			            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
			            ->innerJoin('mbd.memberPackage','mp')
			            ->innerJoin('mp.package','pkg')
			            ->where('pkg.facility IN ( :user ) ')
						->groupBy('createdDate')
						->orderBy('mbd.createdDate','ASC')
			            ->setParameter("user", $users);
		}elseif ($viewType == 'day'){
			$em = $this->getEntityManager();
			$query = $em->createQueryBuilder('mbd')
			            ->select('sum(mbd.amount) as total_amount,  DATE_FORMAT(mbd.createdDate,\'%Y-%M-%d\') AS createdDate')
			            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
			            ->innerJoin('mbd.memberPackage','mp')
			            ->innerJoin('mp.package','pkg')
			            ->where('pkg.facility IN ( :user ) ')
						->groupBy('createdDate')
						->orderBy('mbd.createdDate','ASC')
			            ->setParameter("user", $users);

		}
		if($start && $end){
			$query->andWhere('mbd.createdDate  BETWEEN :start AND :end')
			      ->setParameter('start', new \DateTime($start))
			      ->setParameter('end', new \DateTime($end));
		}

		$result =  $query->getQuery()->getResult();
		if(!$result){
			$result = 0;
		}
		return  $result;
	}
    
    public function getDashboardTotalSaleGraph($users,  $timeperiod){
//
//
//        if($timeperiod){
////
//            if ($timeperiod == "1") {
////                $start = date('Y-m-d', strtotime('Monday last week'));
////                $end = date('Y-m-d', strtotime('Sunday last week'));
//                $start = date('Y-m-d', strtotime('-7 days'));
//                $end = date('Y-m-d', strtotime('+1 days'));
//
//            } elseif ($timeperiod == "2") {
////                $last_month = date('m', strtotime('last month'));
////                $last_year_month = date('Y-m', strtotime('last month'));
////                $end_months = array('01', '03', '05', '07', '08', '10', '12');
////                if (in_array($last_month, $end_months)) {
////                    $month_end = '31';
////                } else {
////                    $month_end = '30';
////                }
//
//	            $start = date('Y-m-d', strtotime('-30 days'));
//	            $end = date('Y-m-d', strtotime('+1 days'));
//
//
//            } else {
//
//                $interval = $timeperiod;
//                $end = date('Y-m-d');
//                $start = date('Y-m-d', strtotime("-" . $interval . " month"));
//
//            }
//
//        }
//
//        $em = $this->getEntityManager();
//
//        $query = $em->createQueryBuilder('mbd')
//            ->select('Sum(mbd.amount) as total_amount, DATE_FORMAT(mbd.createdDate,\'%Y-%M-%d\') as createdDate')
//            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
//            //->innerJoin('mbd.memberbilling','mb')
//            ->innerJoin('mbd.memberPackage','mp')
//            ->innerJoin('mp.package','pkg')
//            ->where('pkg.facility IN ( :user ) ')
//
//            ->setParameter("user", $users)
//            ->groupBy('mbd.createdDate')
//        ;
//
//        if($timeperiod){
//
//            $query->andWhere('mbd.createdDate  BETWEEN :start AND :end')
//                ->setParameter('start', new \DateTime($start))
//                ->setParameter('end', new \DateTime($end))
//            ;
//        }
//
//        return  $query->getQuery()->getResult();



        if($timeperiod){

            if ($timeperiod == "1") {
//                $start = date('Y-m-d', strtotime('Monday last week'));
//                $end = date('Y-m-d', strtotime('Sunday last week'));
                $start = date('Y-m-d', strtotime('-7 days'));
                $end = date('Y-m-d', strtotime('+1 days'));

            } elseif ($timeperiod == "2") {
//                $last_month = date('m', strtotime('last month'));
//                $last_year_month = date('Y-m', strtotime('last month'));
//                $end_months = array('01', '03', '05', '07', '08', '10', '12');
//                if (in_array($last_month, $end_months)) {
//                    $month_end = '31';
//                } else {
//                    $month_end = '30';
//                }

                $start = date('Y-m-d', strtotime('-30 days'));
                $end = date('Y-m-d', strtotime('+1 days'));


            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

            }

        }

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $childs = implode(",",$users);
        if($timeperiod == 1 || $timeperiod == 2 || $timeperiod == 'today'){

            $statement = $connection->prepare("SELECT sum(m4_.amount) total_amount, DATE_FORMAT(m0_.created_date,'%Y-%M-%d') AS createdDate
FROM member_package m0_
INNER JOIN package p1_ ON m0_.package_id = p1_.id
INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id
  WHERE     
             p1_.facility_id IN ($childs) 
 group by createdDate
");
        }else{
            $statement = $connection->prepare("SELECT sum(m4_.amount) total_amount, DATE_FORMAT(m0_.created_date,'%Y-%M') AS createdDate
FROM member_package m0_
INNER JOIN package p1_ ON m0_.package_id = p1_.id
INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id
            WHERE     
             p1_.facility_id IN ($childs) 
 group by createdDate");
        }
        $statement->execute();
        $childs = implode(",",$users);
//        $statement->bindValue('facilities', $childs);
        $results = $statement->fetchAll();
//        dump($results);die;
        return $results;


//
//
//
//
//        $query = $em->createQueryBuilder('mbd')
//            ->select('Sum(mbd.amount) as total_amount, DATE_FORMAT(mbd.createdDate,\'%Y-%M\') as createdDate')
//            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
//            //->innerJoin('mbd.memberbilling','mb')
//            ->innerJoin('mbd.memberPackage','mp')
//            ->innerJoin('mp.package','pkg')
//            ->where('pkg.facility IN ( :user ) ')
//
//            ->setParameter("user", $users)
//            ->groupBy('mbd.createdDate')
//        ;
//
//        if($timeperiod){
//
//            $query->andWhere('mbd.createdDate  BETWEEN :start AND :end')
//                ->setParameter('start', new \DateTime($start))
//                ->setParameter('end', new \DateTime($end))
//            ;
//        }
//
//        return  $query->getQuery()->getResult();



    }



    public function getDashboardTotalSaleGraphMonthView($users,  $timeperiod){


        if($timeperiod){

            if ($timeperiod == "1") {
//                $start = date('Y-m-d', strtotime('Monday last week'));
//                $end = date('Y-m-d', strtotime('Sunday last week'));
                $start = date('Y-m-d', strtotime('-7 days'));
                $end = date('Y-m-d', strtotime('+1 days'));

            } elseif ($timeperiod == "2") {
//                $last_month = date('m', strtotime('last month'));
//                $last_year_month = date('Y-m', strtotime('last month'));
//                $end_months = array('01', '03', '05', '07', '08', '10', '12');
//                if (in_array($last_month, $end_months)) {
//                    $month_end = '31';
//                } else {
//                    $month_end = '30';
//                }

                $start = date('Y-m-d', strtotime('-30 days'));
                $end = date('Y-m-d', strtotime('+1 days'));


            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

            }

        }



//



        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        if($timeperiod == 1 || $timeperiod == 2 || $timeperiod == 'today'){

            $statement = $connection->prepare("SELECT sum(m4_.amount) total_amount, DATE_FORMAT(m0_.created_date,'%Y-%M-%d') AS createdDate
FROM member_package m0_
INNER JOIN package p1_ ON m0_.package_id = p1_.id
INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id
 group by createdDate
");
        }else{
            $statement = $connection->prepare("SELECT sum(m4_.amount) total_amount, DATE_FORMAT(m0_.created_date,'%Y-%M') AS createdDate
FROM member_package m0_
INNER JOIN package p1_ ON m0_.package_id = p1_.id
INNER JOIN package_type p2_ ON p1_.package_type_id = p2_.id
INNER JOIN fos_user_user f3_ ON m0_.member_id = f3_.id
INNER JOIN member_billing_detail m4_ ON m0_.id = m4_.member_package_id
 group by createdDate");
        }
//        $childs = implode(",",$childs);
//        $statement->bindValue('facilities', $childs);
        $statement->execute();
        $results = $statement->fetchAll();
//        dump($results);die;
        return $results;







//
//
//
//
//        $query = $em->createQueryBuilder('mbd')
//            ->select('Sum(mbd.amount) as total_amount, DATE_FORMAT(mbd.createdDate,\'%Y-%M\') as createdDate')
//            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
//            //->innerJoin('mbd.memberbilling','mb')
//            ->innerJoin('mbd.memberPackage','mp')
//            ->innerJoin('mp.package','pkg')
//            ->where('pkg.facility IN ( :user ) ')
//
//            ->setParameter("user", $users)
//            ->groupBy('mbd.createdDate')
//        ;
//
//        if($timeperiod){
//
//            $query->andWhere('mbd.createdDate  BETWEEN :start AND :end')
//                ->setParameter('start', new \DateTime($start))
//                ->setParameter('end', new \DateTime($end))
//            ;
//        }
//
//        return  $query->getQuery()->getResult();
    }

    public function getDashboardTotalSaleGraphFromAndTo($users, $fromDate, $toDate)
    {


        $start = $fromDate;
        $end = $toDate;

        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder('mbd')
            ->select('Sum(mbd.amount) as total_amount, mbd.createdDate')
            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
            //->innerJoin('mbd.memberbilling','mb')
            ->innerJoin('mbd.memberPackage', 'mp')
            ->innerJoin('mp.package', 'pkg')
            ->where('pkg.facility IN ( :user ) ')
            ->setParameter("user", $users)
            ->groupBy('mbd.createdDate');

        $query->andWhere('mbd.createdDate  BETWEEN :start AND :end')
            ->setParameter('start', new \DateTime($start))
            ->setParameter('end', new \DateTime($end));

        return $query->getQuery()->getResult();
    }

    public function getFacilityPackageTotalSale($users,$packageType,$timeperiod = null){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('mbd')
            ->select('count(mbd.amount)')
            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
            ->innerJoin('mbd.memberPackage','mp')
            ->innerJoin('mp.package','pkg')
            ->innerJoin('pkg.packageType','ptype')
            ->where('ptype.name = :type ')
            ->andWhere('mp.isDeleted = 0 ')
            ->andWhere('pkg.facility IN ( :user )')
            ->setParameter("type", $packageType)
            ->setParameter("user", $users)
        ;
        return  $query->getQuery()->getSingleScalarResult();
    }

    public function getFacilitySoldPackageByType($facilityId, $pkgType , $timeperiod){


        $start = $end = "";


        if ($timeperiod == "1") {
//            $start = date('Y-m-d', strtotime('Monday last week'));
//            $end = date('Y-m-d', strtotime('Sunday last week'));
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');


        } elseif ($timeperiod == "2") {
            $last_month = date('m', strtotime('last month'));
            $last_year_month = date('Y-m', strtotime('last month'));
            $end_months = array('01', '03', '05', '07', '08', '10', '12');
            if (in_array($last_month, $end_months)) {
                $month_end = '31';
            } else {
                $month_end = '30';
            }

            $start = $last_year_month . '-01';
            $end = $last_year_month . '-' . $month_end;

        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

        }


        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder('p')
            ->select('count(pkg.id) as total_sold, pkg.createdDate')
            ->from('CoredirectionBundle:MemberBillingDetail', 'mbd')
            ->innerJoin('mbd.memberPackage','mp')
            ->innerJoin('mp.package','pkg')
            ->innerJoin('pkg.packageType','ptype')
            ->where('ptype.name = :type ')
            ->andWhere('mp.isDeleted = 0 ')
            ->andWhere('pkg.facility IN ( :user )')
            ->setParameter("type", $pkgType)
            ->setParameter("user", $facilityId)
            ->groupBy('pkg.createdDate')
        ;

        if($timeperiod){
            $query->andWhere("DATE_FORMAT(pkg.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);
        }
        return $query->getQuery()->getResult();
    }


    public function fetchRevenueListing(Request $request)
    {


        $sql = "SELECT *
from ((SELECT t2.currency,t2.amount,t2.date,t2.email,t2.user_name,t2.phone,t2.product_id, t2.product_type, t2.last_four,t2.subscription_id,
CASE WHEN t2.package_name IS NOT NULL 
THEN t2.package_name
ELSE t2.challenge_title
END 
AS name
from (SELECT t1.currency,t1.amount,t1.date,t1.user_name,t1.email,t1.phone,t1.product_id, t1.product_type, t1.last_four,t1.subscription_id, IF(t1.product_type = 'challenge', challenge.title, NULL) as challenge_title, IF(t1.product_type != 'challenge' or t1.product_type IS NULL, package.name, NULL) as package_name FROM ( SELECT s.id subscription_id,s.product_id,sb.amount,sb.currency,s.email,CONCAT(s.firstName,' ',s.lastName) as user_name,sb.updated_date as date,s.phone, s.product_type,sb.last_four as last_four FROM subscription_billing sb INNER JOIN subscription s ON s.id = sb.subscription_id ) as t1 LEFT JOIN challenge on t1.product_id = challenge.id LEFT JOIN package on t1.product_id = package.id) as t2 )

UNION
(SELECT mb.currency,mb.amount,mbd.updated_date as date,fuu.email as emial,CONCAT(fuu.firstname,' ',fuu.lastname) as user_name,fuu.phone as phone,p.id as product_id,mb.transaction_type as product_type,mb.last_four as last_four,mb.id as subscription_id,p.name as name FROM member_billing_detail as mbd 
INNER JOIN member_billing mb ON mb.id = mbd.member_billing_id
INNER JOIN fos_user_user fuu ON fuu.id = mb.user_id
INNER JOIN member_package mp ON mp.id = mbd.member_package_id
INNER JOIN package p ON p.id= mp.package_id)) as x where product_id > 0";

        $em = $this->getEntityManager(); // ...or getEntityManager() prior to Symfony 2.1
        $connection = $em->getConnection();
        $stmtCount = $connection->prepare($sql);
        $stmtCount->execute();

        $countData = $stmtCount->rowCount();

        $columns = [
          0=>'product_id',
          1=>'user_name',
          2=>'email',
          3=>'name',
          4=>'product_type',
          5=>'last_four',
          6=>'amount',
          7=>'currency',
          8=>'date',
        ];
        $limit = $request->get('length');  //25
        $start = $request->get('start'); // 0
        $order = $columns[$request->get('order')[0]['column']];  //name
        $dir = $request->get('order')[0]['dir']; //desc
        $search = $request->get('search')['value'];  // ""
        $filter = $request->get('filter');
        $filterType = $request->get('filterType');
        $startDate = $request->get('startDate');
        $endDate = $request->get('endDate');

//        dump($startDate,$endDate);die;
        if($startDate != "-1" and $endDate != "-1"){


            $sql .= " AND date BETWEEN '".$startDate." 00:00:00 ' AND '".$endDate." 23:59:59'";
        }
        if ($search){

            $sql .= " AND (currency like '%" . $search . "%'";
            $sql .= " OR amount like '%" . $search . "%'";
            $sql .= " OR user_name like '%" . $search . "%'";
            $sql .= " OR email like '%" . $search . "%'";
            $sql .= " OR phone like '%" . $search . "%'";
            $sql .= " OR product_type like '%" . $search . "%'";
            $sql .= " OR last_four like '%" . $search . "%'";
            $sql .= " OR name like '%" . $search . "%')";
        }

        $sql .= " ORDER BY ".$order." ".$dir;

        $sqlPagination = $sql;
        if($limit != "-1") {
            $sqlPagination .=" LIMIT " . $limit . " OFFSET " . $start;
        }


        $connectionData = $em->getConnection();
        $stmt = $connectionData->prepare($sql);
        $stmt->execute();

        $connectionPagination = $em->getConnection();
        $stmtPagination = $connectionPagination->prepare($sqlPagination);
        $stmtPagination->execute();

        return array(
                'status' => true,
                'data' => $stmtPagination->fetchAll(),
                "recordsTotal" => $countData,
                "recordsFiltered" => $stmt->rowCount(),
                'message' => ' '
        );

    }
}
