<?php

namespace App\Repository;
use Doctrine\ORM\Query\Expr\Base;

/**
 * MemberWorkoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberWorkoutRepository extends BaseRepository
{
}
