<?php

namespace App\Repository;

use Application\Sonata\UserBundle\Entity\User;
use V1Bundle\Common\Shared;

/**
 * MemberInvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberInvitationRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkIfEmailSent($email,User $corporate,$code)
    {

        $qb = $this->createQueryBuilder('mi')
            ->where("mi.email = :email")
            ->innerJoin('App\Entity\CorporateKey','ck','WITH','ck.id = mi.corporate_key')
            ->andWhere('ck.corporate = :corporate')
            ->andWhere('ck.companyKey = :companyKey')
            ->andWhere('ck.type = :type')
            ->setParameter('type',Shared::$KEY_TYPE_Referral)
            ->setParameter('email',$email)
            ->setParameter('companyKey',$code)
            ->setParameter('corporate',$corporate);

        return $qb->getQuery()->getResult();
    }

    public function checkIfEmailSentWithEmail($email,User $corporate)
    {

        $qb = $this->createQueryBuilder('mi')
            ->where("mi.email = :email")
            ->innerJoin('App\Entity\CorporateKey','ck','WITH','ck.id = mi.corporate_key')
            ->andWhere('ck.corporate = :corporate')
            ->andWhere('ck.type = :type')
            ->setParameter('type',Shared::$KEY_TYPE_Referral)
            ->setParameter('email',$email)
            ->setParameter('corporate',$corporate);

        try {
            return $qb->getQuery()->getSingleResult();
        }catch (\Exception $exception){
            return null;
        }
    }
}
