<?php

namespace App\Repository;

/**
 * MemberActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberActionRepository extends BaseRepository
{
    public function SessionSalesCount($username){
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('pkg.isCorepass  =  0 ');


        $query->setParameter('code', 'Session')
            ->select('count(u.username) as total')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')
//            ->where('ptype.code  =  :code ')
//            ->setParameter('code', 'Session')
            ->groupBy('u.id');
        if ($username) {
            $query->andWhere('u.companyName like :name')
                ->setParameter(':name', "%$username%");
        }

        return $query;
    }

    public function SessionSalesReport($username, $sortby, $orderby, $offset, $limit, $timeperiod = null){

        $dateLimit = '';
        if($timeperiod){

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }

        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('pkg.isCorepass  =  0 ')
            ->setParameter('code', 'Session')
            ->select('u.companyName, count(pkg.id) as total_available, count(mpkg.id) as total_sold, sum(mbd.amount) as total_amt')
            ->groupBy('u.id')
            ->orderBy($sortby, $orderby);

        if($limit){
            $query->setFirstResult($offset)
                  ->setMaxResults($limit);
        }
        
        if ($username) {
            $query->
            andWhere('u.companyName  =  :companyName ')
                ->setParameter('companyName', $username);
        }

        if($timeperiod){
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
            ->setParameter('start', new \DateTime($start))
            ->setParameter('end', new \DateTime($end))
            ;
        }


        return $query;
    }

    function MembershipSalesCount($username){
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('pkg.isCorepass  =  0 ');


        $query->setParameter('code', 'Membership')
            ->select('count(u.username) as total')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')
//            ->where('ptype.code  =  :code ')
//            ->setParameter('code', 'Session')
            ->groupBy('u.id');
        if ($username) {
            $query->andWhere('u.companyName like :name')
                ->setParameter(':name', "%$username%");
        }

        return $query;
    }

    public function MembershipSalesReport($username, $sortby, $orderby, $offset, $limit, $timeperiod = null){

        if($timeperiod){

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }


        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('pkg.isCorepass  =  0 ')
            ->setParameter('code', 'Membership')
            ->select('u.companyName, count(pkg.id) as total_available, count(mpkg.id) as total_sold, sum(mbd.amount) as total_amt')
            ->groupBy('u.id')
            ->orderBy($sortby, $orderby);

        if($limit){
            $query->setFirstResult($offset)
                  ->setMaxResults($limit);
        }
        
        if ($username) {
            $query->
            andWhere('u.companyName  =  :companyName ')
                ->setParameter('companyName', $username);
        }

        if($timeperiod){
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime($start))
                ->setParameter('end', new \DateTime($end))
            ;
        }

        return $query;
    }

    public function getDashboardSessionSale($username, $sortby, $orderby, $offset, $limit, $users,$timeperiod = null){

        $dateLimit = '';
        if($timeperiod){

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }

        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('u.companyName, count(pkg.id) as total_available, pkg.createdDate, u.username, ptype.name')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('u.id in (:users) ')
            ->setParameter('code', 'Session')
            ->setParameter('users', $users)

            ->groupBy('pkg.createdDate')
            ->orderBy($sortby, $orderby);

/*
        $query = $em->createQueryBuilder()
            ->select('Sum (mp.id) AS total_available, mp.createdDate, u.username,ptype.name')
            ->from("CoredirectionBundle:MemberPackage", 'mp')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.id = mp.package')
            ->leftJoin('ApplicationSonataUserBundle:User', 'u', 'WITH', 'u.id = pkg.facility')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->where('ptype.code  =  :code ')
            ->andWhere('pkg.facility in (:users) ')
            ->setParameter('code', 'Session')
            ->setParameter('users', $users)
            //->select('u.companyName, count(pkg.id) as total_available')
            ->groupBy('mp.createdDate')
            //->orderBy($sortby, $orderby)
        ;
*/


        if($limit){
            $query->setFirstResult($offset)
                ->setMaxResults($limit);
        }

        if ($username) {
            $query->
            andWhere('u.companyName  =  :companyName ')
                ->setParameter('companyName', $username);
        }

        if($timeperiod){
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime($start))
                ->setParameter('end', new \DateTime($end))
            ;
        }

//        echo $query->getQuery()->getSQL();
//        exit;

        return $query;
    }

    public function getDashboardSessionSaleSoldout($username, $sortby, $orderby, $offset, $limit, $users, $timeperiod){

        $dateLimit = '';
        if($timeperiod){

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }

        $em = $this->getEntityManager();
/*
        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')
            ->andWhere('ptype.code  =  :code ')

            ->andWhere('u.id in (:users) ')
            //->andWhere('pkg.isCorepass  =  0 ')
            ->setParameter('code', 'Session')
            ->setParameter('users', $users)
            ->select('u.companyName, count(pkg.id) as total_available, count(mpkg.id) as total_sold, sum(mbd.amount) as total_amt')
            ->groupBy('u.id')
            ->orderBy($sortby, $orderby);
        */
        $query = $em->createQueryBuilder()
            ->select('Sum (mp.id) AS total_sold, mp.createdDate, u.username,ptype.name')
            ->from("CoredirectionBundle:MemberPackage", 'mp')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.id = mp.package')
            ->leftJoin('ApplicationSonataUserBundle:User', 'u', 'WITH', 'u.id = pkg.facility')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->where('ptype.code  =  :code ')
            ->andWhere('pkg.facility in (:users) ')
            ->setParameter('code', 'Session')
            ->setParameter('users', $users)
            //->select('u.companyName, count(pkg.id) as total_available')
            ->groupBy('mp.createdDate')
            //->orderBy($sortby, $orderby)
        ;
        if($limit){
            $query->setFirstResult($offset)
                ->setMaxResults($limit);
        }

        if ($username) {
            $query->
            andWhere('u.companyName  =  :companyName ')
                ->setParameter('companyName', $username);
        }

        if($timeperiod){
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime($start))
                ->setParameter('end', new \DateTime($end))
            ;
        }



        return $query;

    }

    public function getDashboardMembershipSale($username, $sortby, $orderby, $offset, $limit, $users,$timeperiod = null){

        $dateLimit = '';
        if($timeperiod){

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }

        $em = $this->getEntityManager();
/*
        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('u.id in (:users) ')
            ->setParameter('code', 'Membership')
            ->setParameter('users', $users)
            ->select('u.companyName, count(pkg.id) as total_available')
            ->groupBy('u.id')
            ->orderBy($sortby, $orderby);
*/
        $query = $em->createQueryBuilder()
            ->select('u.companyName, count(pkg.id) as total_available, pkg.createdDate, u.username, ptype.name')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->andWhere('ptype.code  =  :code ')
            ->andWhere('u.id in (:users) ')
            ->setParameter('code', 'Membership')
            ->setParameter('users', $users)

            ->groupBy('pkg.createdDate')
            ->orderBy($sortby, $orderby);

        if($limit){
            $query->setFirstResult($offset)
                ->setMaxResults($limit);
        }

        if ($username) {
            $query->
            andWhere('u.companyName  =  :companyName ')
                ->setParameter('companyName', $username);
        }

        if($timeperiod){
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime($start))
                ->setParameter('end', new \DateTime($end))
            ;
        }



        return $query;
    }

    public function getDashboardMembershipSaleSoldout($username, $sortby, $orderby, $offset, $limit, $users, $timeperiod){

        $dateLimit = '';
        if($timeperiod){

            if ($timeperiod == "1") {
                $start = date('Y-m-d', strtotime('Monday last week'));
                $end = date('Y-m-d', strtotime('Sunday last week'));
                $created_at = "DATE_FORMAT(created_at,'%W') as created_at";

            } elseif ($timeperiod == "2") {
                $last_month = date('m', strtotime('last month'));
                $last_year_month = date('Y-m', strtotime('last month'));
                $end_months = array('01', '03', '05', '07', '08', '10', '12');
                if (in_array($last_month, $end_months)) {
                    $month_end = '31';
                } else {
                    $month_end = '30';
                }

                $start = $last_year_month . '-01';
                $end = $last_year_month . '-' . $month_end;
                //$created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";

            } else {

                $interval = $timeperiod;
                $end = date('Y-m-d');
                $start = date('Y-m-d', strtotime("-" . $interval . " month"));

                $created_at = "DATE_FORMAT(created_at,'%Y-%b') as created_at";
                //$groupby = "DATE_FORMAT(u.created_at,'%Y %M')";
                //$orderby = "DATE_FORMAT(u.created_at,'%Y %m') ASC";
            }
            //$dateLimit = " AND DATE_FORMAT(D.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end'";
        }

        $em = $this->getEntityManager();
    /*
        $query = $em->createQueryBuilder()
            ->select('u')
            ->from("ApplicationSonataUserBundle:User", 'u')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.facility = u.id')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->leftJoin('CoredirectionBundle:MemberPackage', 'mpkg', 'WITH', 'mpkg.package = pkg.id')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity', 'msa', 'WITH', 'msa.package = mpkg.package')
            ->leftJoin('CoredirectionBundle:MemberBillingDetail', 'mbd', 'WITH', 'mbd.memberPackage = mpkg.id')
            ->andWhere('ptype.code  =  :code ')

            ->andWhere('u.id in (:users) ')
            //->andWhere('pkg.isCorepass  =  0 ')
            ->setParameter('code', 'Session')
            ->setParameter('users', $users)
            ->select('u.companyName, count(pkg.id) as total_available, count(mpkg.id) as total_sold, sum(mbd.amount) as total_amt')
            ->groupBy('u.id')
            ->orderBy($sortby, $orderby);
        */
        $query = $em->createQueryBuilder()
            ->select('Sum (mp.id) AS total_sold, mp.createdDate, u.username,ptype.name')
            ->from("CoredirectionBundle:MemberPackage", 'mp')
            ->leftJoin('CoredirectionBundle:Package', 'pkg', 'WITH', 'pkg.id = mp.package')
            ->leftJoin('ApplicationSonataUserBundle:User', 'u', 'WITH', 'u.id = pkg.facility')
            ->leftJoin('CoredirectionBundle:PackageType', 'ptype', 'WITH', 'ptype.id = pkg.packageType')
            ->where('ptype.code  =  :code ')
            ->andWhere('pkg.facility in (:users) ')
            ->setParameter('code', 'Session')
            ->setParameter('users', $users)
            //->select('u.companyName, count(pkg.id) as total_available')
            ->groupBy('mp.createdDate')
            //->orderBy($sortby, $orderby)
        ;
        if($limit){
            $query->setFirstResult($offset)
                ->setMaxResults($limit);
        }

        if ($username) {
            $query->
            andWhere('u.companyName  =  :companyName ')
                ->setParameter('companyName', $username);
        }

        if($timeperiod){
            $query->andWhere('u.createdAt  BETWEEN :start AND :end')
                ->setParameter('start', new \DateTime($start))
                ->setParameter('end', new \DateTime($end))
            ;
        }



        return $query;

    }

}
