<?php

namespace App\Repository;

/**
 * MemberPromotionClicksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberPromotionClicksRepository extends \Doctrine\ORM\EntityRepository
{
}
