<?php

namespace App\Repository;

/**
 * MemberScheduleTimelogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberScheduleTimelogRepository extends BaseRepository
{
    public function isUserCheckIn($msaId, $date )
    {

        

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('count(msa.id)')
            ->from('CoredirectionBundle:MemberScheduleTimelog', 'mstl')
            ->leftJoin('CoredirectionBundle:MemberScheduleActivity ', 'msa', 'WITH', 'mstl.book = msa.id')
            ->where('msa.id = :id')
            ->andWhere('Date(mstl.checkInTime) = :date')
            ->setParameter('id', $msaId)
            ->setParameter('date', $date);

        $total =  $query->getQuery()->getSingleScalarResult();
        if($total > 0){
            return true;
        }else{
            return false;
        }

    }

}
