<?php

namespace App\Repository;

/**
 * MemberArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
