<?php

namespace App\Repository;

/**
 * PackageTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageTypeRepository extends BaseRepository
{
}
