<?php

namespace App\Repository;

use App\Entity\ProfileKeyArticles;

/**
 * ProfileKeyArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileKeyArticlesRepository extends BaseRepository
{
    public function removeProfileKeyArticles($edit_profile_id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('pa')
            ->delete('CoredirectionBundle:ProfileKeyArticles', 'pa')
            ->where("pa.profileKeyId =  ( :profile_key_id )")
            ->setParameter("profile_key_id", $edit_profile_id);

        $results = $query->getQuery()->getResult();
        return $results;
    }

    public function addProfileKeyArticles($profile_articles, $edit_profile_id, $loginedUserId)
    {
        $em = $this->getEntityManager();
        $saved_key = $em->getRepository("CoredirectionBundle:ProfileKey")->findOneBy(array('id' => $edit_profile_id));

        foreach($profile_articles as $article){

            $saved_article = $em->getRepository("CoredirectionBundle:Article")->findOneBy(array('id' => $article));
            $prof_articles = new ProfileKeyArticles();
            $prof_articles->setProfileKeyId($saved_key);
            $prof_articles->setArticleId($saved_article);
            $prof_articles->setIsDeleted(0);
            $prof_articles->setModifiedBy($loginedUserId);
            $em->persist($prof_articles);
        }
        $em->flush();
    }

    public function getProfileKeyArticles($profileKeyIds){


        $query = $this->createQueryBuilder('p')
        ->add('select', 'a.name,a.code, a.imageName')
        ->innerJoin('p.articleId', 'a')
        ->where('p.profileKeyId = :profilekey')
        ->andWhere('a.isDeleted = 0')
        ->setParameter('profilekey', $profileKeyIds)
        ;
        $results = $query->getQuery()->getResult();
        return $results;
    }
}
