<?php

namespace App\Repository;

/**
 * UserDocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDocumentsRepository extends BaseRepository
{

    public function approveUnapproveDocuments($approveIds,$unapproveIds){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        if(!empty($approveIds)) {
            $query->update("CoredirectionBundle:UserDocuments", "d")

                ->set('d.isVerified', 1)
                ->where('d.id IN ( :id ) ')
                ->setParameter('id', $approveIds)->getQuery()->execute();
        }

        if(!empty($unapproveIds)) {
            $query->update("CoredirectionBundle:UserDocuments", "d")

                ->set('d.isVerified', 0)
                ->where('d.id IN ( :id ) ')
                ->setParameter('id', $unapproveIds)->getQuery()->execute();
        }
    }
}
