<?php

namespace App\Repository;

/**
 * UserBankInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBankInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
