<?php

namespace App\Repository;

use App\Entity\WorkoutExercise;
use V1Bundle\Helper\APIHelper;

/**
 * WorkoutExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkoutExerciseRepository extends BaseRepository
{
    public function Workout_Selected_Exercises($workout_id, $userGroups = array(), $userId){


        $full_exercise_list = $this->getEntityManager('App\Entity\Exercise')
            ->getRepository('App\Entity\Exercise')->findBy(array('isDeleted' => 0));


        $full_model_list  = $this->getEntityManager('CoredirectionBundle:BaseLookup')
            ->getRepository('CoredirectionBundle:BaseLookup')
            ->getModelLookups($userGroups, $userId);




        $workout_exercises = $this->findBy(array('workout' => $workout_id, 'isDeleted' => 0),array('sequence' => 'ASC'));
        $output = "";

        $output .= $this->All_Exercises_List();

        if($workout_exercises){
            $sequence = 1;
            $output .= '<div id="sortable"><div class="row wrk_exerciseInput"></div>';
            foreach($workout_exercises as $exercise){
                $selected_exercise_modelId = '';
                $exercise_id = $exercise->getExercise()->getId();
                $exercise_code = $exercise->getExercise();
                $exercise_duration = $exercise->getDuration();
                $minutes = $seconds = 0;
                $explode_duration = explode(':',$exercise_duration);

                if(isset($explode_duration[0])){
                    $minutes = $explode_duration[0];
                }
                if(isset($explode_duration[1])){
                    $seconds = $explode_duration[1];
                }

                $output .= '<div class="row wrk_exerciseInput">
                            <div class="col-md-1">
                                <div class="form-group">
                                    <label class="col-md-12 control-label sequence" sequence="">'.$sequence.'</label>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Exercise</label>
                                    
                                    <div class="col-md-5" id="selected_model_list">
                                        <datalist  name="model_exercise[]" class="selects model-select" >';

                                            if($full_model_list){
                                                $selected_exercise_modelId = '';
                                                foreach($full_model_list as $mod_list){
//

                                                    $selected_models  = $this->getEntityManager('CoredirectionBundle:ExerciseLookup')
                                                        ->getRepository('CoredirectionBundle:ExerciseLookup')
                                                        ->findOneBy(array('exercise' => $exercise_id, 'baseLookup' => $mod_list->getId()));
                                                    if($selected_models){
                                                        $selected_model_id = $selected_models->getBaseLookup()->getId();
                                                    }else{
                                                        $selected_model_id = '';
                                                    }


                                                    if(trim($mod_list->getId()) == trim($selected_model_id)){
                                                        $selected_exercise_modelId = $mod_list->getId();
                                                        $output .= '<option selected="selected" value="'.$mod_list->getId().'">'.$mod_list->getName().'</option>';
                                                    }else{

                                                        $output .= '<option value="'.$mod_list->getId().'">'.$mod_list->getName().'</option>';
                                                    }
                                                }
                                            }


                                $output.='</datalist>
                                                <span class="help-block " >Select model</span>
                                    </div>
                                    
                                    
                                        <div class="col-md-4" id="selected_exercises_lists">
                                            <datalist name="workout_exercise[]" class="selects uexercise_list">';
                                                //$selected_exercise_modelId
                                            $full_exercise_list = $this->getFullExerciseListByModelId($selected_exercise_modelId);
                                            if($full_exercise_list){
                                                foreach($full_exercise_list as $exe_list){

                                                    if(trim($exe_list->getCode()) == trim($exercise_code)){
                                                        $output .= '<option selected="selected" value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
                                                    }else{
                                                        $output .= '<option value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
                                                    }
                                                }
                                            }
                                    $output .=   '</datalist>
                                                  <span class="help-block " >Select exercise</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">Duration</label>';

                                    $output .= '<div class="col-md-4" id="minutes_list">
                                                <datalist name="duration_minutes[]" class="form-control selects" data-live-search="true">';
                                                    for($i=0; $i<=120; $i++) {
                                                        if($minutes == $i){
                                                            $selected = 'selected="selected"';
                                                        }else{
                                                            $selected = '';
                                                        }
                                                        $output .= '<option '.$selected.' value="'.$i.'">'.$i.'</option>';
                                                    }
                                    $output .= '</datalist>
                                                <span class="help-block">Enter minute</span>
                                            </div>
                                            <div class="col-md-4" id="seconds_list">
                                                <datalist name="duration_seconds[]" class="form-control selects" data-live-search="true">';

                                                    for($i=0; $i<=59; $i++){
                                                        if($seconds == $i){
                                                            $selected = 'selected="selected"';
                                                        }else{
                                                            $selected = '';
                                                        }
                                                        $output .= '<option '.$selected.' value="'.$i.'">'.$i.'</option>';
                                                    }

                                    $output .=  '</datalist>
                                                <span class="help-block">Enter second</span>
                                            </div>
                                        </div>
                                    </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <button class="btn btn-primary col-md-3 control-label btnDel wrk_exerciseInput_del" INPUT_CLASS="wrk_exerciseInput">X</button>
                                    </div>
                                </div>
                        </div>';
                $sequence++;
            }
            $output .= '</div>';
        }else{
            $output .= '<div id="sortable"><div class="row wrk_exerciseInput"></div></div>';
        }

        return $output;
    }

    public function All_Exercises_List(){
        $exercise_list = '';
        $full_exercise_list = $this->getEntityManager('App\Entity\Exercise')
            ->getRepository('App\Entity\Exercise')->findBy(array('isDeleted' => 0));






        if($full_exercise_list) {
            $exercise_list .= '<div id="all_exercises_list" style="display: none;">';

            foreach($full_exercise_list as $exe_list){
                $exercise_list .= '<option  value="'.$exe_list->getId().'">'.$exe_list->getName().'</option>';
            }
            $exercise_list .= '</div>';
        }
        return $exercise_list;
    }


    public function removeWorkoutExerciseData($workoutId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->delete('CoredirectionBundle:WorkoutExercise', 'el')
            ->where("el.workout =  ( :workout_id )")
            ->setParameter("workout_id", $workoutId);

        $results = $query->getQuery()->getResult();
        return $results;
    }

    public function saveWorkoutExercises($workoutId, $formData, $loginedUserId)
    {
        $exercise_ids = $minutes = $seconds = array();
        $em = $this->getEntityManager();


        if(isset($formData['workout_exercise'])){
            $exercises = $formData['workout_exercise'];
            foreach($exercises as $exercise){
                $exercise_ids[] = $exercise ;
            }
        }

//        $exercise_ids = array_unique(array_filter($exercise_ids));
        $exercise_ids = array_filter($exercise_ids);
        if(isset($formData['duration_minutes'])){
            $duration_minutes = $formData['duration_minutes'];
            foreach($duration_minutes as $minute){
                $minutes[] = $minute ;
            }
        }

        if(isset($formData['duration_seconds'])){
            $duration_seconds = $formData['duration_seconds'];
            foreach($duration_seconds as $second){
                $seconds[] = $second ;
            }
        }


        $workout_exercise_list = $em->getRepository('CoredirectionBundle:WorkoutExercise')
            ->findBy(array('workout' => $workoutId));

        $exercise_list = array();
        if(!empty($workout_exercise_list)) {
            foreach ($workout_exercise_list as $wrk_exe_list) {
                $exercise_list[$wrk_exe_list->getId()] = $wrk_exe_list->getExercise()->getId();
            }
        }


        if(!empty($exercise_ids)){

            if(!empty($exercise_list)) {
//                $del_wrk_exe = array_diff($exercise_list, $exercise_ids);
//                $this->deleteWorkoutExerciseByWorkAndExerciseId($workoutId, $exercise_ids);
                $this->deleteExercisesByWorkout($workoutId);
            }

//            dump($exercise_ids,$minutes,$seconds);die;
            $workout = $em->getReference('App\Entity\Workout', $workoutId);
            $sequence_order = 1;
            foreach($exercise_ids as $key => $exercise_id){
                $workout_exercise = new WorkoutExercise();

                $duration = '';
                if(isset($minutes[$key])){
                    $duration .= $minutes[$key];
                }
                if(isset($seconds[$key])){
                    $duration .= ":".$seconds[$key];
                }

                $exercise = $em->getReference('App\Entity\Exercise', $exercise_id);


                $workoutExercise = $em->getRepository('CoredirectionBundle:WorkoutExercise')
                    ->findOneBy(array('exercise' => $exercise->getId(), 'workout' => $workoutId));

                if($workoutExercise){ //update it

                    $workoutExercise->setModifiedBy($loginedUserId);
                    $workoutExercise->setUpdatedDate(new \DateTime());
                    $workoutExercise->setSequence($sequence_order);
                    $workoutExercise->setDuration($duration);

                }else{ //  insert new one
                    $workout_exercise = new WorkoutExercise();
                    $workout_exercise->setWorkout($workout);
                    $workout_exercise->setExercise($exercise);
                    $workout_exercise->setModifiedBy($loginedUserId);
                    $workout_exercise->setCreatedDate(new \DateTime());
                    $workout_exercise->setUpdatedDate(new \DateTime());
                    $workout_exercise->setSequence($sequence_order);
                    $workout_exercise->setDuration($duration);

                    $em->persist($workout_exercise);
                }
                $sequence_order++;
            }
            $em->flush();
        }
    }

    public function getFullExerciseListByModelId( $lookupId ){

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('exe')
            ->from('CoredirectionBundle:Exercise','exe')
            ->innerJoin('CoredirectionBundle:ExerciseLookup','el' , 'WITH', 'el.exercise = exe.id ' )
            ->where('el.baseLookup =  :lookup')
            ->andWhere('exe.isDeleted =  0')
            ->setParameter('lookup', $lookupId)
            ;


        return $query->getQuery()->getResult();

    }

    public function deleteWorkoutExerciseByWorkAndExerciseId($workoutIds, $exerciseIds){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('el')
            ->delete('CoredirectionBundle:WorkoutExercise', 'el')
            ->where("el.workout =  ( :workout_id )")
            ->andWhere('el.exercise IN ( :exercise_ids )')
            ->setParameter("workout_id", $workoutIds)
            ->setParameter("exercise_ids", $exerciseIds)
        ;

        $results = $query->getQuery()->getResult();
        return $results;
    }


    /**
     * @param $workoutId
     * @return bool
     * @throws \Doctrine\DBAL\DBALException
     */
    public function deleteExercisesByWorkout($workoutId)
    {
        $params['workout_id'] = $workoutId;
        $em = $this->getEntityManager();
        $sql= "DELETE FROM `workout_exercise` WHERE `workout_exercise`.`workout_id` = :workout_id";
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return true;
    }

    public function getWorkoutExercises($workoutId)
    {

        $query = $this->createQueryBuilder('we')
            ->innerJoin('App\Entity\Workout', 'w','WITH','we.workout = w.id')
            ->select('we.duration')
            ->where('w.id = :workout_id')
            ->setParameter('workout_id',$workoutId);

        $results = $query->getQuery()->getResult();

        $time = 0 ;
        foreach ($results as $result){

            $time +=APIHelper::get()->getTimeInseconds($result['duration']);
        }
        return $time;
    }
}
