<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200116062915 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE fos_user_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', code VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_583D1F3E5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, date_of_birth DATETIME DEFAULT NULL, firstname VARCHAR(64) DEFAULT NULL, lastname VARCHAR(64) DEFAULT NULL, website VARCHAR(64) DEFAULT NULL, biography VARCHAR(1000) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, facebook_uid VARCHAR(255) DEFAULT NULL, facebook_name VARCHAR(255) DEFAULT NULL, facebook_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', twitter_uid VARCHAR(255) DEFAULT NULL, twitter_name VARCHAR(255) DEFAULT NULL, twitter_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', gplus_uid VARCHAR(255) DEFAULT NULL, gplus_name VARCHAR(255) DEFAULT NULL, gplus_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', token VARCHAR(255) DEFAULT NULL, two_step_code VARCHAR(255) DEFAULT NULL, address VARCHAR(100) DEFAULT NULL, is_gdpr TINYINT(1) DEFAULT NULL, address_one VARCHAR(100) DEFAULT NULL, address_two VARCHAR(100) DEFAULT NULL, po_box VARCHAR(50) DEFAULT NULL, city VARCHAR(50) DEFAULT NULL, country VARCHAR(50) DEFAULT NULL, contact_title VARCHAR(100) DEFAULT NULL, contact_firstname VARCHAR(50) DEFAULT NULL, contact_lastname VARCHAR(50) DEFAULT NULL, designation VARCHAR(50) DEFAULT NULL, contact_email VARCHAR(50) DEFAULT NULL, contact_no VARCHAR(100) DEFAULT NULL, contact_url VARCHAR(100) DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, company_logo VARCHAR(255) DEFAULT NULL, company_name VARCHAR(100) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, card_id VARCHAR(100) DEFAULT NULL, notification TINYINT(1) DEFAULT NULL, enable_discount TINYINT(1) DEFAULT NULL, step_count INT DEFAULT NULL, distance DOUBLE PRECISION DEFAULT NULL, step_date_time DATETIME DEFAULT NULL, last_reward_steps INT DEFAULT NULL, appVersion_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_C560D76192FC23A8 (username_canonical), UNIQUE INDEX UNIQ_C560D761A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_C560D761C05FB297 (confirmation_token), INDEX IDX_C560D761727ACA70 (parent_id), INDEX IDX_C560D761E112DAFD (appVersion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_B3C77447A76ED395 (user_id), INDEX IDX_B3C77447FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_challenge_invite (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, challenge_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, status enum( \'Pending\', \'Confirmed\',\'Reject\'), INDEX IDX_4B8C0F07597D3FE (member_id), INDEX IDX_4B8C0F098A21AC6 (challenge_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gmf_actions (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(25) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, point INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_action_point (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, action_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, action_date DATE NOT NULL, INDEX IDX_25D8A1107597D3FE (member_id), INDEX IDX_25D8A1109D32F035 (action_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE challenge_action (id INT AUTO_INCREMENT NOT NULL, challenge_id INT DEFAULT NULL, member_action_points_id INT DEFAULT NULL, INDEX IDX_B4712F5398A21AC6 (challenge_id), INDEX IDX_B4712F534B8837D4 (member_action_points_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE challenge (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, title VARCHAR(255) NOT NULL, logo_name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, code VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_D709895177153098 (code), INDEX IDX_D7098951979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE workout_level (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, point INT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exercise_lookup (id INT AUTO_INCREMENT NOT NULL, exercise_id INT DEFAULT NULL, lookup_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_8553246EE934951A (exercise_id), INDEX IDX_8553246E8955C49D (lookup_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_billing_detail (id INT AUTO_INCREMENT NOT NULL, member_billing_id INT DEFAULT NULL, member_package_id INT DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, amount NUMERIC(10, 2) NOT NULL, INDEX IDX_8F318570D04C426E (member_billing_id), INDEX IDX_8F3185701F02B516 (member_package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity_schedule (id INT AUTO_INCREMENT NOT NULL, instructor_id INT DEFAULT NULL, activity_id INT DEFAULT NULL, facility_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, pinaddress VARCHAR(255) DEFAULT NULL, startDate DATETIME NOT NULL, endDate DATETIME NOT NULL, duration SMALLINT NOT NULL, recurrence VARCHAR(255) NOT NULL, is_recommended TINYINT(1) DEFAULT \'1\' NOT NULL, session_type enum(\'Morning\', \'Evening\', \'Afternoon\'), slots INT DEFAULT NULL, is_location TINYINT(1) DEFAULT \'0\' NOT NULL, latitude VARCHAR(100) DEFAULT NULL, longitude VARCHAR(100) DEFAULT NULL, allow_corepass TINYINT(1) DEFAULT \'0\' NOT NULL, is_free TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_FA32A1F58C4FC193 (instructor_id), INDEX IDX_FA32A1F581C06096 (activity_id), INDEX IDX_FA32A1F5A7014910 (facility_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity_schedule_package (activityschedule_id INT NOT NULL, package_id INT NOT NULL, INDEX IDX_B741AA4692A20CA5 (activityschedule_id), INDEX IDX_B741AA46F44CABFF (package_id), PRIMARY KEY(activityschedule_id, package_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profile_key_articles (id INT AUTO_INCREMENT NOT NULL, profile_key_id INT DEFAULT NULL, article_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_C976BB9A653E3254 (profile_key_id), INDEX IDX_C976BB9A7294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_key (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, key_id INT DEFAULT NULL, created DATETIME NOT NULL, INDEX IDX_BB348BF27597D3FE (member_id), INDEX IDX_BB348BF2D145533 (key_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_package (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, package_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, status enum( \'active\', \'cancel\', \'expired\'), checkin INT DEFAULT 0 NOT NULL, card_id VARCHAR(100) DEFAULT NULL, is_promotion TINYINT(1) NOT NULL, INDEX IDX_619CD0017597D3FE (member_id), INDEX IDX_619CD001F44CABFF (package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE error_log (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, error_code VARCHAR(100) NOT NULL, error_message LONGTEXT NOT NULL, error_date DATETIME NOT NULL, method_name VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE workout (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, workout_type INT DEFAULT NULL, level_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, background_music VARCHAR(100) DEFAULT NULL, duration VARCHAR(255) DEFAULT NULL, point INT DEFAULT NULL, is_recommended TINYINT(1) DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, INDEX IDX_649FFB72A76ED395 (user_id), INDEX IDX_649FFB72F4505455 (workout_type), INDEX IDX_649FFB725FB14BA7 (level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE promotions (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, image VARCHAR(255) NOT NULL, ordering INT DEFAULT 0 NOT NULL, promotionType VARCHAR(255) NOT NULL, activitySchedule_id INT DEFAULT NULL, INDEX IDX_EA1B3034143E8372 (activitySchedule_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE corporate_member_email (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, corporate_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, templateNo INT NOT NULL, actionDate DATETIME NOT NULL, status enum( \'pending\', \'sent\',\'failed\'), INDEX IDX_E3A97B9C7597D3FE (member_id), INDEX IDX_E3A97B9CCD147EEF (corporate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subscription_billing (id INT AUTO_INCREMENT NOT NULL, subscription_id INT DEFAULT NULL, charge_id VARCHAR(100) NOT NULL, track_id VARCHAR(100) NOT NULL, card_id VARCHAR(100) NOT NULL, amount NUMERIC(10, 2) NOT NULL, vat NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, transaction_response LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', last_four VARCHAR(255) NOT NULL, transaction_type enum(\'Payment\', \'Refund\', \'Cancellation\'), INDEX IDX_9F37AC319A1887DC (subscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE layout (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, bg_color VARCHAR(255) NOT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_3A3A6BE277153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, article_type_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, is_Recumended TINYINT(1) DEFAULT NULL, point INT DEFAULT NULL, tag LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, tags_ar LONGTEXT DEFAULT NULL, INDEX IDX_23A0E66A76ED395 (user_id), INDEX IDX_23A0E66289EC824 (article_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_filter (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, Member INT NOT NULL, screen VARCHAR(50) NOT NULL, filter JSON NOT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE corporate_department (id INT AUTO_INCREMENT NOT NULL, corporate_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(25) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, imageName VARCHAR(255) DEFAULT NULL, INDEX IDX_8AD59DBCD147EEF (corporate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sections (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, bg_image VARCHAR(255) DEFAULT NULL, bg_color VARCHAR(255) NOT NULL, type enum(\'list\', \'rect\', \'box\'), direction enum(\'horizontal\', \'vertical\'), section_order INT NOT NULL, text_color VARCHAR(255) NOT NULL, name_ar LONGTEXT DEFAULT NULL, cell_dimensions VARCHAR(255) DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_2B96439877153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exercise_image (id INT AUTO_INCREMENT NOT NULL, exercise_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL, sequence INT NOT NULL, INDEX IDX_E00BF39DE934951A (exercise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package (id INT AUTO_INCREMENT NOT NULL, package_type_id INT DEFAULT NULL, facility_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, expires_on DATETIME DEFAULT NULL, visits INT NOT NULL, public_rate NUMERIC(10, 2) NOT NULL, corporate_rate NUMERIC(10, 2) NOT NULL, discount NUMERIC(10, 2) DEFAULT NULL, validity_days SMALLINT DEFAULT 0 NOT NULL, repeat_monthly TINYINT(1) DEFAULT \'0\' NOT NULL, individual_rate_commission NUMERIC(10, 2) NOT NULL, corporate_rate_commission NUMERIC(10, 2) NOT NULL, is_corepass TINYINT(1) DEFAULT NULL, INDEX IDX_DE6867954A17E91F (package_type_id), INDEX IDX_DE686795A7014910 (facility_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE actions (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(25) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, point INT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, INDEX IDX_548F1EF727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_article (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, article_id INT NOT NULL, key_id INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_BDCEB9F2A76ED395 (user_id), INDEX IDX_BDCEB9F27294869C (article_id), INDEX IDX_BDCEB9F2D145533 (key_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facility_checkin_history (id INT AUTO_INCREMENT NOT NULL, facility_id INT DEFAULT NULL, member_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, checkin INT DEFAULT 0 NOT NULL, time DATETIME NOT NULL, INDEX IDX_612FB270A7014910 (facility_id), INDEX IDX_612FB2707597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_schedule_timelog (id INT AUTO_INCREMENT NOT NULL, book_id INT NOT NULL, checkInTime DATETIME NOT NULL, INDEX IDX_A192F9916A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE amenity (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invitation_template (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, title VARCHAR(255) NOT NULL, template LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE workout_exercise (id INT AUTO_INCREMENT NOT NULL, workout_id INT DEFAULT NULL, exercise_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, sequence INT DEFAULT NULL, duration VARCHAR(255) DEFAULT NULL, INDEX IDX_76AB38AAA6CCCFC9 (workout_id), INDEX IDX_76AB38AAE934951A (exercise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facility_activity (id INT AUTO_INCREMENT NOT NULL, facility_id INT DEFAULT NULL, activity_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, is_recommended TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_FA77B0D5A7014910 (facility_id), INDEX IDX_FA77B0D581C06096 (activity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_schedule_activity (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, schedule_detail_id INT DEFAULT NULL, package_id INT NOT NULL, member_package_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, checkin INT NOT NULL, is_favourite TINYINT(1) NOT NULL, status enum( \'booked\', \'favourite\', \'cancelled\', \'expired\',\'reserved\'), INDEX IDX_59C640527597D3FE (member_id), INDEX IDX_59C6405217D67DCB (schedule_detail_id), INDEX IDX_59C64052F44CABFF (package_id), INDEX IDX_59C640521F02B516 (member_package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_workout (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, workout_id INT DEFAULT NULL, key_id INT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, is_favourite TINYINT(1) DEFAULT NULL, is_history TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_DB6B4CE67597D3FE (member_id), INDEX IDX_DB6B4CE6A6CCCFC9 (workout_id), INDEX IDX_DB6B4CE6D145533 (key_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE layout_sections (id INT AUTO_INCREMENT NOT NULL, layout_id INT NOT NULL, section_id INT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, sequence INT DEFAULT NULL, INDEX IDX_35E5CDAF8C22AA1A (layout_id), INDEX IDX_35E5CDAFD823E37A (section_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_version (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, device_type enum( \'iphone\', \'android\'), version VARCHAR(255) NOT NULL, status TINYINT(1) NOT NULL, current_release TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_promotion_clicks (id INT AUTO_INCREMENT NOT NULL, member_id INT NOT NULL, promotion_id INT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, clicks BIGINT DEFAULT 0 NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_58741DA7597D3FE (member_id), INDEX IDX_58741DA139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE workout_type (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, sequence INT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE base_lookup (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(60) NOT NULL, name VARCHAR(60) NOT NULL, description VARCHAR(100) NOT NULL, INDEX IDX_987C296C727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subscription (id INT AUTO_INCREMENT NOT NULL, key_id INT DEFAULT NULL, firstName VARCHAR(255) NOT NULL, lastName VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, product_id INT DEFAULT NULL, product_type enum( \'package\', \'challenge\'), INDEX IDX_A3C664D3D145533 (key_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_bank_info (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, account_title VARCHAR(100) DEFAULT NULL, bank_name VARCHAR(100) DEFAULT NULL, iban VARCHAR(255) DEFAULT NULL, branch VARCHAR(100) DEFAULT NULL, account_no LONGTEXT DEFAULT NULL, branch_code SMALLINT DEFAULT NULL, swift_code VARCHAR(255) DEFAULT NULL, bank_address VARCHAR(255) DEFAULT NULL, secret_key VARCHAR(100) DEFAULT NULL, publish_key VARCHAR(100) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, currency_code enum(\'AED\', \'GBP\', \'USD\'), country_code VARCHAR(2) DEFAULT NULL, INDEX IDX_6109EE3DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_documents (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, documentName VARCHAR(255) NOT NULL, is_verified TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_A250FF6CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_device_token (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, api_key_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, device_type VARCHAR(10) NOT NULL, device_token LONGTEXT DEFAULT NULL, is_login TINYINT(1) NOT NULL, build VARCHAR(100) DEFAULT NULL, version VARCHAR(100) DEFAULT NULL, identifier_key VARCHAR(255) DEFAULT NULL, INDEX IDX_EC01DFD4A76ED395 (user_id), INDEX IDX_EC01DFD48BE312B3 (api_key_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE configurations (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, key_name VARCHAR(255) NOT NULL, value_data LONGTEXT NOT NULL, is_active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package_type (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facility_amenity (id INT AUTO_INCREMENT NOT NULL, facility_id INT DEFAULT NULL, amenity_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_1B1DD556A7014910 (facility_id), INDEX IDX_1B1DD5569F9F1305 (amenity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_billing (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, charge_id VARCHAR(100) NOT NULL, track_id VARCHAR(100) NOT NULL, card_id VARCHAR(100) NOT NULL, last_four VARCHAR(4) NOT NULL, amount NUMERIC(10, 2) NOT NULL, vat NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, transaction_response LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', transaction_type enum(\'Payment\', \'Refund\', \'Cancellation\'), INDEX IDX_53D6FB3EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exercise (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, video_name VARCHAR(255) DEFAULT NULL, video_type enum(\'url\', \'file\'), point INT DEFAULT NULL, time INT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, INDEX IDX_AEDAD51CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE manual_checkin_history (id INT AUTO_INCREMENT NOT NULL, activity_id INT DEFAULT NULL, member_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, time DATETIME NOT NULL, INDEX IDX_600F004A81C06096 (activity_id), INDEX IDX_600F004A7597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_measurement (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, point INT NOT NULL, weight NUMERIC(10, 2) NOT NULL, height NUMERIC(10, 2) NOT NULL, waist NUMERIC(10, 2) NOT NULL, thighs NUMERIC(10, 2) DEFAULT NULL, hips NUMERIC(10, 2) NOT NULL, chest NUMERIC(10, 2) DEFAULT NULL, isCurrent TINYINT(1) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, wrist NUMERIC(10, 2) DEFAULT NULL, forearm NUMERIC(10, 2) DEFAULT NULL, INDEX IDX_F5DDCCD37597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE device_config (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, config LONGTEXT NOT NULL, lang  enum(\'en\',\'ar\',\'de\') , created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_79A5E67A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_type (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, tags LONGTEXT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, tags_ar LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity_type (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, imageName VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE corporate_key (id INT AUTO_INCREMENT NOT NULL, corporate_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, company_key VARCHAR(25) NOT NULL, validate_date DATETIME NOT NULL, type enum(\'Discount\', \'Package\', \'CorePass\', \'Profile\', \'Default\',\'Referral\'), start_date DATETIME NOT NULL, is_active TINYINT(1) DEFAULT \'1\', INDEX IDX_D13C28ADCD147EEF (corporate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE corporate_key_package (corporatekey_id INT NOT NULL, package_id INT NOT NULL, INDEX IDX_A017927197F1F59D (corporatekey_id), INDEX IDX_A0179271F44CABFF (package_id), PRIMARY KEY(corporatekey_id, package_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE key_profile_group (corporatekey_id INT NOT NULL, profilekey_id INT NOT NULL, INDEX IDX_D849CD0597F1F59D (corporatekey_id), INDEX IDX_D849CD0570F8267D (profilekey_id), PRIMARY KEY(corporatekey_id, profilekey_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE schedule_detail (id INT AUTO_INCREMENT NOT NULL, schedule_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, schedule_date DATETIME NOT NULL, duration SMALLINT NOT NULL, recurrence enum(\'Monday\', \'Tuesday\', \'Wednesday\', \'Thursday\', \'Friday\', \'Saturday\', \'Sunday\'), session_type enum(\'Morning\', \'Evening\', \'Afternoon\'), slots INT DEFAULT NULL, is_cancel TINYINT(1) DEFAULT \'0\' NOT NULL, latitude VARCHAR(100) DEFAULT NULL, longitude VARCHAR(100) DEFAULT NULL, INDEX IDX_4C273B8CA40BC2D5 (schedule_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_setting_layout (id INT AUTO_INCREMENT NOT NULL, app_setting_id INT NOT NULL, layout_id INT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, sequence INT DEFAULT NULL, INDEX IDX_DF3C0021B82E160E (app_setting_id), INDEX IDX_DF3C00218C22AA1A (layout_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity (id INT AUTO_INCREMENT NOT NULL, activity_type_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, imageName VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_AC74095A77153098 (code), INDEX IDX_AC74095AC51EFA73 (activity_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profile_key (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT \'0\', expire_date DATETIME DEFAULT NULL, is_default TINYINT(1) DEFAULT \'0\', UNIQUE INDEX UNIQ_2432029677153098 (code), INDEX IDX_24320296979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profile_key_workouts (id INT AUTO_INCREMENT NOT NULL, profile_key_id INT DEFAULT NULL, workout_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_D3CACA12653E3254 (profile_key_id), INDEX IDX_D3CACA12A6CCCFC9 (workout_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_setting (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, description LONGTEXT DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, loader_image VARCHAR(255) DEFAULT NULL, build VARCHAR(255) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, lang_list TINYTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', base_url VARCHAR(255) DEFAULT NULL, name_ar LONGTEXT DEFAULT NULL, description_ar LONGTEXT DEFAULT NULL, authentication VARCHAR(100) DEFAULT NULL, gamify_enabled TINYINT(1) DEFAULT \'0\' NOT NULL, published TINYINT(1) DEFAULT \'0\' NOT NULL, gamify_base_url VARCHAR(100) DEFAULT NULL, gamify_app_key VARCHAR(255) DEFAULT NULL, url VARCHAR(100) DEFAULT NULL, enable TINYINT(1) DEFAULT \'0\' NOT NULL, error_log_enabled TINYINT(1) DEFAULT \'0\' NOT NULL, font VARCHAR(100) DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, txt_unhl VARCHAR(100) DEFAULT NULL, txt_hl VARCHAR(100) DEFAULT NULL, bg_unhl VARCHAR(100) DEFAULT NULL, bg_hl VARCHAR(100) DEFAULT NULL, sec_title_txt_unhl VARCHAR(100) DEFAULT NULL, sec_title_txt_hl VARCHAR(100) DEFAULT NULL, sec_bg_unhl VARCHAR(100) DEFAULT NULL, sec_bg_hl VARCHAR(100) DEFAULT NULL, device_type enum(\'android\',\'ios\'), company_name VARCHAR(100) NOT NULL, postfix VARCHAR(100) DEFAULT NULL, main_authentication VARCHAR(100) DEFAULT NULL, app_icon VARCHAR(255) DEFAULT NULL, privacy_policy VARCHAR(100) DEFAULT NULL, agreement_content VARCHAR(100) DEFAULT NULL, push_notification_enable TINYINT(1) DEFAULT \'0\' NOT NULL, messaging_enable TINYINT(1) DEFAULT \'0\' NOT NULL, messaging_base_url VARCHAR(100) DEFAULT NULL, messaging_postfix VARCHAR(100) DEFAULT NULL, messaging_authentication VARCHAR(100) DEFAULT NULL, UNIQUE INDEX UNIQ_722938D577153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE api_key (id INT AUTO_INCREMENT NOT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, api_key VARCHAR(50) NOT NULL, api_password VARCHAR(50) NOT NULL, is_active TINYINT(1) DEFAULT \'1\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facility_package (id INT AUTO_INCREMENT NOT NULL, facility_id INT DEFAULT NULL, package_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, INDEX IDX_6E15CBA0A7014910 (facility_id), INDEX IDX_6E15CBA0F44CABFF (package_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facility_gallery (id INT AUTO_INCREMENT NOT NULL, facility_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, image_name VARCHAR(255) DEFAULT NULL, sequence INT DEFAULT NULL, INDEX IDX_F756D40FA7014910 (facility_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_invitation (id INT AUTO_INCREMENT NOT NULL, corporate_key_id INT DEFAULT NULL, invitation_template_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, email VARCHAR(255) NOT NULL, sent_at DATETIME DEFAULT NULL, invitation_status enum(\'enqueue\',\'pending\',\'confirmed\'), INDEX IDX_1A537F4BC5D3D9FF (corporate_key_id), INDEX IDX_1A537F4BD2D03B8 (invitation_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_action (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, action_id INT DEFAULT NULL, is_deleted TINYINT(1) DEFAULT NULL, modifiedby INT NOT NULL, created_date DATETIME NOT NULL, updated_date DATETIME NOT NULL, isCompleted TINYINT(1) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, INDEX IDX_631A0EA17597D3FE (member_id), INDEX IDX_631A0EA19D32F035 (action_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_classes (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_type VARCHAR(200) NOT NULL, UNIQUE INDEX UNIQ_69DD750638A36066 (class_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_security_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, identifier VARCHAR(200) NOT NULL, username TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 (identifier, username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_object_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, parent_object_identity_id INT UNSIGNED DEFAULT NULL, class_id INT UNSIGNED NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 (object_identifier, class_id), INDEX IDX_9407E54977FA751A (parent_object_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INT UNSIGNED NOT NULL, ancestor_id INT UNSIGNED NOT NULL, INDEX IDX_825DE2993D9AB4A6 (object_identity_id), INDEX IDX_825DE299C671CEA1 (ancestor_id), PRIMARY KEY(object_identity_id, ancestor_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE acl_entries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_id INT UNSIGNED NOT NULL, object_identity_id INT UNSIGNED DEFAULT NULL, security_identity_id INT UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT UNSIGNED NOT NULL, mask INT NOT NULL, granting TINYINT(1) NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success TINYINT(1) NOT NULL, audit_failure TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 (class_id, object_identity_id, field_name, ace_order), INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 (class_id, object_identity_id, security_identity_id), INDEX IDX_46C8B806EA000B10 (class_id), INDEX IDX_46C8B8063D9AB4A6 (object_identity_id), INDEX IDX_46C8B806DF9183C9 (security_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761727ACA70 FOREIGN KEY (parent_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE fos_user_user ADD CONSTRAINT FK_C560D761E112DAFD FOREIGN KEY (appVersion_id) REFERENCES app_version (id)');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES fos_user_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_challenge_invite ADD CONSTRAINT FK_4B8C0F07597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_challenge_invite ADD CONSTRAINT FK_4B8C0F098A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id)');
        $this->addSql('ALTER TABLE member_action_point ADD CONSTRAINT FK_25D8A1107597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_action_point ADD CONSTRAINT FK_25D8A1109D32F035 FOREIGN KEY (action_id) REFERENCES gmf_actions (id)');
        $this->addSql('ALTER TABLE challenge_action ADD CONSTRAINT FK_B4712F5398A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id)');
        $this->addSql('ALTER TABLE challenge_action ADD CONSTRAINT FK_B4712F534B8837D4 FOREIGN KEY (member_action_points_id) REFERENCES member_action_point (id)');
        $this->addSql('ALTER TABLE challenge ADD CONSTRAINT FK_D7098951979B1AD6 FOREIGN KEY (company_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE exercise_lookup ADD CONSTRAINT FK_8553246EE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE exercise_lookup ADD CONSTRAINT FK_8553246E8955C49D FOREIGN KEY (lookup_id) REFERENCES base_lookup (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_billing_detail ADD CONSTRAINT FK_8F318570D04C426E FOREIGN KEY (member_billing_id) REFERENCES member_billing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_billing_detail ADD CONSTRAINT FK_8F3185701F02B516 FOREIGN KEY (member_package_id) REFERENCES member_package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity_schedule ADD CONSTRAINT FK_FA32A1F58C4FC193 FOREIGN KEY (instructor_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE activity_schedule ADD CONSTRAINT FK_FA32A1F581C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity_schedule ADD CONSTRAINT FK_FA32A1F5A7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE activity_schedule_package ADD CONSTRAINT FK_B741AA4692A20CA5 FOREIGN KEY (activityschedule_id) REFERENCES activity_schedule (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity_schedule_package ADD CONSTRAINT FK_B741AA46F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE profile_key_articles ADD CONSTRAINT FK_C976BB9A653E3254 FOREIGN KEY (profile_key_id) REFERENCES profile_key (id)');
        $this->addSql('ALTER TABLE profile_key_articles ADD CONSTRAINT FK_C976BB9A7294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE member_key ADD CONSTRAINT FK_BB348BF27597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_key ADD CONSTRAINT FK_BB348BF2D145533 FOREIGN KEY (key_id) REFERENCES corporate_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_package ADD CONSTRAINT FK_619CD0017597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_package ADD CONSTRAINT FK_619CD001F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB72A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB72F4505455 FOREIGN KEY (workout_type) REFERENCES workout_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workout ADD CONSTRAINT FK_649FFB725FB14BA7 FOREIGN KEY (level_id) REFERENCES workout_level (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotions ADD CONSTRAINT FK_EA1B3034143E8372 FOREIGN KEY (activitySchedule_id) REFERENCES activity_schedule (id)');
        $this->addSql('ALTER TABLE corporate_member_email ADD CONSTRAINT FK_E3A97B9C7597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE corporate_member_email ADD CONSTRAINT FK_E3A97B9CCD147EEF FOREIGN KEY (corporate_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE subscription_billing ADD CONSTRAINT FK_9F37AC319A1887DC FOREIGN KEY (subscription_id) REFERENCES subscription (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66289EC824 FOREIGN KEY (article_type_id) REFERENCES article_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE corporate_department ADD CONSTRAINT FK_8AD59DBCD147EEF FOREIGN KEY (corporate_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE exercise_image ADD CONSTRAINT FK_E00BF39DE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867954A17E91F FOREIGN KEY (package_type_id) REFERENCES package_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE686795A7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE actions ADD CONSTRAINT FK_548F1EF727ACA70 FOREIGN KEY (parent_id) REFERENCES actions (id)');
        $this->addSql('ALTER TABLE member_article ADD CONSTRAINT FK_BDCEB9F2A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_article ADD CONSTRAINT FK_BDCEB9F27294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_article ADD CONSTRAINT FK_BDCEB9F2D145533 FOREIGN KEY (key_id) REFERENCES corporate_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facility_checkin_history ADD CONSTRAINT FK_612FB270A7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE facility_checkin_history ADD CONSTRAINT FK_612FB2707597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_schedule_timelog ADD CONSTRAINT FK_A192F9916A2B381 FOREIGN KEY (book_id) REFERENCES member_schedule_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAA6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facility_activity ADD CONSTRAINT FK_FA77B0D5A7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE facility_activity ADD CONSTRAINT FK_FA77B0D581C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_schedule_activity ADD CONSTRAINT FK_59C640527597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_schedule_activity ADD CONSTRAINT FK_59C6405217D67DCB FOREIGN KEY (schedule_detail_id) REFERENCES schedule_detail (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_schedule_activity ADD CONSTRAINT FK_59C64052F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_schedule_activity ADD CONSTRAINT FK_59C640521F02B516 FOREIGN KEY (member_package_id) REFERENCES member_package (id)');
        $this->addSql('ALTER TABLE member_workout ADD CONSTRAINT FK_DB6B4CE67597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_workout ADD CONSTRAINT FK_DB6B4CE6A6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_workout ADD CONSTRAINT FK_DB6B4CE6D145533 FOREIGN KEY (key_id) REFERENCES corporate_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE layout_sections ADD CONSTRAINT FK_35E5CDAF8C22AA1A FOREIGN KEY (layout_id) REFERENCES layout (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE layout_sections ADD CONSTRAINT FK_35E5CDAFD823E37A FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_promotion_clicks ADD CONSTRAINT FK_58741DA7597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_promotion_clicks ADD CONSTRAINT FK_58741DA139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE base_lookup ADD CONSTRAINT FK_987C296C727ACA70 FOREIGN KEY (parent_id) REFERENCES base_lookup (id)');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3D145533 FOREIGN KEY (key_id) REFERENCES corporate_key (id)');
        $this->addSql('ALTER TABLE user_bank_info ADD CONSTRAINT FK_6109EE3DA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE user_documents ADD CONSTRAINT FK_A250FF6CA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_device_token ADD CONSTRAINT FK_EC01DFD4A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_device_token ADD CONSTRAINT FK_EC01DFD48BE312B3 FOREIGN KEY (api_key_id) REFERENCES api_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facility_amenity ADD CONSTRAINT FK_1B1DD556A7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE facility_amenity ADD CONSTRAINT FK_1B1DD5569F9F1305 FOREIGN KEY (amenity_id) REFERENCES amenity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_billing ADD CONSTRAINT FK_53D6FB3EA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51CA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE manual_checkin_history ADD CONSTRAINT FK_600F004A81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE manual_checkin_history ADD CONSTRAINT FK_600F004A7597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_measurement ADD CONSTRAINT FK_F5DDCCD37597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE device_config ADD CONSTRAINT FK_79A5E67A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE corporate_key ADD CONSTRAINT FK_D13C28ADCD147EEF FOREIGN KEY (corporate_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE corporate_key_package ADD CONSTRAINT FK_A017927197F1F59D FOREIGN KEY (corporatekey_id) REFERENCES corporate_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE corporate_key_package ADD CONSTRAINT FK_A0179271F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE key_profile_group ADD CONSTRAINT FK_D849CD0597F1F59D FOREIGN KEY (corporatekey_id) REFERENCES corporate_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE key_profile_group ADD CONSTRAINT FK_D849CD0570F8267D FOREIGN KEY (profilekey_id) REFERENCES profile_key (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE schedule_detail ADD CONSTRAINT FK_4C273B8CA40BC2D5 FOREIGN KEY (schedule_id) REFERENCES activity_schedule (id)');
        $this->addSql('ALTER TABLE app_setting_layout ADD CONSTRAINT FK_DF3C0021B82E160E FOREIGN KEY (app_setting_id) REFERENCES app_setting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE app_setting_layout ADD CONSTRAINT FK_DF3C00218C22AA1A FOREIGN KEY (layout_id) REFERENCES layout (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AC51EFA73 FOREIGN KEY (activity_type_id) REFERENCES activity_type (id)');
        $this->addSql('ALTER TABLE profile_key ADD CONSTRAINT FK_24320296979B1AD6 FOREIGN KEY (company_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE profile_key_workouts ADD CONSTRAINT FK_D3CACA12653E3254 FOREIGN KEY (profile_key_id) REFERENCES profile_key (id)');
        $this->addSql('ALTER TABLE profile_key_workouts ADD CONSTRAINT FK_D3CACA12A6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id)');
        $this->addSql('ALTER TABLE facility_package ADD CONSTRAINT FK_6E15CBA0A7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE facility_package ADD CONSTRAINT FK_6E15CBA0F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facility_gallery ADD CONSTRAINT FK_F756D40FA7014910 FOREIGN KEY (facility_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_invitation ADD CONSTRAINT FK_1A537F4BC5D3D9FF FOREIGN KEY (corporate_key_id) REFERENCES corporate_key (id)');
        $this->addSql('ALTER TABLE member_invitation ADD CONSTRAINT FK_1A537F4BD2D03B8 FOREIGN KEY (invitation_template_id) REFERENCES invitation_template (id)');
        $this->addSql('ALTER TABLE member_action ADD CONSTRAINT FK_631A0EA17597D3FE FOREIGN KEY (member_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE member_action ADD CONSTRAINT FK_631A0EA19D32F035 FOREIGN KEY (action_id) REFERENCES actions (id)');
        $this->addSql('ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id)');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447FE54D947');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761727ACA70');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447A76ED395');
        $this->addSql('ALTER TABLE member_challenge_invite DROP FOREIGN KEY FK_4B8C0F07597D3FE');
        $this->addSql('ALTER TABLE member_action_point DROP FOREIGN KEY FK_25D8A1107597D3FE');
        $this->addSql('ALTER TABLE challenge DROP FOREIGN KEY FK_D7098951979B1AD6');
        $this->addSql('ALTER TABLE activity_schedule DROP FOREIGN KEY FK_FA32A1F58C4FC193');
        $this->addSql('ALTER TABLE activity_schedule DROP FOREIGN KEY FK_FA32A1F5A7014910');
        $this->addSql('ALTER TABLE member_key DROP FOREIGN KEY FK_BB348BF27597D3FE');
        $this->addSql('ALTER TABLE member_package DROP FOREIGN KEY FK_619CD0017597D3FE');
        $this->addSql('ALTER TABLE workout DROP FOREIGN KEY FK_649FFB72A76ED395');
        $this->addSql('ALTER TABLE corporate_member_email DROP FOREIGN KEY FK_E3A97B9C7597D3FE');
        $this->addSql('ALTER TABLE corporate_member_email DROP FOREIGN KEY FK_E3A97B9CCD147EEF');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66A76ED395');
        $this->addSql('ALTER TABLE corporate_department DROP FOREIGN KEY FK_8AD59DBCD147EEF');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE686795A7014910');
        $this->addSql('ALTER TABLE member_article DROP FOREIGN KEY FK_BDCEB9F2A76ED395');
        $this->addSql('ALTER TABLE facility_checkin_history DROP FOREIGN KEY FK_612FB270A7014910');
        $this->addSql('ALTER TABLE facility_checkin_history DROP FOREIGN KEY FK_612FB2707597D3FE');
        $this->addSql('ALTER TABLE facility_activity DROP FOREIGN KEY FK_FA77B0D5A7014910');
        $this->addSql('ALTER TABLE member_schedule_activity DROP FOREIGN KEY FK_59C640527597D3FE');
        $this->addSql('ALTER TABLE member_workout DROP FOREIGN KEY FK_DB6B4CE67597D3FE');
        $this->addSql('ALTER TABLE member_promotion_clicks DROP FOREIGN KEY FK_58741DA7597D3FE');
        $this->addSql('ALTER TABLE user_bank_info DROP FOREIGN KEY FK_6109EE3DA76ED395');
        $this->addSql('ALTER TABLE user_documents DROP FOREIGN KEY FK_A250FF6CA76ED395');
        $this->addSql('ALTER TABLE member_device_token DROP FOREIGN KEY FK_EC01DFD4A76ED395');
        $this->addSql('ALTER TABLE facility_amenity DROP FOREIGN KEY FK_1B1DD556A7014910');
        $this->addSql('ALTER TABLE member_billing DROP FOREIGN KEY FK_53D6FB3EA76ED395');
        $this->addSql('ALTER TABLE exercise DROP FOREIGN KEY FK_AEDAD51CA76ED395');
        $this->addSql('ALTER TABLE manual_checkin_history DROP FOREIGN KEY FK_600F004A7597D3FE');
        $this->addSql('ALTER TABLE member_measurement DROP FOREIGN KEY FK_F5DDCCD37597D3FE');
        $this->addSql('ALTER TABLE device_config DROP FOREIGN KEY FK_79A5E67A76ED395');
        $this->addSql('ALTER TABLE corporate_key DROP FOREIGN KEY FK_D13C28ADCD147EEF');
        $this->addSql('ALTER TABLE profile_key DROP FOREIGN KEY FK_24320296979B1AD6');
        $this->addSql('ALTER TABLE facility_package DROP FOREIGN KEY FK_6E15CBA0A7014910');
        $this->addSql('ALTER TABLE facility_gallery DROP FOREIGN KEY FK_F756D40FA7014910');
        $this->addSql('ALTER TABLE member_action DROP FOREIGN KEY FK_631A0EA17597D3FE');
        $this->addSql('ALTER TABLE member_action_point DROP FOREIGN KEY FK_25D8A1109D32F035');
        $this->addSql('ALTER TABLE challenge_action DROP FOREIGN KEY FK_B4712F534B8837D4');
        $this->addSql('ALTER TABLE member_challenge_invite DROP FOREIGN KEY FK_4B8C0F098A21AC6');
        $this->addSql('ALTER TABLE challenge_action DROP FOREIGN KEY FK_B4712F5398A21AC6');
        $this->addSql('ALTER TABLE workout DROP FOREIGN KEY FK_649FFB725FB14BA7');
        $this->addSql('ALTER TABLE activity_schedule_package DROP FOREIGN KEY FK_B741AA4692A20CA5');
        $this->addSql('ALTER TABLE promotions DROP FOREIGN KEY FK_EA1B3034143E8372');
        $this->addSql('ALTER TABLE schedule_detail DROP FOREIGN KEY FK_4C273B8CA40BC2D5');
        $this->addSql('ALTER TABLE member_billing_detail DROP FOREIGN KEY FK_8F3185701F02B516');
        $this->addSql('ALTER TABLE member_schedule_activity DROP FOREIGN KEY FK_59C640521F02B516');
        $this->addSql('ALTER TABLE workout_exercise DROP FOREIGN KEY FK_76AB38AAA6CCCFC9');
        $this->addSql('ALTER TABLE member_workout DROP FOREIGN KEY FK_DB6B4CE6A6CCCFC9');
        $this->addSql('ALTER TABLE profile_key_workouts DROP FOREIGN KEY FK_D3CACA12A6CCCFC9');
        $this->addSql('ALTER TABLE member_promotion_clicks DROP FOREIGN KEY FK_58741DA139DF194');
        $this->addSql('ALTER TABLE layout_sections DROP FOREIGN KEY FK_35E5CDAF8C22AA1A');
        $this->addSql('ALTER TABLE app_setting_layout DROP FOREIGN KEY FK_DF3C00218C22AA1A');
        $this->addSql('ALTER TABLE profile_key_articles DROP FOREIGN KEY FK_C976BB9A7294869C');
        $this->addSql('ALTER TABLE member_article DROP FOREIGN KEY FK_BDCEB9F27294869C');
        $this->addSql('ALTER TABLE layout_sections DROP FOREIGN KEY FK_35E5CDAFD823E37A');
        $this->addSql('ALTER TABLE activity_schedule_package DROP FOREIGN KEY FK_B741AA46F44CABFF');
        $this->addSql('ALTER TABLE member_package DROP FOREIGN KEY FK_619CD001F44CABFF');
        $this->addSql('ALTER TABLE member_schedule_activity DROP FOREIGN KEY FK_59C64052F44CABFF');
        $this->addSql('ALTER TABLE corporate_key_package DROP FOREIGN KEY FK_A0179271F44CABFF');
        $this->addSql('ALTER TABLE facility_package DROP FOREIGN KEY FK_6E15CBA0F44CABFF');
        $this->addSql('ALTER TABLE actions DROP FOREIGN KEY FK_548F1EF727ACA70');
        $this->addSql('ALTER TABLE member_action DROP FOREIGN KEY FK_631A0EA19D32F035');
        $this->addSql('ALTER TABLE facility_amenity DROP FOREIGN KEY FK_1B1DD5569F9F1305');
        $this->addSql('ALTER TABLE member_invitation DROP FOREIGN KEY FK_1A537F4BD2D03B8');
        $this->addSql('ALTER TABLE member_schedule_timelog DROP FOREIGN KEY FK_A192F9916A2B381');
        $this->addSql('ALTER TABLE fos_user_user DROP FOREIGN KEY FK_C560D761E112DAFD');
        $this->addSql('ALTER TABLE workout DROP FOREIGN KEY FK_649FFB72F4505455');
        $this->addSql('ALTER TABLE exercise_lookup DROP FOREIGN KEY FK_8553246E8955C49D');
        $this->addSql('ALTER TABLE base_lookup DROP FOREIGN KEY FK_987C296C727ACA70');
        $this->addSql('ALTER TABLE subscription_billing DROP FOREIGN KEY FK_9F37AC319A1887DC');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867954A17E91F');
        $this->addSql('ALTER TABLE member_billing_detail DROP FOREIGN KEY FK_8F318570D04C426E');
        $this->addSql('ALTER TABLE exercise_lookup DROP FOREIGN KEY FK_8553246EE934951A');
        $this->addSql('ALTER TABLE exercise_image DROP FOREIGN KEY FK_E00BF39DE934951A');
        $this->addSql('ALTER TABLE workout_exercise DROP FOREIGN KEY FK_76AB38AAE934951A');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66289EC824');
        $this->addSql('ALTER TABLE activity DROP FOREIGN KEY FK_AC74095AC51EFA73');
        $this->addSql('ALTER TABLE member_key DROP FOREIGN KEY FK_BB348BF2D145533');
        $this->addSql('ALTER TABLE member_article DROP FOREIGN KEY FK_BDCEB9F2D145533');
        $this->addSql('ALTER TABLE member_workout DROP FOREIGN KEY FK_DB6B4CE6D145533');
        $this->addSql('ALTER TABLE subscription DROP FOREIGN KEY FK_A3C664D3D145533');
        $this->addSql('ALTER TABLE corporate_key_package DROP FOREIGN KEY FK_A017927197F1F59D');
        $this->addSql('ALTER TABLE key_profile_group DROP FOREIGN KEY FK_D849CD0597F1F59D');
        $this->addSql('ALTER TABLE member_invitation DROP FOREIGN KEY FK_1A537F4BC5D3D9FF');
        $this->addSql('ALTER TABLE member_schedule_activity DROP FOREIGN KEY FK_59C6405217D67DCB');
        $this->addSql('ALTER TABLE activity_schedule DROP FOREIGN KEY FK_FA32A1F581C06096');
        $this->addSql('ALTER TABLE facility_activity DROP FOREIGN KEY FK_FA77B0D581C06096');
        $this->addSql('ALTER TABLE manual_checkin_history DROP FOREIGN KEY FK_600F004A81C06096');
        $this->addSql('ALTER TABLE profile_key_articles DROP FOREIGN KEY FK_C976BB9A653E3254');
        $this->addSql('ALTER TABLE key_profile_group DROP FOREIGN KEY FK_D849CD0570F8267D');
        $this->addSql('ALTER TABLE profile_key_workouts DROP FOREIGN KEY FK_D3CACA12653E3254');
        $this->addSql('ALTER TABLE app_setting_layout DROP FOREIGN KEY FK_DF3C0021B82E160E');
        $this->addSql('ALTER TABLE member_device_token DROP FOREIGN KEY FK_EC01DFD48BE312B3');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806EA000B10');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806DF9183C9');
        $this->addSql('ALTER TABLE acl_object_identities DROP FOREIGN KEY FK_9407E54977FA751A');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE2993D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE299C671CEA1');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B8063D9AB4A6');
        $this->addSql('DROP TABLE fos_user_group');
        $this->addSql('DROP TABLE fos_user_user');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('DROP TABLE member_challenge_invite');
        $this->addSql('DROP TABLE gmf_actions');
        $this->addSql('DROP TABLE member_action_point');
        $this->addSql('DROP TABLE challenge_action');
        $this->addSql('DROP TABLE challenge');
        $this->addSql('DROP TABLE workout_level');
        $this->addSql('DROP TABLE exercise_lookup');
        $this->addSql('DROP TABLE member_billing_detail');
        $this->addSql('DROP TABLE activity_schedule');
        $this->addSql('DROP TABLE activity_schedule_package');
        $this->addSql('DROP TABLE profile_key_articles');
        $this->addSql('DROP TABLE member_key');
        $this->addSql('DROP TABLE member_package');
        $this->addSql('DROP TABLE error_log');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE promotions');
        $this->addSql('DROP TABLE corporate_member_email');
        $this->addSql('DROP TABLE subscription_billing');
        $this->addSql('DROP TABLE layout');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE member_filter');
        $this->addSql('DROP TABLE corporate_department');
        $this->addSql('DROP TABLE sections');
        $this->addSql('DROP TABLE exercise_image');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE actions');
        $this->addSql('DROP TABLE member_article');
        $this->addSql('DROP TABLE facility_checkin_history');
        $this->addSql('DROP TABLE member_schedule_timelog');
        $this->addSql('DROP TABLE amenity');
        $this->addSql('DROP TABLE invitation_template');
        $this->addSql('DROP TABLE workout_exercise');
        $this->addSql('DROP TABLE facility_activity');
        $this->addSql('DROP TABLE member_schedule_activity');
        $this->addSql('DROP TABLE member_workout');
        $this->addSql('DROP TABLE layout_sections');
        $this->addSql('DROP TABLE app_version');
        $this->addSql('DROP TABLE member_promotion_clicks');
        $this->addSql('DROP TABLE workout_type');
        $this->addSql('DROP TABLE base_lookup');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE user_bank_info');
        $this->addSql('DROP TABLE user_documents');
        $this->addSql('DROP TABLE member_device_token');
        $this->addSql('DROP TABLE configurations');
        $this->addSql('DROP TABLE package_type');
        $this->addSql('DROP TABLE facility_amenity');
        $this->addSql('DROP TABLE member_billing');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE manual_checkin_history');
        $this->addSql('DROP TABLE member_measurement');
        $this->addSql('DROP TABLE device_config');
        $this->addSql('DROP TABLE article_type');
        $this->addSql('DROP TABLE activity_type');
        $this->addSql('DROP TABLE corporate_key');
        $this->addSql('DROP TABLE corporate_key_package');
        $this->addSql('DROP TABLE key_profile_group');
        $this->addSql('DROP TABLE schedule_detail');
        $this->addSql('DROP TABLE app_setting_layout');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE profile_key');
        $this->addSql('DROP TABLE profile_key_workouts');
        $this->addSql('DROP TABLE app_setting');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE api_key');
        $this->addSql('DROP TABLE facility_package');
        $this->addSql('DROP TABLE facility_gallery');
        $this->addSql('DROP TABLE member_invitation');
        $this->addSql('DROP TABLE member_action');
        $this->addSql('DROP TABLE acl_classes');
        $this->addSql('DROP TABLE acl_security_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_entries');
    }
}
