<?php

namespace App\Gamification\Bundle\Repository;

/**
 * ChallengeActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeActionRepository extends \Doctrine\ORM\EntityRepository
{
}
