<?php

namespace App\Gamification\Bundle\Repository;

use App\Application\Sonata\UserBundle\Entity\User;

/**
 * ChallengeActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberChallengeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserChallenges(User $user,$status,$company = null)
    {

        $qb = $this->createQueryBuilder('mc');
        $qb
            ->innerJoin('App\Application\Sonata\UserBundle\Entity\User','m','WITH','m.id = mc.member')
            ->innerJoin('App\Gamification\Bundle\Entity\Challenge','c','WITH','c.id = mc.challenge')
            ->where('m.id = :user_id')
            ->andWhere('mc.status = :status')
            ->select('c')
            ->setParameter('user_id',$user->getId())
            ->setParameter('status',$status)
            ->andWhere('c.isActive = :isActive')
            ->andWhere('c.end_date >= :now')
            ->andWhere('mc.isDeleted = :isDeleted')
            ->andWhere('c.isDeleted = :isDeleted')
            ->setParameter('isActive',true)
            ->setParameter('isDeleted',false)
            ->setParameter('now',new \DateTime())
            ->addOrderBy('c.start_date','ASC')
        ;
        if($company){

            $qb
//                ->innerJoin('Application\Sonata\UserBundle\Entity\User','co','co.id =')
                ->andWhere('c.company = :company')
                ->setParameter('company',$company)

            ;
        }

        return $qb->getQuery();
    }
}
