<?php

namespace App\Application\Sonata\UserBundle\Entity;

use App\Entity\ActivitySchedule;
use App\Entity\Article;
use App\Entity\CorporateDepartment;
use App\Entity\CorporateKey;
use App\Entity\DeviceConfig;
use App\Entity\Exercise;
use App\Entity\FacilityActivity;
use App\Entity\FacilityAmenity;
use App\Entity\FacilityGallery;
use App\Entity\FacilityPackage;
use App\Entity\MemberAction;
use App\Entity\MemberBillingHistory;
use App\Entity\MemberDeviceToken;
use App\Entity\MemberKey;
use App\Entity\MemberMeasurement;
use App\Entity\MemberPackage;
use App\Entity\MemberScheduleActivity;
use App\Entity\MemberWorkout;
use App\Entity\Package;
use App\Entity\ProfileKey;
use App\Entity\UserBankInfo;
use App\Entity\UserDocuments;
use App\Entity\Workout;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{


    public function __construct()
    {

        parent::__construct();
        $this->fosUser = new ArrayCollection();
        $this->corporateKey = new ArrayCollection();
        $this->corporateDepartment = new ArrayCollection();
        $this->corporateMember = new ArrayCollection();
        $this->corporateUser = new ArrayCollection();
        $this->memberMeasurement = new ArrayCollection();
        $this->facilityActivity = new ArrayCollection();
        $this->memberAction = new ArrayCollection();
        $this->article = new ArrayCollection();
        $this->member = new ArrayCollection();
        $this->package = new ArrayCollection();
        $this->activitySchedule = new ArrayCollection();
        $this->activitySchedulefacility = new ArrayCollection();
        $this->amenity = new ArrayCollection();
        $this->workout = new ArrayCollection();
        $this->memberAction = new ArrayCollection();
        $this->memberWorkout = new ArrayCollection();
        $this->exercise = new ArrayCollection();
        $this->memberSchedule = new ArrayCollection();
        $this->facilityGallery = new ArrayCollection();
        $this->facilityPackage = new ArrayCollection();
        $this->memberPackage = new ArrayCollection();
        $this->userDocument = new ArrayCollection();
        $this->UserBankInfo = new ArrayCollection();
        $this->memberBillingHistory = new ArrayCollection();
        $this->deviceconfig = new ArrayCollection();

    }



    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var boolean $isGDPR
     */
    protected $isGDPR;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberAction", mappedBy="user")
     */
    protected $memberAction;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @ORM\ManyToOne(targetEntity="User",  inversedBy="fosUser")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id")
     */
    protected $parentUser;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AppVersion",  inversedBy="user")
     */
    protected $appVersion;

    /**
     * @ORM\OneToMany(targetEntity="User", mappedBy="parentUser")
     */
    protected $fosUser;

    /**
     * @ORM\OneToMany(targetEntity="App\Gamification\Bundle\Entity\MemberChallenge",mappedBy="member")
     */
    protected $challanges;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CorporateMemberEmail",mappedBy="corporate")
     */
    protected $corporateEmail;
    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=100)
     */
    protected $address;

    /**
     * @var string
     *
     * @ORM\Column(name="address_one", type="string", length=100)
     */
    protected $addressOne;

    /**
     * @var string
     *
     * @ORM\Column(name="address_two", type="string", length=100)
     */
    protected $addressTwo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CorporateMemberEmail",mappedBy="member")
     */
    protected $corporateMemberEmail;

    /**
     * @ORM\Column(name="po_box", type="string", length=50)
     */
    protected $PoBox;

    /**
     * @ORM\Column(name="city", type="string", length=100)
     */
    protected $city;

    /**
     * @ORM\Column(name="country", type="string", length=100)
     */
    protected $country;

    /**
     * @ORM\Column(name="contact_title", type="string", length=100)
     */
    protected $contactTitle;

    /**
     * @ORM\Column(name="contract_firstname", type="string", length=100)
     */
    protected $contactFirstname;

    /**
     * @ORM\Column(name="contact_lastname", type="string", length=100)
     */
    protected $contactLastname;

    /**
     * @ORM\Column(name="designation", type="string", length=100)
     */
    protected $designation;

    /**
     * @ORM\Column(name="contact_email", type="string", length=100)
     */
    protected $contactEmail;

    /**
     * @ORM\Column(name="contact_no", type="string", length=20)
     */
    protected $contactNo;

    /**
     * @ORM\Column(name="contact_url", type="string", length=50)
     */
    protected $contactUrl;

    /**
     * @ORM\Column(name="notes", type="string", length=255)
     */
    protected $contactNotes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CorporateKey", mappedBy="corporate")
     */
    protected $corporateKey;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CorporateDepartment", mappedBy="corporateUser")
     */
    protected $corporateDepartment;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberKey", mappedBy="member", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $corporateMember;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberDeviceToken", mappedBy="user")
     */
    protected $memberDeviceToken;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProfileKey", mappedBy="companyId")
     */
    protected $companyId;

    /**
     *
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="companyLogo")
     *
     * @var File
     */
    protected $profileImage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    protected $companyLogo;

    /**
     * @ORM\Column(name="company_name", type="string", length=100, nullable=true)
     *
     * @var string
     */
    protected $companyName;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberMeasurement", mappedBy="user")
     */
    protected $memberMeasurement;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FacilityActivity", mappedBy="facility")
     */
    protected $facilityActivity;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="user")
     */
    protected $article;




    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Package", mappedBy="facility")
     */
    private $package;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ActivitySchedule", mappedBy="instructor")
     */
    private $activitySchedule;



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ActivitySchedule", mappedBy="facility")
     */
    private $activitySchedulefacility;

    /**
     * @ORM\Column(name="latitude", type="string", length=100, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(name="longitude", type="string", length=100, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(name="card_id", type="string", length=100, nullable=true)
     */
    private $card;

    /**
     * @ORM\Column(name="notification", type="boolean", options={"default": 1})
     */
    private $notification = true;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FacilityAmenity", mappedBy="facility")
     */
    private $amenity;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Workout", mappedBy="user")
     */
    private $workout;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberWorkout", mappedBy="member")
     */
    private $memberWorkout;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Exercise", mappedBy="user")
     */
    private $exercise;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberScheduleActivity", mappedBy="member")
     */
    private $memberSchedule;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FacilityGallery", mappedBy="facility")
     */
    private $facilityGallery;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FacilityPackage", mappedBy="facility")
     */
    private $facilityPackage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberPackage", mappedBy="member")
     */
    private $memberPackage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserDocuments", mappedBy="user")
     */
    private $userDocument;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UserBankInfo", mappedBy="user")
     */
    private $UserBankInfo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MemberBillingHistory", mappedBy="user")
     */
    private $memberBillingHistory;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\DeviceConfig", mappedBy="user")
     */
    private $deviceconfig;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FacilityCheckinHistory",mappedBy="facilityId")
     */
    private $nonPartnerFacility;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FacilityCheckinHistory",mappedBy="memberId")
     */
    private $nonPartnerMember;

    /**
     * @ORM\Column(name="enable_discount",type="boolean")
     */
    private $enableDiscount = false;


    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $stepCount;

    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $distance;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $stepDateTime;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ManualCheckinHistory",mappedBy="member")
     */
    private $manualCheckInHistory;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $lastRewardSteps;
    /**
     * @return mixed
     */
    public function getDistance()
    {
        return $this->distance;
    }

    public function getDistanceApi()
    {
        if($this->distance) {
            return $this->distance;
        }

        return 0.0;
    }

    /**
     * @param mixed $distance
     */
    public function setDistance($distance)
    {
        $this->distance = $distance;
    }

    /**
     * @return mixed
     */
    public function getStepCount()
    {
        return $this->stepCount;
    }


    public function getStepCountApi()
    {
        if($this->stepCount) {
            return $this->stepCount;
        }
        return 0;
    }

    /**
     * @param mixed $stepCount
     */
    public function setStepCount($stepCount)
    {
        $this->stepCount = $stepCount;
    }


    /**
     * @return mixed
     */
    public function getFacilityPackage()
    {
        return $this->facilityPackage;
    }


    /**
     * @return mixed
     */
    public function getFacilityGallery()
    {
        return $this->facilityGallery;
    }

    /**
     * @return mixed
     */
    public function getMemberSchedule()
    {
        return $this->memberSchedule;
    }

    /**
     * @return string
     */
    public function getCompanyLogo()
    {

        if ($this->companyLogo) {
            return '/images/member/'.$this->companyLogo;
        } else {
            return '/icon/default_image.png';
        }
    }

    public function getImageName(){
        return $this->getCompanyLogo();
    }
    /**
     * @param string $companyLogo
     */
    public function setCompanyLogo($companyLogo)
    {
        $this->companyLogo = $companyLogo;
    }


    /**
     * @return string
     */
    public function getCompanyName()
    {
        return $this->companyName;
    }

    /**
     * @param string $companyName
     */
    public function setCompanyName($companyName)
    {
        $this->companyName = $companyName;
    }

    /**
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return User
     * @throws \Exception
     */
    public function setProfileImage(File $image = null)
    {

        $this->profileImage = $image;
        if (isset($image)) {
            $this->setUpdatedAt(new \DateTime());
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getProfileImage()
    {
        return $this->profileImage;
    }


    /**
     * Set parentUser
     *
     *
     * @return User
     */
    public function setParentUser(User $user = null)
    {
        $this->parentUser = $user;

        return $this;
    }

    /**
     * Get parentUser
     *
     * @return int $parentUser
     */
    public function getParentUser()
    {
        return $this->parentUser;
    }


    /**
     * Get address
     *
     * @return string $address
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set address
     *
     *
     * @return address
     */
    public function setAddress($address)
    {
        $this->address = $address;
        return $this;
    }


    /**
     * @return string
     */
    public function getAddressOne()
    {
        return $this->addressOne;
    }

    /**
     * @param string $addressOne
     */
    public function setAddressOne($addressOne)
    {
        $this->addressOne = $addressOne;
    }

    /**
     * @return string
     */
    public function getAddressTwo()
    {
        return $this->addressTwo;
    }

    /**
     * @param string $addressTwo
     */
    public function setAddressTwo($addressTwo)
    {
        $this->addressTwo = $addressTwo;
    }

    /**
     * @return mixed
     */
    public function getContactNotes()
    {
        return $this->contactNotes;
    }

    /**
     * @param mixed $contactNotes
     */
    public function setContactNotes($contactNotes)
    {
        $this->contactNotes = $contactNotes;
    }

    /**
     * @return mixed
     */
    public function getContactUrl()
    {
        return $this->contactUrl;
    }

    /**
     * @param mixed $contactUrl
     */
    public function setContactUrl($contactUrl)
    {
        $this->contactUrl = $contactUrl;
    }

    /**
     * @return mixed
     */
    public function getContactNo()
    {
        return $this->contactNo;
    }

    /**
     * @param mixed $contactNo
     */
    public function setContactNo($contactNo)
    {
        $this->contactNo = $contactNo;
    }

    /**
     * @return mixed
     */
    public function getContactEmail()
    {
        return $this->contactEmail;
    }

    /**
     * @param mixed $contactEmail
     */
    public function setContactEmail($contactEmail)
    {
        $this->contactEmail = $contactEmail;
    }

    /**
     * @return mixed
     */
    public function getDesignation()
    {
        return $this->designation;
    }

    /**
     * @param mixed $designation
     */
    public function setDesignation($designation)
    {
        $this->designation = $designation;
    }

    /**
     * @return mixed
     */
    public function getContactLastname()
    {
        return $this->contactLastname;
    }

    /**
     * @param mixed $contactLastname
     */
    public function setContactLastname($contactLastname)
    {
        $this->contactLastname = $contactLastname;
    }

    /**
     * @return mixed
     */
    public function getContactFirstname()
    {
        return $this->contactFirstname;
    }

    /**
     * @param mixed $contactFirstname
     */
    public function setContactFirstname($contactFirstname)
    {
        $this->contactFirstname = $contactFirstname;
    }

    /**
     * @return mixed
     */
    public function getContactTitle()
    {
        return $this->contactTitle;
    }

    /**
     * @param mixed $contactTitle
     */
    public function setContactTitle($contactTitle)
    {
        $this->contactTitle = $contactTitle;
    }

    /**
     * @return mixed
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param mixed $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return mixed
     */
    public function getPoBox()
    {
        return $this->PoBox;
    }

    /**
     * @param mixed $PoBox
     */
    public function setPoBox($PoBox)
    {
        $this->PoBox = $PoBox;
    }


    /**
     * @return mixed
     */
    public function getFosUser()
    {
        return $this->fosUser;
    }

    /**
     * @param mixed $fosUser
     */
    public function setFosUser(ArrayCollection $fosUser)
    {
        $this->fosUser = $fosUser;
    }

    /**
     * @return mixed
     */
    public function getCorporateKey()
    {
        return $this->corporateKey;
    }

    /**
     * @param mixed $corporateKey
     */
    public function setCorporateKey(ArrayCollection $corporateKey)
    {
        $this->corporateKey = $corporateKey;
    }

    /**
     * @return mixed
     */
    public function getCorporateDepartment()
    {
        return $this->corporateDepartment;
    }

    /**
     * @param mixed $corporateDepartment
     */
    public function setCorporateDepartment(ArrayCollection $corporateDepartment)
    {
        $this->corporateDepartment = $corporateDepartment;
    }


    /**
     * @return mixed
     */
    public function getCorporateMember()
    {

        return $this->corporateMember;
    }

    /**
     * @param mixed $corporateMember
     * @return User
     */
    public function setCorporateMember(ArrayCollection $corporateMember)
    {
        $this->corporateMember = $corporateMember;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getMemberMeasurement()
    {
        return $this->memberMeasurement;
    }

    /**
     * @return mixed
     */
    public function getFacilityActivity()
    {
        return $this->facilityActivity;
    }

    /**
     * Get package
     *
     * @return Collection
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     * Set latitude
     *
     * @param string $latitude
     *
     * @return User
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * Get latitude
     *
     * @return string
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Set longitude
     *
     * @param string $longitude
     *
     * @return User
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * Get longitude
     *
     * @return string
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Add fosUser
     *
     * @param User $fosUser
     *
     * @return User
     */
    public function addFosUser(User $fosUser)
    {
        $this->fosUser[] = $fosUser;

        return $this;
    }

    /**
     * Remove fosUser
     *
     * @param User $fosUser
     */
    public function removeFosUser(User $fosUser)
    {
        $this->fosUser->removeElement($fosUser);
    }

    /**
     * Add corporateKey
     *
     * @param CorporateKey $corporateKey
     *
     * @return User
     */
    public function addCorporateKey(CorporateKey $corporateKey)
    {
        $this->corporateKey[] = $corporateKey;

        return $this;
    }

    /**
     * Remove corporateKey
     *
     * @param CorporateKey $corporateKey
     */
    public function removeCorporateKey(CorporateKey $corporateKey)
    {
        $this->corporateKey->removeElement($corporateKey);
    }

    /**
     * Add corporateDepartment
     *
     * @param CorporateDepartment $corporateDepartment
     *
     * @return User
     */
    public function addCorporateDepartment(CorporateDepartment $corporateDepartment)
    {
        $this->corporateDepartment[] = $corporateDepartment;

        return $this;
    }

    /**
     * Remove corporateDepartment
     *
     * @param CorporateDepartment $corporateDepartment
     */
    public function removeCorporateDepartment(CorporateDepartment $corporateDepartment)
    {
        $this->corporateDepartment->removeElement($corporateDepartment);
    }

    /**
     * Add corporateMember
     *
     * @param MemberKey $corporateMember
     *
     * @return User
     */
    public function addCorporateMember(MemberKey $corporateMember)
    {
        $this->corporateMember[] = $corporateMember;

        return $this;
    }

    /**
     * Remove corporateMember
     *
     * @param MemberKey $corporateMember
     */
    public function removeCorporateMember(MemberKey $corporateMember)
    {
        $this->corporateMember->removeElement($corporateMember);
    }

    /**
     * Add memberMeasurement
     *
     * @param MemberMeasurement $memberMeasurement
     *
     * @return User
     */
    public function addMemberMeasurement(MemberMeasurement $memberMeasurement)
    {
        $this->memberMeasurement[] = $memberMeasurement;

        return $this;
    }

    /**
     * Remove memberMeasurement
     *
     * @param MemberMeasurement $memberMeasurement
     */
    public function removeMemberMeasurement(MemberMeasurement $memberMeasurement)
    {
        $this->memberMeasurement->removeElement($memberMeasurement);
    }

    /**
     * Add facilityActivity
     *
     * @param FacilityActivity $facilityActivity
     *
     * @return User
     */
    public function addFacilityActivity(FacilityActivity $facilityActivity)
    {
        $this->facilityActivity[] = $facilityActivity;

        return $this;
    }

    /**
     * Remove facilityActivity
     *
     * @param FacilityActivity $facilityActivity
     */
    public function removeFacilityActivity(FacilityActivity $facilityActivity)
    {
        $this->facilityActivity->removeElement($facilityActivity);
    }

    /**
     * Add article
     *
     * @param Article $article
     *
     * @return User
     */
    public function addArticle(Article $article)
    {
        $this->article[] = $article;

        return $this;
    }

    /**
     * Remove article
     *
     * @param Article $article
     */
    public function removeArticle(Article $article)
    {
        $this->article->removeElement($article);
    }

    /**
     * Get article
     *
     * @return Collection
     */
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * Add member
     *
     * @param Article $member
     *
     * @return User
     */
    public function addMember(Article $member)
    {
        $this->member[] = $member;

        return $this;
    }

    /**
     * Remove member
     *
     * @param Article $member
     */
    public function removeMember(Article $member)
    {
        $this->member->removeElement($member);
    }

    /**
     * Get member
     *
     * @return Collection
     */
    public function getMember()
    {
        return $this->member;
    }

    /**
     * Add package
     *
     * @param Package $package
     *
     * @return User
     */
    public function addPackage(Package $package)
    {
        $this->package[] = $package;

        return $this;
    }

    /**
     * Remove package
     *
     * @param Package $package
     */
    public function removePackage(Package $package)
    {
        $this->package->removeElement($package);
    }

    /**
     * Add activitySchedule
     *
     * @param ActivitySchedule $activitySchedule
     *
     * @return User
     */
    public function addActivitySchedule(ActivitySchedule $activitySchedule)
    {
        $this->activitySchedule[] = $activitySchedule;

        return $this;
    }

    /**
     * Remove activitySchedule
     *
     * @param ActivitySchedule $activitySchedule
     */
    public function removeActivitySchedule(ActivitySchedule $activitySchedule)
    {
        $this->activitySchedule->removeElement($activitySchedule);
    }

    /**
     * Get activitySchedule
     *
     * @return Collection
     */
    public function getActivitySchedule()
    {
        return $this->activitySchedule;
    }

    /**
     * Add activitySchedulefacility
     *
     * @param ActivitySchedule $activitySchedulefacility
     *
     * @return User
     */
    public function addActivitySchedulefacility(ActivitySchedule $activitySchedulefacility)
    {
        $this->activitySchedulefacility[] = $activitySchedulefacility;

        return $this;
    }

    /**
     * Remove activitySchedulefacility
     *
     * @param ActivitySchedule $activitySchedulefacility
     */
    public function removeActivitySchedulefacility(ActivitySchedule $activitySchedulefacility)
    {
        $this->activitySchedulefacility->removeElement($activitySchedulefacility);
    }

    /**
     * Get activitySchedulefacility
     *
     * @return Collection
     */
    public function getActivitySchedulefacility()
    {
        return $this->activitySchedulefacility;
    }

    /**
     * Add amenity
     *
     * @param FacilityAmenity $amenity
     *
     * @return User
     */
    public function addAmenity(FacilityAmenity $amenity)
    {
        $this->amenity[] = $amenity;

        return $this;
    }

    /**
     * Remove amenity
     *
     * @param FacilityAmenity $amenity
     */
    public function removeAmenity(FacilityAmenity $amenity)
    {
        $this->amenity->removeElement($amenity);
    }

    /**
     * Get amenity
     *
     * @return Collection
     */
    public function getAmenity()
    {
        return $this->amenity;
    }

    /**
     * Add workout
     *
     * @param Workout $workout
     *
     * @return User
     */
    public function addWorkout(Workout $workout)
    {
        $this->workout[] = $workout;

        return $this;
    }

    /**
     * Remove workout
     *
     * @param Workout $workout
     */
    public function removeWorkout(Workout $workout)
    {
        $this->workout->removeElement($workout);
    }

    /**
     * Get workout
     *
     * @return Collection
     */
    public function getWorkout()
    {
        return $this->workout;
    }

    /**
     * Add memberWorkout
     *
     * @param MemberWorkout $memberWorkout
     *
     * @return User
     */
    public function addMemberWorkout(MemberWorkout $memberWorkout)
    {
        $this->memberWorkout[] = $memberWorkout;

        return $this;
    }

    /**
     * Remove memberWorkout
     *
     * @param MemberWorkout $memberWorkout
     */
    public function removeMemberWorkout(MemberWorkout $memberWorkout)
    {
        $this->memberWorkout->removeElement($memberWorkout);
    }

    /**
     * Get memberWorkout
     *
     * @return Collection
     */
    public function getMemberWorkout()
    {
        return $this->memberWorkout;
    }

    /**
     * Add exercise
     *
     * @param Exercise $exercise
     *
     * @return User
     */
    public function addExercise(Exercise $exercise)
    {
        $this->exercise[] = $exercise;

        return $this;
    }

    /**
     * Remove exercise
     *
     * @param Exercise $exercise
     */
    public function removeExercise(Exercise $exercise)
    {
        $this->exercise->removeElement($exercise);
    }

    /**
     * Get exercise
     *
     * @return Collection
     */
    public function getExercise()
    {
        return $this->exercise;
    }

    /**
     * Add memberSchedule
     *
     * @param MemberScheduleActivity $memberSchedule
     *
     * @return User
     */
    public function addMemberSchedule(MemberScheduleActivity $memberSchedule)
    {
        $this->memberSchedule[] = $memberSchedule;

        return $this;
    }

    /**
     * Remove memberSchedule
     *
     * @param MemberScheduleActivity $memberSchedule
     */
    public function removeMemberSchedule(MemberScheduleActivity $memberSchedule)
    {
        $this->memberSchedule->removeElement($memberSchedule);
    }

    /**
     * Add facilityGallery
     *
     * @param FacilityGallery $facilityGallery
     *
     * @return User
     */
    public function addFacilityGallery(FacilityGallery $facilityGallery)
    {
        $this->facilityGallery[] = $facilityGallery;

        return $this;
    }

    /**
     * Remove facilityGallery
     *
     * @param FacilityGallery $facilityGallery
     */
    public function removeFacilityGallery(FacilityGallery $facilityGallery)
    {
        $this->facilityGallery->removeElement($facilityGallery);
    }

    /**
     * Add facilityPackage
     *
     * @param FacilityPackage $facilityPackage
     *
     * @return User
     */
    public function addFacilityPackage(FacilityPackage $facilityPackage)
    {
        $this->facilityPackage[] = $facilityPackage;

        return $this;
    }

    /**
     * Remove facilityPackage
     *
     * @param FacilityPackage $facilityPackage
     */
    public function removeFacilityPackage(FacilityPackage $facilityPackage)
    {
        $this->facilityPackage->removeElement($facilityPackage);
    }

    /**
     * Add memberPackage
     *
     * @param MemberPackage $memberPackage
     *
     * @return User
     */
    public function addMemberPackage(MemberPackage $memberPackage)
    {
        $this->memberPackage[] = $memberPackage;

        return $this;
    }

    /**
     * Remove memberPackage
     *
     * @param MemberPackage $memberPackage
     */
    public function removeMemberPackage(MemberPackage $memberPackage)
    {
        $this->memberPackage->removeElement($memberPackage);
    }

    /**
     * Get memberPackage
     *
     * @return Collection
     */
    public function getMemberPackage()
    {
        return $this->memberPackage;
    }



    /**
     * Add userDocument
     *
     * @param UserDocuments $userDocument
     *
     * @return User
     */
    public function addUserDocument(UserDocuments $userDocument)
    {
        $this->userDocument[] = $userDocument;

        return $this;
    }

    /**
     * Remove userDocument
     *
     * @param UserDocuments $userDocument
     */
    public function removeUserDocument(UserDocuments $userDocument)
    {
        $this->userDocument->removeElement($userDocument);
    }

    /**
     * Get userDocument
     *
     * @return Collection
     */
    public function getUserDocument()
    {
        return $this->userDocument;
    }

    /**
     * Add userBankInfo
     *
     * @param UserBankInfo $userBankInfo
     *
     * @return User
     */
    public function addUserBankInfo(UserBankInfo $userBankInfo)
    {
        $this->UserBankInfo[] = $userBankInfo;

        return $this;
    }

    /**
     * Remove userBankInfo
     *
     * @param UserBankInfo $userBankInfo
     */
    public function removeUserBankInfo(UserBankInfo $userBankInfo)
    {
        $this->UserBankInfo->removeElement($userBankInfo);
    }

    /**
     * Get userBankInfo
     *
     * @return Collection
     */
    public function getUserBankInfo()
    {
        return $this->UserBankInfo;
    }

    /**
     * Set card
     *
     * @param string $card
     *
     * @return User
     */
    public function setCard($card)
    {
        $this->card = $card;

        return $this;
    }

    /**
     * Get card
     *
     * @return string
     */
    public function getCard()
    {
        return $this->card;
    }





    /**
     * Add memberBillingHistory
     *
     * @param MemberBillingHistory $memberBillingHistory
     *
     * @return User
     */
    public function addMemberBillingHistory(MemberBillingHistory $memberBillingHistory)
    {
        $this->memberBillingHistory[] = $memberBillingHistory;

        return $this;
    }

    /**
     * Remove memberBillingHistory
     *
     * @param MemberBillingHistory $memberBillingHistory
     */
    public function removeMemberBillingHistory(MemberBillingHistory $memberBillingHistory)
    {
        $this->memberBillingHistory->removeElement($memberBillingHistory);
    }

    /**
     * Get memberBillingHistory
     *
     * @return Collection
     */
    public function getMemberBillingHistory()
    {
        return $this->memberBillingHistory;
    }


    /**
     * Set notification
     *
     * @param boolean $notification
     *
     * @return User
     */
    public function setNotification($notification)
    {
        $this->notification = $notification;

        return $this;
    }

    /**
     * Get notification
     *
     * @return boolean
     */
    public function getNotification()
    {
        return $this->notification;
    }

    /**
     * Add memberDeviceToken
     *
     * @param MemberDeviceToken $memberDeviceToken
     *
     * @return User
     */
    public function addMemberDeviceToken(MemberDeviceToken $memberDeviceToken)
    {
        $this->memberDeviceToken[] = $memberDeviceToken;

        return $this;
    }

    /**
     * Remove memberDeviceToken
     *
     * @param MemberDeviceToken $memberDeviceToken
     */
    public function removeMemberDeviceToken(MemberDeviceToken $memberDeviceToken)
    {
        $this->memberDeviceToken->removeElement($memberDeviceToken);
    }

    /**
     * Get memberDeviceToken
     *
     * @return Collection
     */
    public function getMemberDeviceToken()
    {
        return $this->memberDeviceToken;
    }

    /**
     * Add companyId
     *
     * @param ProfileKey $companyId
     *
     * @return User
     */
    public function addCompanyId(ProfileKey $companyId)
    {
        $this->companyId[] = $companyId;

        return $this;
    }

    /**
     * Remove companyId
     *
     * @param ProfileKey $companyId
     */
    public function removeCompanyId(ProfileKey $companyId)
    {
        $this->companyId->removeElement($companyId);
    }

    /**
     * Get companyId
     *
     * @return Collection
     */
    public function getCompanyId()
    {
        return $this->companyId;
    }

    /**
     * Add deviceconfig
     *
     * @param DeviceConfig $deviceconfig
     *
     * @return User
     */
    public function addDeviceconfig(DeviceConfig $deviceconfig)
    {
        $this->deviceconfig[] = $deviceconfig;

        return $this;
    }

    /**
     * Remove deviceconfig
     *
     * @param DeviceConfig $deviceconfig
     */
    public function removeDeviceconfig(DeviceConfig $deviceconfig)
    {
        $this->deviceconfig->removeElement($deviceconfig);
    }

    /**
     * Get deviceconfig
     *
     * @return Collection
     */
    public function getDeviceconfig()
    {
        return $this->deviceconfig;
    }

    /**
     * @return bool
     */
    public function isGDPR()
    {
        return $this->isGDPR;
    }

    /**
     * @param bool $isGDPR
     */
    public function setIsGDPR($isGDPR)
    {
        $this->isGDPR = $isGDPR;
    }

    /**
     * @return mixed
     */
    public function getNonPartnerFacility()
    {
        return $this->nonPartnerFacility;
    }

    /**
     * @param mixed $nonPartnerFacility
     */
    public function setNonPartnerFacility($nonPartnerFacility)
    {
        $this->nonPartnerFacility = $nonPartnerFacility;
    }

    /**
     * @return mixed
     */
    public function getNonPartnerMember()
    {
        return $this->nonPartnerMember;
    }

    /**
     * @param mixed $nonPartnerMember
     */
    public function setNonPartnerMember($nonPartnerMember)
    {
        $this->nonPartnerMember = $nonPartnerMember;
    }

    /**
     * @return mixed
     */
    public function getAppVersion()
    {
        return $this->appVersion;
    }

    /**
     * @param mixed $appVersion
     */
    public function setAppVersion($appVersion)
    {
        $this->appVersion = $appVersion;
    }

    /**
     * @return mixed
     */
    public function getChallanges()
    {
        return $this->challanges;
    }

    /**
     * @param mixed $challanges
     */
    public function setChallanges($challanges)
    {
        $this->challanges = $challanges;
    }


    public function getUsernameExport()
    {
        return parent::getUsername(); // TODO: Change the autogenerated stub
    }


    public function getCheckInCount()
    {

        global $kernel;
        $em = $kernel->getContainer()->get('doctrine')->getManager();
        return $em
            ->getRepository('ApplicationSonataUserBundle:User')->getCounts(Shared::CHECKIN,$this->getId());
    }


    public function getWorkoutCount()
    {

        global $kernel;
        $em = $kernel->getContainer()->get('doctrine')->getManager();
        return $em
            ->getRepository('ApplicationSonataUserBundle:User')->getCounts(Shared::WORKOUT,$this->getId());
    }


    public function getArticleCount()
    {

        global $kernel;
        $em = $kernel->getContainer()->get('doctrine')->getManager();
        return $em
            ->getRepository('ApplicationSonataUserBundle:User')->getCounts(Shared::ARTICLE,$this->getId());
    }


    public function getTotalPoints()
    {

        global $kernel;
        $em = $kernel->getContainer()->get('doctrine')->getManager();
        return $em
            ->getRepository('ApplicationSonataUserBundle:User')->getTotalPoints($this->getId());
    }

    public function getChallengesData()
    {

    }

    public function getGenderExport()
    {

        switch ($this->getGender()){
            case 'm':
                return 'Male';
                break;
            case 'u':
                return 'Unknown';
            default:
                return 'Female';
        }
    }

    /**
     * @return mixed
     */
    public function getEnableDiscount()
    {
        return $this->enableDiscount;
    }

    /**
     * @param mixed $enableDiscount
     */
    public function setEnableDiscount($enableDiscount)
    {
        $this->enableDiscount = $enableDiscount;
    }

    /**
     * Add memberAction
     *
     * @param MemberAction $memberAction
     *
     * @return User
     */
    public function addMemberAction(MemberAction $memberAction)
    {
        $this->memberAction[] = $memberAction;

        return $this;
    }

    /**
     * Remove memberAction
     *
     * @param MemberAction $memberAction
     */
    public function removeMemberAction(MemberAction $memberAction)
    {
        $this->memberAction->removeElement($memberAction);
    }

    /**
     * Get memberAction
     *
     * @return Collection
     */
    public function getMemberAction()
    {
        return $this->memberAction;
    }

    /**
     * @return mixed
     */
    public function getManualCheckInHistory()
    {
        return $this->manualCheckInHistory;
    }

    /**
     * @param mixed $manualCheckInHistory
     */
    public function setManualCheckInHistory($manualCheckInHistory)
    {
        $this->manualCheckInHistory = $manualCheckInHistory;
    }

    /**
     * @return mixed
     */
    public function getCorporateMemberEmail()
    {
        return $this->corporateMemberEmail;
    }

    /**
     * @param mixed $corporateMemberEmail
     */
    public function setCorporateMemberEmail($corporateMemberEmail)
    {
        $this->corporateMemberEmail = $corporateMemberEmail;
    }

    /**
     * @return mixed
     */
    public function getCorporateEmail()
    {
        return $this->corporateEmail;
    }

    /**
     * @param mixed $corporateEmail
     */
    public function setCorporateEmail($corporateEmail)
    {
        $this->corporateEmail = $corporateEmail;
    }

    public function getDateOfBirthExport()
    {

        /**
         * @var  $dob \DateTime
         */
        $dob =$this->getDateOfBirth();
        if($dob) {
            return $dob->format('Y/m/d');
        }else{
            return '';
        }
    }

    /**
     * @return mixed
     */
    public function getStepDateTime()
    {
        return $this->stepDateTime;
    }

    /**
     * @return mixed
     */
    public function getStepDateTimeAtUTC()
    {
        /**
         * @var $dateObj \DateTime
         */
        $dateObj = $this->stepDateTime;

        if(!$dateObj){
            $dateObj =  new \DateTime();
        }
        return $dateObj->setTimezone(new \DateTimeZone('UTC'));
    }

    /**
     * @param mixed $stepDateTime
     */
    public function setStepDateTime($stepDateTime)
    {
        $this->stepDateTime = $stepDateTime;
    }

    /**
     * @return mixed
     */
    public function getLastRewardSteps()
    {
        return $this->lastRewardSteps;
    }

    /**
     * @return mixed
     */
    public function getLastRewardStepsApi()
    {

        if($this->lastRewardSteps){

            return $this->lastRewardSteps;
        }
        return 0;
    }

    /**
     * @param mixed $lastRewardSteps
     */
    public function setLastRewardSteps($lastRewardSteps)
    {
        $this->lastRewardSteps = $lastRewardSteps;
    }


}
