<?php

namespace App\Gamification\Bundle\Repository;

use App\Application\Sonata\UserBundle\Entity\User;
use Doctrine\Common\Collections\Criteria;

/**
 * ChallengeActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends \Doctrine\ORM\EntityRepository
{

    public function checkActiveChallenge($company)
    {

        $now = new \DateTime();
        $qb = $this->createQueryBuilder('c')
            ->where('c.isActive = :isActive')
            ->andWhere('c.start_date <= :now')
            ->andWhere('c.end_date >= :now')
            ->andWhere('c.company = :company')
            ->setParameter('isActive',true)
            ->setParameter('now',$now)
            ->setParameter('company',$company);
        ;

            $memberChallenge = $qb->getQuery()->getResult();
//            dump($memberChallenge);die;
            if(!empty($memberChallenge)) {
                return $memberChallenge[0];
            }else{

                /*
                 * TODO one active at a time
                 */
                $qbUpdate = $this->createQueryBuilder('c');
                $qbUpdate->update('GamificationBundle:Challenge','c')
                    ->set('c.isActive',':isActive')
                    ->andWhere('c.company = :company')
                    ->setParameter('company',$company)
                    ->setParameter('isActive',false);
                $qbUpdate->getQuery()->execute();
                return null;
            }
    }
    public function getUserChallenges(User $user,$status,$company = null)
    {

        $qb = $this->createQueryBuilder('c');
        $qb
            ->innerJoin('App\Application\Sonata\UserBundle\Entity\User','m','WITH','u.id = mc.member')
            ->innerJoin('App\Gamification\Bundle\Entity\Challenge','c','WITH','c.id = mc.challenge')
            ->where('u.id = :user_id')
            ->andWhere('mc.status = :status')
            ->select('c')
            ->setParameter('user_id',$user->getId())
            ->setParameter('status',$status)
            ->andWhere('c.start_date <= :now')
            ->andWhere('c.isActive = :isActive')
            ->andWhere('c.end_date >= :now')
            ->setParameter('isActive',true)
            ->setParameter('now',new \DateTime())
        ;
        if($company){

            $qb
                ->innerJoin('App\Application\Sonata\UserBundle\Entity\User','company','u.id = ')
                ->andWhere('c.company = :company')
                ->setParameter('company',$company)

            ;
        }
        dump($qb->getQuery()->getResult(),$status,$company);die;

        return $qb->getQuery();
    }
    public function getCorporateChallenges($company)
    {

        $qb = $this->createQueryBuilder('c');
        $qb
            ->where('c.company = :company')
            ->andWhere('c.isActive = :isActive')
            ->andWhere('c.end_date >= :now')
            ->setParameter('isActive',true)
            ->setParameter('now',new \DateTime())
            ->setParameter('company',$company);
        return $qb->getQuery()->getResult();
    }

    public function getValidRecordByCode($code)
    {
        $criteria = new Criteria();
        $criteria->where($criteria->expr()->eq('isDeleted', 0))
            ->andWhere($criteria->expr()->eq('code', $code))
            ->andWhere($criteria->expr()->gt('end_date', new \DateTime()));
        return $this->matching($criteria)->first();
    }

    public function qbFindOwners($user)
    {


            if(in_array('Corporate',$user->getGroups()->toArray())) {
                $qb = $this->createQueryBuilder('c')
                    ->where('c.isActive = :isActive')
                    ->andWhere('c.company = :company')
                    ->andWhere('c.end_date >= :now')
                    ->setParameter('isActive', true)
                    ->setParameter('company', $user)
                    ->setParameter('now',new \DateTime())
                ;
            }elseif(in_array('SubFranchise',$user->getGroups()->toArray())) {

                $qb = $this->createQueryBuilder('c')
                    ->where('c.isActive = :isActive')
                    ->andWhere('c.end_date >= :now')
                    ->setParameter('isActive', true)
                    ->setParameter('now',new \DateTime());

                $qb
                    ->innerJoin('App\Application\Sonata\UserBundle\Entity\User','u','WITH','c.company = u.id')
                    ->andWhere('u.parentUser =:parentUser')
                    ->setParameter('parentUser',$user);
            }else{

            $qb = $this->createQueryBuilder('c')
                ->where('c.isActive = :isActive')
                ->andWhere('c.end_date >= :now')
                ->setParameter('isActive', true)
                ->setParameter('now',new \DateTime())
            ;
        }

            return $qb;
        }

    }
