<?php

namespace App\Gamification\Bundle\Repository;

use App\Application\Sonata\UserBundle\Entity\User;
use App\Gamification\Bundle\Entity\Actions;
use App\Gamification\Bundle\Entity\Challenge;

/**
 * ChallengeActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberActionPointsRepository extends \Doctrine\ORM\EntityRepository
{

    public function validateAction(User $user,Actions $action,$now = null)
    {

        if(!$now){

            $now = new \DateTime();
        }
        $qb = $this->createQueryBuilder('map');
        $qb
            ->where( 'map.member = :member')
            ->andWhere('map.action = :action')
            ->setParameter('member',$user)
            ->setParameter('action',$action);
        $qb
            ->andWhere('DATE(map.actionDate) =DATE(:date)')
            ->setParameter('date',$now);
        return $qb->getQuery()->getResult();
    }

    public function validateCheckIn(User $user,$checkInArray , $now = null)
    {

        if(!$now){

            $now = new \DateTime();
        }

        $qb = $this->createQueryBuilder('map');
        $qb
            ->innerJoin('App\Gamification\Bundle\Entity\Actions','a','WITH','a.id = map.action')
            ->where( 'map.member = :member')
            ->andWhere('a.code IN (:action)')
            ->setParameter('member',$user)
            ->setParameter('action',$checkInArray);
        $qb
            ->andWhere('DATE(map.actionDate) =DATE(:date)')
            ->setParameter('date',$now);

        return $qb->getQuery()->getResult();
    }

    public function getUserPoints(Challenge $challenge = null,User $user = null,$status = 'Confirmed')
    {

        $qb = $this->baseQueryUserChallenge($challenge,$status);
        $qb
            ->andWhere('u.id =:user_id')
            ->setParameter('user_id',$user->getId())
        ;

        try {
            return $qb->getQuery()->getSingleScalarResult();
        }catch (\Exception $exception){
            return 0;
        }
    }

    public function getUserRank(Challenge $challenge = null,User $user = null,$status = 'Confirmed')
    {

        $imagePath = '/image/member/';
        $qb = $this->baseQueryUserChallenge($challenge,$status);
        $qb

            ->andWhere('u.id =:user_id')
            ->select('u.id id','sum(a.value) as total_points','u.username username','CONCAT(\''.$imagePath.'\',u.companyLogo) image_url')
            ->setParameter('user_id',$user->getId())
        ;

        try {
            return $qb->getQuery()->getSingleResult();
        }catch (\Exception $exception){
            return 0;
        }
    }

    public function baseQueryUserChallenge(Challenge $challenge = null,$status = 'Confirmed')
    {
        $qb = $this->createQueryBuilder('map')
            ->select('sum(a.value) as total_points')
            ->innerJoin('App\Application\Sonata\UserBundle\Entity\User','u','WITH','u.id = map.member')
            ->innerJoin('App\Gamification\Bundle\Entity\ChallengeAction','ca','WITH','ca.member_action_points = map.id')
            ->innerJoin('App\Gamification\Bundle\Entity\Actions','a','WITH','a.id = map.action')
            ->innerJoin('App\Gamification\Bundle\Entity\Challenge','c','WITH','c.id = ca.challenge')
            ->innerJoin('App\Gamification\Bundle\Entity\MemberChallenge','mc','WITH','c.id = mc.challenge')
        ;
        $qb
//
//            ->andWhere('c.isActive =:isActive')
            ->andWhere('mc.status = :status')
//            ->setParameter('isActive',true)
            ->setParameter('status',$status)
        ;
        if($challenge) {
            $qb
                ->andWhere('c.id =:challenge_id')
                ->setParameter('challenge_id', $challenge->getId());
        }
        return $qb;
    }

    public function getUsersRank(Challenge $challenge = null,User $user = null,$status = 'Confirmed')
    {

        $qb = $this->baseQueryUserChallenge($challenge,$status);
        $qb
            ->select('sum(a.value) as total_points','u.id as id')
            ->addGroupBy('id')
            ->addOrderBy('total_points','DESC')
        ;
        $positions = $qb->getQuery()->getResult();

        if(empty($positions)){

            return array(0,0);
        }else{

            $userPosition = array_search($user->getId(),array_column($positions,'id'));
            $userRank = 0;
            if($userPosition){

                $userRank = $userPosition +1;
            }
            return array($userRank , count($positions));
        }
    }

    public function getUserLeaderBoard(Challenge $challenge = null,User $user = null,$self = false,$status = 'Confirmed')
    {

        $imagePath = '/image/member/';
        $qb = $this->baseQueryUserChallenge($challenge,$status);
        $qb
            ->select('sum(a.value) as total_points','u.id as id','CONCAT(u.firstname,\' \',u.lastname) name','CONCAT(\''.$imagePath.'\',u.companyLogo) image_url')
            ->addGroupBy('id')
            ->addOrderBy('total_points','DESC')
        ;



        $positions = $qb->getQuery()->getResult();
        $responseArr = array();
        $loggedinUserObject = array();
        foreach ($positions as $key =>$position){

            if($position['id'] == $user->getId()){

                $loggedinUserObject = array(
                    'total_points'=>(int)$position['total_points'],
                    'id'=>(int)$position['id'],
                    'name'=>$position['name'],
                    'rank'=>$key+1,
                    'batch_icon'=>'/challenge/icons/your_rank_cup.png',
                    'image_url'=>$position['image_url'],
                );
            }else {
                $responseArr[] = array(
                    'total_points' => (int)$position['total_points'],
                    'id' => (int)$position['id'],
                    'name' => $position['name'],
                    'rank' => $key + 1,
                    'batch_icon'=> $this->getBatchIcon($key),
                    'image_url' => $position['image_url'],
                );
            }
        }
        if(empty($loggedinUserObject)){

            $loggedinUserObject = array(
                    "total_points"=> 0,
                    "id"=> $user->getId(),
                    "rank"=>0,
                    "name"=> $user->getFullname() !== " "? $user->getFullname(): $user->getUsername(),
                    'batch_icon'=>'/challenge/icons/your_rank_cup.png',
                    "image_url"=> $user->getCompanyLogo()
                );
        }
        return array($responseArr,$loggedinUserObject);
    }

    public function getBatchIcon($key)
    {
        switch ($key){
            case 0:
                return '/challenge/icons/first_rank.png';
                break;
            case 1:
                return '/challenge/icons/second_rank.png';
                break;
            case 2:
                return '/challenge/icons/third_rank.png';
                break;
            default:
                return '/challenge/icons/normal_rank.png';
                break;
        }

    }

    public function getUserChallengeDetailExport(Challenge $challenge = null,User $user,$code,$status = 'Confirmed')
    {
        $qb = $this->baseQueryUserChallenge($challenge,$status);

        $qb
            ->andWhere('u.id = :user_id')
            ->setParameter('user_id',$user->getId())
            ->addGroupBy('map.id')
            ->select('u.id member_id','map.id','map.actionDate','a.code');

        switch ($code) {
            case 'checkIn':
                {

                    $code = array('MANUAL_ACTIVITY_CHECKIN','CHECKIN','NON_PARTNER_CHECKIN');
                    $qb
                        ->andWhere('a.code IN (:code)')
                        ->setParameter('code', $code);
                    break;
                }
            default:{
                $qb
                    ->andWhere('a.code = :code')
                    ->setParameter('code', $code);
                break;
            }

        }


        $actionByDate =  $qb->getQuery()->getResult();
        return $actionByDate;
//        return $this->getAllAction($actionByDate);
    }

    public function getUserChallengeDetailDashboard(Challenge $challenge = null,User $user,$status = 'Confirmed')
    {
        $qb = $this->baseQueryUserChallenge($challenge,$status);

        $qb
            ->andWhere('u.id = :user_id')
            ->setParameter('user_id',$user->getId())
//            ->addGroupBy('map.actionDate')
            ->addGroupBy('map.id')
            ->select('u.id member_id','map.id','map.actionDate','a.code');

        $actionByDate =  $qb->getQuery()->getResult();


        return $this->getAllAction($actionByDate);
    }

    public function getAllAction($actionByDate)
    {

        $checkoutCount= 0;
        $articleCount= 0;
        $workoutCount= 0;
        foreach ($actionByDate as $value){

            switch ($value['code']) {
                case 'WORKOUT':
                    $workoutCount++;
                    break;
                case 'ARTICLE':
                    $articleCount++;
                    break;
                default:
                    $checkoutCount++;
            }

        }

        return array($checkoutCount,$articleCount,$workoutCount);

    }
    public function getUserChallengeDetail(Challenge $challenge = null,User $user,$status = 'Confirmed')
    {
        $qb = $this->baseQueryUserChallenge($challenge,$status);

        $qb
            ->andWhere('u.id = :user_id')
            ->setParameter('user_id',$user->getId())
//            ->addGroupBy('map.actionDate')
            ->addGroupBy('map.id')
            ->select('u.id member_id','map.id','map.actionDate','a.code');

        $actionByDate =  $qb->getQuery()->getResult();
        return $this->getAllActionByDate($actionByDate,$challenge);
    }

    public function getAllActionByDate($actionByDates,Challenge $challenge = null)
    {

        $period = new \DatePeriod(
            $challenge->getStartDate(),
            new \DateInterval('P1D'),
            $challenge->getEndDate()
        );
        $dateArr = array();
        $workoutCount = 0;
        $articleCount = 0;
        $checkinCount = 0;
        foreach ($period as $key=>$value){

            $checkIn = $this->getActionByDate($actionByDates,'checkin',$value);
            $workOut = $this->getActionByDate($actionByDates,'workout',$value);
            $article = $this->getActionByDate($actionByDates,'article',$value);

            $imageUrl = '/challenge/icons/full_empty.png';
            if($checkIn && $workOut && $article){

                $checkinCount++;
                $articleCount++;
                $workoutCount++;
                $imageUrl = '/challenge/icons/complete.png';
            }elseif (!$checkIn && $workOut && $article){

                $articleCount++;
                $workoutCount++;
                $imageUrl = '/challenge/icons/article_workout.png';

            }elseif ($checkIn && !$workOut && $article){

                $checkinCount++;
                $articleCount++;
                $imageUrl = '/challenge/icons/article_checkin.png';

            }elseif ($checkIn && $workOut && !$article){

                $checkinCount++;
                $workoutCount++;
                $imageUrl = '/challenge/icons/checkin_workout.png';

            }elseif ($checkIn && !$workOut && !$article){

                $checkinCount++;
                $imageUrl = '/challenge/icons/checkin.png';

            }elseif (!$checkIn && !$workOut && $article){
                $articleCount++;
                $imageUrl = '/challenge/icons/article.png';

            }elseif (!$checkIn && $workOut && !$article){

                $workoutCount++;
                $imageUrl = '/challenge/icons/workout.png';

            }
            $now = new \DateTime();

            $dateArr[] = array(
                'image_url'=>$imageUrl,
                'is_today'=>$value->format('Y-m-d') == $now->format('Y-m-d') ? true:false,
                'date'=>strtoupper($value->format('Y-m-d') == $now->format('Y-m-d') ? 'Today, '. $value->format('d F Y'):''. $value->format('j F Y'))
            );

        }

        $countArray = array(

            "check_in_count"=>$checkinCount,
            "workout_count"=>$workoutCount,
            "article_count"=>$articleCount
        );
        return array($dateArr,$countArray);
    }

    public function getActionByDate($actionByPoint,$actionType,$value)
    {


        foreach ($actionByPoint as $action){
            $diff=date_diff($value,$action['actionDate']);
            $diff_days = $diff->format("%a");
            if($diff_days == 0){

                if($actionType == 'checkin') {

                    if(in_array($action['code'],array('MANUAL_ACTIVITY_CHECKIN','CHECKIN','NON_PARTNER_CHECKIN','STEPS_AWARD'))){
                        return true;
                    }
                }

                if ($action['code'] == strtoupper($actionType)) {
                    return true;
                }
            }
        }
        return false;
    }

}
