#!/bin/bash
cd /home/devengagement/public_html
chmod -R 775 ../public_html/
chown -R devengagement:apache ../public_html/
git clone git@git.assembla.com:rebeltech/messaging.2.git .
git checkout -b development --track origin/development
mkdir -m 777 bootstrap/cache storage/framework/sessions # This directory is needed by framework to be writable

# Install composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --filename=composer.phar
php -r "unlink('composer-setup.php');"

composer.phar install
cp .env.example .env
chmod -R 777 storage bootstrap/cache

php artisan cache:clear
php artisan config:cache