apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: "MYSQL_USER"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: "MYSQL_DATABASE"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-db
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlvolume
  volumes:
    - name: mysqlvolume
      hostPath:
        path: /tmp/data/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  #type: NodePort
  selector:
    name: mysql-pod
  ports:
    - protocol: TCP
      port: 3306   
      targetPort: 3306 
      #nodePort: 30100 