doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            json: Sonata\Doctrine\Types\JsonType
        mapping_types:
            enum: string
            set: string
            varbinary: string
            tinyblob: text
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    GamificationBundle: ~
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        MINUTE: DoctrineExtensions\Query\Mysql\Minute
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        Day: DoctrineExtensions\Query\Mysql\Day
                        date_format: DoctrineExtensions\Query\Mysql\DateFormat
                        DATE: DoctrineExtensions\Query\Mysql\Date
                    string_functions:
                        cast: DoctrineExtensions\Query\Mysql\Cast

        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

