const FosUserUserModel = [{
    "id": 1,
    "parent_id": 1,
    "username": "cliff",
    "username_canonical": "cliff",
    "email": "clifford@coredirection.com",
    "email_canonical": "clifford@coredirection.com",
    "enabled": 1,
    "salt": "2d2BdpYr50HmLWzTEFdoflj3ZIPgHKj7.13cvm5..HI",
    "password": "$2b$10$K0XTPzrb2SGv2v9/7.DR7eX/lOy6rKI.mO2lFKK6rNUUzAuFDohau",
    "last_login": "2021-05-19 06:50:11",
    "locked": 0,
    "expired": 0,
    "expires_at": "",
    "confirmation_token": "ZGV2ZWxvcG1lbnRAY29yZWRpcmVjdGlvbi5jb207OzM0YzYxMjJmLTkyZWUtNGY4Zi05MjQ4LTdjMDAwMzA0Y2Y3YTs7U2F0IE1heSAyOSAyMDIxIDEzOjQ2OjMzIEdNVCswNTAwIChQYWtpc3RhbiBTdGFuZGFyZCBUaW1lKQ==",
    "password_requested_at": "2021-03-31 13:04:28",
    "roles": "a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}",
    "credentials_expired": 0,
    "credentials_expire_at": "",
    "created_at": "2017-04-12 16:39:25",
    "updated_at": "2021-05-23 10:17:34",
    "date_of_birth": "1985-06-04 00:00:00",
    "firstname": "Clifford",
    "lastname": "Tindell",
    "website": "http://www.coredirection.com",
    "biography": "",
    "gender": "m",
    "locale": "zu_ZA",
    "timezone": "Asia/Dubai",
    "phone": "",
    "facebook_uid": "",
    "facebook_name": "",
    "facebook_data": "null",
    "twitter_uid": "",
    "twitter_name": "",
    "twitter_data": "null",
    "gplus_uid": "",
    "gplus_name": "",
    "gplus_data": "null",
    "token": "1ab4dd85-244e-40dd-954b-05d8f62f88c1",
    "two_step_code": "",
    "address": "Street 233, Maadi as Sarayat Al Gharbeyah, Al Maadi, Cairo Governorate, Egypt",
    "address_one": "Jumaira",
    "address_two": "",
    "po_box": "5422",
    "city": "Dubai",
    "country": "",
    "contact_title": "Mr.",
    "contact_firstname": "",
    "contact_lastname": "",
    "designation": "",
    "contact_email": "",
    "contact_no": "",
    "contact_url": "",
    "notes": "",
    "company_logo": "5ebd307bd7820975523015.png",
    "company_name": "Core Direction",
    "latitude": "29.9590754",
    "longitude": "31.27838280000003",
    "card_id": "",
    "notification": 1,
    "is_gdpr": 1,
    "appVersion_id": 26,
    "enable_discount": 0,
    "step_count": 0,
    "distance": 0.0,
    "step_date_time": "",
    "last_reward_steps": 0,
    "is_deleted": 0,
    "apple_id": "",
    "company_banner": "",
    "term_condition": "",
    "about_corporate": ""
}, {
    "id": 11,
    "parent_id": 17,
    "username": "lululemon_UAE",
    "username_canonical": "lululemon_uae",
    "email": "lululemon@maf.co.ae",
    "email_canonical": "lululemon@maf.co.ae",
    "enabled": 1,
    "salt": "hb48ghjr7jcoc8w0o4ssg8848oo844w",
    "password": "K6a+DrS0/JFQ7lQaUKke7i2Hy4imdIvMSUDgKVe2SYJbzHh3U4Ww2E5YCjNUd8V0IbR/0YtwRK8HXYI8Xs+xuQ==",
    "last_login": "2018-10-14 16:15:50",
    "locked": 0,
    "expired": 0,
    "expires_at": "",
    "confirmation_token": "bHVsdWxlbW9uQG1hZi5jby5hZTs7c29tZS11dWlkOztXZWQgTWF5IDI5IDMwMjIgMDA6MDA6MDAgR01UKzA1MDAgKFBha2lzdGFuIFN0YW5kYXJkIFRpbWUp", //token will expire on year 3022
    "password_requested_at": "",
    "roles": "a:0:{}",
    "credentials_expired": 0,
    "credentials_expire_at": "",
    "created_at": "2017-04-12 18:33:22",
    "updated_at": "2019-01-31 16:18:00",
    "date_of_birth": "2018-01-01 00:00:00",
    "firstname": "lululemon",
    "lastname": "",
    "website": "https://www.eu.lululemon.com/?locale=en_IE&sl=AE",
    "biography": "Any moment. Any weather.\r\nWhen you're on the go from one place to the next, our outerwear keeps you covered.",
    "gender": "f",
    "locale": "en",
    "timezone": "Asia/Dubai",
    "phone": "0097143474651",
    "facebook_uid": "",
    "facebook_name": "",
    "facebook_data": "null",
    "twitter_uid": "",
    "twitter_name": "",
    "twitter_data": "null",
    "gplus_uid": "",
    "gplus_name": "",
    "gplus_data": "null",
    "token": "f57358889c821c00e8b3c1efb9c2cab2",
    "two_step_code": "",
    "address": "Unnamed Road - Dubai - United Arab Emirates",
    "address_one": "123 Street",
    "address_two": "",
    "po_box": "57000",
    "city": "Dubai",
    "country": "AE",
    "contact_title": "Mrs.",
    "contact_firstname": "Christine",
    "contact_lastname": "Zanon",
    "designation": "Consultant",
    "contact_email": "Christine.Zanon@maf.co.ae",
    "contact_no": "971562264843",
    "contact_url": "",
    "notes": "",
    "company_logo": "5bb5a30841a29.png",
    "company_name": "lululemon",
    "latitude": "25.118107",
    "longitude": "55.200608",
    "card_id": "",
    "notification": 0,
    "is_gdpr": 0,
    "appVersion_id": 0,
    "enable_discount": 0,
    "step_count": 0,
    "distance": 0.0,
    "step_date_time": "",
    "last_reward_steps": 0,
    "is_deleted": 0,
    "apple_id": "",
    "company_banner": "",
    "term_condition": "",
    "about_corporate": ""
}];

module.exports = FosUserUserModel;