<?php

namespace App\Application\Sonata\UserBundle\Repository;

use App\Repository\BaseRepository;

/**
 * ActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends BaseRepository
{

   
}
