<?php

namespace App\Application\Sonata\UserBundle\Repository;

use App\Repository\BaseRepository;
use App\Application\Sonata\UserBundle\Entity\User;
use App\Entity\MemberDeviceToken;
use App\Entity\Package;
use App\Gamification\Bundle\Entity\Challenge;
use App\Coredirection\Common\Shared;

/**
 * ActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    public function getMemberCountWhoEnrolledInClass($userId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('u')
            ->from('App\Entity\MemberScheduleActivity', 'u')
            ->innerJoin('u.member', 'm')
            ->innerJoin('u.scheduleDetail', 'd')
            ->innerJoin('d.schedule', 's')
            ->where('s.facility IN  ( :facility ) ')
            ->setParameter("facility", $userId)
            ->groupBy('u.member');
        $results = $query->getQuery()->getResult();
        $msaIds = array();
        foreach ($results as $result) {
            $msaIds[] = $result->getId();
        }
        $msaIds = array_unique($msaIds);
        $query = $em->createQueryBuilder()
            ->select('count(msa.id)')
            ->from('App\Entity\MemberScheduleActivity', 'msa')
            ->where('msa.isDeleted = :status')
            ->andWhere('msa.id IN ( :ids )')
            ->setParameter('status', 0)
            ->setParameter('ids', $msaIds);
        return $query->getQuery()->getSingleScalarResult();
    }
    public function getRegisteredUsersList($timeperiod)
    {
        $start = $end = "";
        if ($timeperiod == "1") {
            $start = date('Y-m-d', strtotime('Monday last week'));
            $end = date('Y-m-d', strtotime('Sunday last week'));
        } elseif ($timeperiod == "2") {
            $last_month = date('m', strtotime('last month'));
            $last_year_month = date('Y-m', strtotime('last month'));
            $end_months = array('01', '03', '05', '07', '08', '10', '12');
            if (in_array($last_month, $end_months)) {
                $month_end = '31';
            } else {
                $month_end = '30';
            }
            $start = $last_year_month . '-01';
            $end = $last_year_month . '-' . $month_end;
        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));
        }
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select("count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,'%Y-%b') as created_at")
            ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('u.enabled = 1')
            ->andWhere('g.code = :code')
            ->setParameter('code', 'Member')
            ->groupBy('u.createdAt');;
        if ($timeperiod) {
            $query->andWhere("DATE_FORMAT(u.createdAt,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);

        }
        return $query->getQuery()->getResult();
    }
    public function getPendingApprovalCount($username)
    {
        $countQuery = "SELECT 
                            COUNT(A.id) as total
                       FROM 
                            fos_user_user A 
                       INNER JOIN fos_user_user_group B ON A.id = B.user_id
                       INNER JOIN fos_user_group C ON B.group_id = C.id
                            
                       WHERE C.code = 'Member' 
                       AND A.enabled = 1
                       AND A.id NOT IN ( 
                            SELECT 
                            A.member_id           
                            FROM       
                            member_key A 
                            INNER JOIN corporate_key B  on A.key_id =B.id  
                            INNER  JOIN
                            (
                            SELECT C.id AS franchise_id from fos_user_group A
                            INNER JOIN fos_user_user_group B  on B.group_id =A.id 
                            INNER JOIN fos_user_user C  on B.user_id =C.id 
                            WHERE A.code='MasterFranchise'
                            ) AB ON AB.franchise_id = B.corporate_id
                            WHERE 
                            B.type='Default' 
                            AND B.is_active = true  
                            )";

        if ($username) {
            $countQuery .= " AND A.company_name like '%$username%'";
        }
        //$countQuery .= " GROUP BY A.id ";

        return $countQuery;

    }
    public function getPendingApproval($username, $sortby, $sortOrder, $offset, $limit)
    {

        $dql = "SELECT 
                            A.id as id,
                            A.username,
                            A.email,
                            A.company_name,
                            company_logo
                       FROM 
                            fos_user_user A 
                       INNER JOIN fos_user_user_group B ON A.id = B.user_id
                       INNER JOIN fos_user_group C ON B.group_id = C.id
                            
                       WHERE C.code = 'Member' 
                       AND A.enabled = 1
                       AND A.id NOT IN ( 
                                SELECT 
                                A.member_id           
                                FROM       
                                member_key A 
                                INNER JOIN corporate_key B  on A.key_id =B.id  
                                INNER  JOIN
                                (
                                SELECT C.id AS franchise_id from fos_user_group A
                                INNER JOIN fos_user_user_group B  on B.group_id =A.id 
                                INNER JOIN fos_user_user C  on B.user_id =C.id 
                                WHERE A.code='MasterFranchise'
                                ) AB ON AB.franchise_id = B.corporate_id
                                WHERE 
                                B.type='Default' 
                                AND B.is_active = true                             
                                     ) 
                                  ";
        if ($username) {
            $dql .= " AND A.username like '%$username%' ";
        }
        //$dql .= "GROUP BY A.id  ";
        $dql .= "ORDER BY $sortby $sortOrder";
        if ($limit) {
            $dql .= " limit $offset , $limit ";
        }

        return $dql;
    }
    public function getUserMasterFranchise($UserId)
    {
        $objUser = $this->getEntityManager()->getRepository("App\\Application\\Sonata\\UserBundle\\Entity\\User")->findOneBy(array('id' => $UserId, 'enabled' => 1));
        $MasterFranchiseId = 0;
        if(!empty($objUser) ){
                foreach ($objUser->getparentUser()->getGroups() as $group) {
                    switch ($group->getCode()) {
                        case Shared::$FRANCHISE_TYPE:
                            $MasterFranchiseId = $objUser->getparentUser()->getId();
                            break;
                        default:
                            break;
                    }

            }

        }


        if ($MasterFranchiseId == 0) {
            if(!empty($objUser) )
            return $this->getUserMasterFranchise($objUser->getparentUser()->getId());
        } else {
            return $MasterFranchiseId;
        }
    }
    public function getClassEnrollUserList($userId, $timeperiod)
    {

        $start = $end = "";

        if ($timeperiod == "1") {
//            $start = date('Y-m-d', strtotime('Monday last week'));
//            $end = date('Y-m-d', strtotime('Sunday last week'));
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');

        } elseif ($timeperiod == "2") {
            $last_month = date('m', strtotime('last month'));
            $last_year_month = date('Y-m', strtotime('last month'));
            $end_months = array('01', '03', '05', '07', '08', '10', '12');
            if (in_array($last_month, $end_months)) {
                $month_end = '31';
            } else {
                $month_end = '30';
            }

            $start = $last_year_month . '-01';
            $end = $last_year_month . '-' . $month_end;

        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

        }

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('count(u.member) as no_of_users, DATE_FORMAT(u.createdDate,\'%Y-%b\') as created_at')
            ->from('App\Entity\MemberScheduleActivity', 'u')
            ->innerJoin('u.member', 'm')
            ->innerJoin('u.scheduleDetail', 'd')
            ->innerJoin('d.schedule', 's')
            ->where('s.facility IN  ( :facility ) ')
            ->setParameter("facility", $userId)//->groupBy('u.member')
        ;

        if ($timeperiod) {
            $query->andWhere("DATE_FORMAT(u.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);
        }

        return $query->getQuery()->getResult();
    }
    public function getAllSystemUsers()
    {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%b\') as created_at')
            ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('u.enabled  = 1 ')
            ->andWhere('g.code  = :code ')
            ->setParameter('code', 'member')
            ->groupBy('created_at');

        return $query->getQuery()->getResult();
    }
    public function getAllNewUsers($timeperiod)
    {
        $start = $end = "";
        if ($timeperiod == "1") {
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');
        } elseif ($timeperiod == "2") {
            $last_month = date('m', strtotime('last month'));
            $last_year_month = date('Y-m', strtotime('last month'));
            $end_months = array('01', '03', '05', '07', '08', '10', '12');
            if (in_array($last_month, $end_months)) {
                $month_end = '31';
            } else {
                $month_end = '30';
            }
            $start = $last_year_month . '-01';
            $end = $last_year_month . '-' . $month_end;
        } else {
            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

        }
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%b\') as created_at')
            ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('u.enabled  = 1 ')
            ->andWhere('g.code  = :code ')
            ->setParameter('code', 'member')
            ->groupBy('created_at');
        if ($timeperiod) {
            $query->andWhere("DATE_FORMAT(u.createdAt,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);
        }
        return $query->getQuery()->getResult();
    }
    public function getUsersForDashboardMemberChart($timeperiod, $userGroup, $childs = array())
    {

        $start = $end = "";
        if ($timeperiod == "1") {
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');

        } elseif ($timeperiod == "2") {
            $start = date('Y-m-d', strtotime('-30 days'));
            $end = date('Y-m-d');

        } elseif ($timeperiod == "today") {
            $start = date('Y-m-d');
            $end = date('Y-m-d');
//            dump($start,$end);die;
        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

        }


        $em = $this->getEntityManager();
        if ($userGroup == 'HQ-Admin') {
            if($timeperiod == 1 || $timeperiod == 2 || $timeperiod == 'today' ){
//                die('sdssds');
                $query = $em->createQueryBuilder('u')
                    ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%M-%d\') as created_at')
                    ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
                    ->join('u.groups', 'g')
                    ->where('u.enabled  = 1 ')
                    ->andWhere('g.code = :code')
                    ->setParameter('code', 'Member')
                    ->orderBy('u.createdAt', 'ASC')
                    ->groupBy('created_at');

            }else{
                $query = $em->createQueryBuilder('u')
                    ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%M\') as created_at')
                    ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
                    ->join('u.groups', 'g')
                    ->where('u.enabled  = 1 ')
                    ->andWhere('g.code = :code')
                    ->setParameter('code', 'Member')
                    ->orderBy('u.createdAt', 'ASC')
                    ->groupBy('created_at');

            }


        } elseif ($userGroup == 'MasterFranchise' || $userGroup == 'SubFranchise') {

            $query = $em->createQueryBuilder('msa')
                ->select('count(msa.id) as no_of_users, DATE_FORMAT(msa.createdDate,\'%Y-%M-%d\') as created_at')
                ->from('App\Entity\MemberScheduleActivity', 'msa')
                ->innerJoin('msa.member', 'u')
                ->innerJoin('msa.scheduleDetail', 'd')
                ->innerJoin('d.schedule', 's')
                ->where('s.facility IN  ( :facility ) ')
                ->setParameter("facility", $childs);

            if ($timeperiod) {
                $query->andWhere("DATE_FORMAT(msa.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
                    ->setParameter('start', $start)
                    ->setParameter('end', $end);
            }
            $query->groupBy('created_at');

            return $query->getQuery()->getResult();

        } elseif ($userGroup == 'SuperFranchise' || $userGroup == 'Facility') {
            $em = $this->getEntityManager();
            $connection = $em->getConnection();
            if($timeperiod == 1 || $timeperiod == 2 ||$timeperiod == 'today'){


                $statement = $connection->prepare("SELECT  COUNT(member_id) no_of_users,DATE_FORMAT(created_date, '%Y-%M-%d') created_at
                    FROM
                     (
                      SELECT  member_id,DATE_FORMAT(created_date, '%Y-%m-%d') created_date
                      FROM 
                      (
                      SELECT  m0_.member_id ,DATE_FORMAT(m0_.created_date, '%Y-%m-%d') created_date   
                      FROM member_schedule_activity m0_
                      INNER JOIN schedule_detail s2_ ON m0_.schedule_detail_id = s2_.id
                      INNER JOIN activity_schedule a3_ ON s2_.schedule_id = a3_.id
                      WHERE a3_.facility_id IN (:facilities)
                      AND (DATE_FORMAT(m0_.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end' )  
                     ) uniq 
                     GROUP BY member_id 
                    
                    ) redun
                    GROUP BY created_date");
            }else{
                $statement = $connection->prepare("SELECT  COUNT(member_id) no_of_users,DATE_FORMAT(created_date, '%Y-%M') created_at
                    FROM
                     (
                      SELECT  member_id,DATE_FORMAT(created_date, '%Y-%m-%d') created_date
                      FROM 
                      (
                      SELECT  m0_.member_id ,DATE_FORMAT(m0_.created_date, '%Y-%m-%d') created_date   
                      FROM member_schedule_activity m0_
                      INNER JOIN schedule_detail s2_ ON m0_.schedule_detail_id = s2_.id
                      INNER JOIN activity_schedule a3_ ON s2_.schedule_id = a3_.id
                      WHERE a3_.facility_id IN (:facilities)
                      AND (DATE_FORMAT(m0_.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end' )   
                     ) uniq 
                     GROUP BY member_id 
                     
                    ) redun
                    GROUP BY  month(created_date);");
            }
            $childs = implode(",",$childs);
            $statement->bindValue('facilities', $childs);
//            $statement->bindValue('startDate', $start);
//            $statement->bindValue('endDate', $end);
            $statement->execute();
            $results = $statement->fetchAll();
            return $results;

        }


        if ($timeperiod) {
            $query->andWhere("DATE_FORMAT(u.createdAt,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);
        }
        return $query->getQuery()->getResult();
    }
	public function getUsersForDashboardMemberChartMonthView($timeperiod, $userGroup, $childs = array())
	{

		$start = $end = "";
//        dump($timeperiod);exit;
		if ($timeperiod == "1") {
			$start = date('Y-m-d', strtotime('-7 days'));
			$end = date('Y-m-d');

		}
		elseif ($timeperiod == "2") {
            $start = date('Y-m-d', strtotime('-30 days'));
            $end = date('Y-m-d');
		}
		elseif ($timeperiod == "today") {
			$start =date('Y-m-d', strtotime('-1 days'));
			$end = date('Y-m-d', strtotime('+1 days'));
//            dump($start,$end);die;
		} else {

			$interval = $timeperiod;
			$end = date('Y-m-d');
			$start = date('Y-m-d', strtotime("-" . $interval . " month"));

		}


		$em = $this->getEntityManager();
		if ($userGroup == 'HQ-Admin') {
//            die($timeperiod);
			$query = $em->createQueryBuilder('u')
			            ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%m-%d\') as created_at')
			            ->from('ApplicationSonataUserBundle:User', 'u')
			            ->join('u.groups', 'g')
			            ->where('u.enabled  = 1 ')
			            ->andWhere('g.code = :code')
			            ->setParameter('code', 'Member')
			            ->orderBy('u.createdAt', 'ASC')
			            ->groupBy('created_at');
//            echo $query->getQuery()->getSQL(); exit;


		} elseif ($userGroup == 'MasterFranchise' || $userGroup == 'SubFranchise') {

			$query = $em->createQueryBuilder('msa')
			            ->select('count(msa.id) as no_of_users, DATE_FORMAT(msa.createdDate,\'%Y-%M\') as created_at')
			            ->from('CoredirectionBundle:MemberScheduleActivity', 'msa')
			            ->innerJoin('msa.member', 'u')
			            ->innerJoin('msa.scheduleDetail', 'd')
			            ->innerJoin('d.schedule', 's')
			            ->where('s.facility IN  ( :facility ) ')
			            ->setParameter("facility", $childs);

			if ($timeperiod) {
				$query->andWhere("DATE_FORMAT(msa.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
				      ->setParameter('start', $start)
				      ->setParameter('end', $end);
			}
			$query->groupBy('created_at');

			return $query->getQuery()->getResult();

		}

		elseif ($userGroup == 'SuperFranchise' || $userGroup == 'Facility') {
            $em = $this->getEntityManager();
            $connection = $em->getConnection();
            if($timeperiod == 1 || $timeperiod == 2 || $timeperiod == 'today'){

                $statement = $connection->prepare("SELECT count(DISTINCT (m0_.member_id)) AS no_of_users, DATE_FORMAT(m0_.created_date, '%Y-%M') AS created_at
                    FROM member_schedule_activity m0_
                    INNER JOIN fos_user_user f1_ ON m0_.member_id = f1_.id
                    INNER JOIN schedule_detail s2_ ON m0_.schedule_detail_id = s2_.id
                    INNER JOIN activity_schedule a3_ ON s2_.schedule_id = a3_.id
                    WHERE a3_.facility_id IN (:facilities)
                    AND (DATE_FORMAT(m0_.created_date, '%Y-%m-%d')
                     BETWEEN ".$start." AND ".$end.") GROUP BY created_at;
");
            }else{
                $statement = $connection->prepare("SELECT count(DISTINCT (m0_.member_id)) AS no_of_users, DATE_FORMAT(m0_.created_date, '%Y-%M') AS created_at
                    FROM member_schedule_activity m0_
                    INNER JOIN fos_user_user f1_ ON m0_.member_id = f1_.id
                    INNER JOIN schedule_detail s2_ ON m0_.schedule_detail_id = s2_.id
                    INNER JOIN activity_schedule a3_ ON s2_.schedule_id = a3_.id
                    WHERE a3_.facility_id IN (:facilities)
                    AND (DATE_FORMAT(m0_.created_date, '%Y-%m-%d')
                     BETWEEN ".$start." AND ".$end.") GROUP BY created_at;");
            }
            $childs = implode(",",$childs);
            $statement->bindValue('facilities', $childs);
            $statement->execute();
            $results = $statement->fetch();
            return $results;

		}


		if ($timeperiod) {
			$query->andWhere("DATE_FORMAT(u.createdAt,'%Y-%m-%d') BETWEEN :start and :end")
			      ->setParameter('start', $start)
			      ->setParameter('end', $end);
		}
		return $query->getQuery()->getResult();
	}
    public function countUserforDashboardByRole($childIds, $role)
    {


        $em = $this->getEntityManager();
        if ($role == 'HQ-Admin' || $role == 'MasterFranchise') {
            $query = $em->createQueryBuilder('u')
                ->select('count(u.id)')
                ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
                ->join('u.groups', 'g')
                ->where('u.enabled  = 1 ')
                ->andWhere('g.code = :code')
                ->setParameter('code', 'Member');
//            echo $query->getQuery()->getSQL(); exit;


        } elseif ($role == 'SubFranchise') {
            $query = $em->createQueryBuilder('msa')
                ->select('count(msa.id)')
                ->from('App\Entity\MemberScheduleActivity', 'msa')
                ->join('msa.member', 'member')
                ->join('member.groups', 'g')
                ->join('msa.scheduleDetail', 'sd')
                ->join('sd.schedule', 's')
                ->where('s.facility  IN ( :facilityIds )')
                ->andWhere('g.code = :code')
                ->setParameter('code', 'Member')
                ->setParameter('facilityIds', $childIds);

//            $query = $em->createQueryBuilder('u')
//                ->select('count(u.id)')
//                ->from('ApplicationSonataUserBundle:User', 'u')
//                ->join('u.groups', 'g')
//                ->where('u.enabled  = 1 ')
//                ->andWhere('g.code = :code')
//                ->setParameter('code', 'Member');

        } elseif ($role == 'SuperFranchise' || $role == 'Facility') {

            $query = $em->createQueryBuilder('msa')
                ->select('count(DISTINCT(msa.member))')
                ->from('App\Entity\MemberScheduleActivity', 'msa')
                ->join('msa.scheduleDetail', 'sd')
                ->join('sd.schedule', 's')
                ->where('s.facility  IN ( :facilityIds )')
                ->setParameter('facilityIds', $childIds);


        }


        return $query->getQuery()->getSingleScalarResult();
    }
    public function countUserforDashboarChartdByRole($childIds, $role,$deviceType,$startDate = null,$endDate = null)
    {


//        $em = $this->getEntityManager();
        if ($role == 'HQ-Admin' || $role == 'MasterFranchise') {
            $query = $this->createQueryBuilder('u')
                ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%M\') as created_at')
	            ->innerJoin('App\Entity\MemberDeviceToken','mdt', 'WITH', 'u.id = mdt.user')
                ->join('u.groups', 'g')
                ->where('u.enabled  = 1 ')
                ->andWhere('g.code = :code')
	            ->andWhere('mdt.deviceType = :deviceType')
                ->groupBy('u.createdAt')
	            ->setParameter('deviceType',$deviceType)
	            ->setParameter('code', 'Member');

            if($startDate && $endDate) {
	            if ( $startDate == $endDate ) {

		            $query
			            ->andWhere( 'mdt.createdDate >= :startDate' )
			            ->setParameter( 'startDate', $startDate );
	            } else {

		            $query
			            ->andWhere( 'mdt.createdDate >= :startDate' )
			            ->andWhere( 'mdt.createdDate <= :endDate' )
			            ->setParameter( 'startDate', $startDate )
			            ->setParameter( 'endDate', $endDate );
	            }
            }
//            echo $query->getQuery()->getSQL(); exit;


        } elseif ($role == 'SubFranchise') {
            $query = $this->createQueryBuilder('u')
                ->select('count(u.id)')
                ->innerJoin('App\Entity\MemberScheduleActivity','msa','WITH','u.id = msa.member')
	            ->innerJoin('App\Entity\MemberDeviceToken','mdt', 'WITH', 'u.id = mdt.user')
                ->join('u.groups', 'g')
                ->join('msa.scheduleDetail', 'sd')
                ->join('sd.schedule', 's')
                ->where('s.facility  IN ( :facilityIds )')
	            ->groupBy('u.id')
                ->andWhere('g.code = :code')
	            ->andWhere('mdt.deviceType = :deviceType')
	            ->setParameter('deviceType',$deviceType)
                ->setParameter('code', 'Member')
                ->setParameter('facilityIds', $childIds);
	        if($startDate && $endDate) {
		        if ( $startDate == $endDate ) {

			        $query
				        ->andWhere( 'mdt.createdDate >= :startDate' )
				        ->setParameter( 'startDate', $startDate );
		        } else {

			        $query
				        ->andWhere( 'mdt.createdDate >= :startDate' )
				        ->andWhere( 'mdt.createdDate <= :endDate' )
				        ->setParameter( 'startDate', $startDate )
				        ->setParameter( 'endDate', $endDate );
		        }
	        }

        } elseif ($role == 'SuperFranchise' || $role == 'Facility') {

            $query = $this->createQueryBuilder('u')
                ->select('count(u.id)')
	            ->innerJoin('App\Entity\MemberScheduleActivity','msa','WITH','u.id = msa.member')
	            ->innerJoin('App\Entity\MemberDeviceToken','mdt', 'WITH', 'u.id = mdt.user')
                ->join('msa.scheduleDetail', 'sd')
                ->join('sd.schedule', 's')
	            ->groupBy('u.id')
                ->where('s.facility  IN ( :facilityIds )')
	            ->andWhere('mdt.deviceType = :deviceType')

	            ->setParameter('deviceType',$deviceType)
                ->setParameter('facilityIds', $childIds);

	        if($startDate && $endDate) {
		        $query->
		        andWhere( 'mdt.createdDate >= :startDate' )
		              ->andWhere( 'mdt.createdDate = :endDate' )
		              ->setParameter( 'startDate', $startDate )
		              ->setParameter( 'endDate', $endDate );
	        }
        }

//        print_r($childIds);
//        echo $query->getQuery()->getSQL(); exit;
        return $query->getQuery()->getResult();
    }
    public function getUsersForDashboardMemberChartByFromandToDate($fromDate, $toDate, $userGroup, $childs = array())
    {

//        $start = $end = "";

        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $start = $fromDate;
        $end = $toDate;
        $em = $this->getEntityManager();
        if ($userGroup == 'HQ-Admin') {

            $query = $em->createQueryBuilder('u')
                ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%b\') as created_at')
                ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
                ->join('u.groups', 'g')
                ->where('u.enabled  = 1 ')
                ->andWhere('g.code = :code')
                ->setParameter('code', 'Member')
                ->orderBy('u.createdAt', 'ASC')
                ->groupBy('created_at');
            //echo $query->getQuery()->getSQL(); exit;


        }elseif ($userGroup == 'SubFranchise') {
            $query = $em->createQueryBuilder('msa')
                ->select('count(msa.id) as no_of_users ,  DATE_FORMAT(msa.createdAt,\'%Y-%b\') as created_at')
                ->from('App\Entity\MemberScheduleActivity', 'msa')
                ->join('msa.member', 'member')
                ->join('member.groups', 'g')
                ->join('msa.scheduleDetail', 'sd')
                ->join('sd.schedule', 's')
                ->where('s.facility  IN ( :facilityIds )')
                ->andWhere('g.code = :code')
                ->setParameter('code', 'Member')
                ->setParameter('facilityIds', $childs);

//            $query = $em->createQueryBuilder('u')
//                ->select('count(u.id)')
//                ->from('ApplicationSonataUserBundle:User', 'u')
//                ->join('u.groups', 'g')
//                ->where('u.enabled  = 1 ')
//                ->andWhere('g.code = :code')
//                ->setParameter('code', 'Member');

        }

//        join package on member_package.package_id = package.id
//join package_type on package.package_type_id = package_type.id




        elseif ($userGroup == 'SuperFranchise' || $userGroup == 'Facility') {

                $statement = $connection->prepare("SELECT  COUNT(member_id) no_of_users,DATE_FORMAT(created_date, '%Y-%M') created_at
                    FROM
                     (
                      SELECT  member_id,DATE_FORMAT(created_date, '%Y-%m-%d') created_date
                      FROM 
                      (
                      SELECT  m0_.member_id ,DATE_FORMAT(m0_.created_date, '%Y-%m-%d') created_date   
                      FROM member_schedule_activity m0_
                      INNER JOIN schedule_detail s2_ ON m0_.schedule_detail_id = s2_.id
                      INNER JOIN activity_schedule a3_ ON s2_.schedule_id = a3_.id
                      WHERE a3_.facility_id IN (:facilities)
                      AND (DATE_FORMAT(m0_.created_date, '%Y-%m-%d') BETWEEN '$start' AND '$end' )   
                     ) uniq 
                     GROUP BY member_id 
                     
                    ) redun
                    GROUP BY  month(created_date)");
            $childs = implode(",",$childs);
            $statement->bindValue('facilities', $childs);
//            $statement->bindValue('startDate', $start);
//            $statement->bindValue('endDate', $end);
            $statement->execute();
            $results = $statement->fetchAll();
//        dump($results);die;
            return $results;
            }




//        $query->andWhere("DATE_FORMAT(u.createdAt,'%Y-%m-%d') BETWEEN :start and :end")
//            ->setParameter('start', $start)
//            ->setParameter('end', $end);
//
//        return $query->getQuery()->getResult();
    }




    public function getDeviceSpecificUsersByRolesForDashboardChart($timeperiod, $userGroup, $childs = array())
    {

        $start = $end = "";
//        dump($timeperiod);exit;
        if ($timeperiod == "1") {
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');

        }
        elseif ($timeperiod == "2") {
            $start = date('Y-m-d', strtotime('-30 days'));
            $end = date('Y-m-d');
        }
        elseif ($timeperiod == "today") {
            $start = date('Y-m-d', strtotime('-1 days'));
            $end = date('Y-m-d');
//            dump($start,$end);die;
        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

        }


        $em = $this->getEntityManager();
        if ($userGroup == 'HQ-Admin') {
            $em = $this->getEntityManager();
            $connection = $em->getConnection();
            if($timeperiod == 1 || $timeperiod == 2 ||$timeperiod == 'today'){
                $sql = "SELECT DATE_FORMAT(f1_.created_at, '%Y-%M-%d') created_at , count(mdt1.member_id) android_user,count(mdt2.member_id) iphone_user  
                    FROM fos_user_user f1_
                    INNER JOIN fos_user_user_group f3_ ON f1_.id = f3_.user_id
                    INNER JOIN fos_user_group f2_ ON f2_.id = f3_.group_id 
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='android'
                    )  mdt1 ON f1_.id=  mdt1.member_id 
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='iphone'
                    )  mdt2 ON f1_.id=  mdt2.member_id 
                    WHERE f2_.code = 'Member' 
                    AND
                    (DATE_FORMAT(f1_.created_at, '%Y-%m-%d') BETWEEN '".$start."' AND '".$end."') 
                    GROUP BY DAY(f1_.created_at) 
                    ORDER BY f1_.created_at";
                $statement = $connection->prepare($sql);
            }else{
                $statement = $connection->prepare("SELECT DATE_FORMAT(f1_.created_at, '%Y-%M') created_at , count(mdt1.member_id) android_user,count(mdt2.member_id) iphone_user  
                    FROM fos_user_user f1_
                    INNER JOIN fos_user_user_group f3_ ON f1_.id = f3_.user_id
                    INNER JOIN fos_user_group f2_ ON f2_.id = f3_.group_id 
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='android'
                    )  mdt1 ON f1_.id=  mdt1.member_id 
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='iphone'
                    )  mdt2 ON f1_.id=  mdt2.member_id 
                    WHERE f2_.code = 'Member' 
                    AND
                    (DATE_FORMAT(f1_.created_at, '%Y-%m-%d') BETWEEN '".$start."' AND '".$end."') 
                    GROUP BY MONTH(f1_.created_at) 
                    ORDER BY f1_.created_at");
            }

//            $statement->bindValue('start', $end);
//            $statement->bindValue('end', $start);
            $statement->execute();

//            dump($statement);die;

            $results = $statement->fetchAll();
            return $results;


        }
        elseif ($userGroup == 'MasterFranchise' || $userGroup == 'SubFranchise') {


            $em = $this->getEntityManager();
            $connection = $em->getConnection();
            if($timeperiod == 1 || $timeperiod == 2 ||$timeperiod == 'today'){
                $sql = "SELECT  DATE_FORMAT(mp_.created_date, '%Y-%M-%d') created_at,count(mp_.member_id)  ,count(mdt1.member_id) android_user,count(mdt2.member_id) iphone_user 
                                        FROM  member_package mp_ 
                                        INNER JOIN package p_ ON mp_.package_id=p_.id  
                                        
                                        INNER JOIN fos_user_user f2_ ON p_.facility_id=f2_.id
                                        INNER JOIN fos_user_user_group f3_ ON f2_.id = f3_.user_id
                                        INNER JOIN fos_user_group f4_ ON f3_.group_id = f4_.id
                                        
                                        
                                        LEFT JOIN  
                                        (
                                        SELECT DISTINCT(user_id) member_id
                                        FROM member_device_token
                                        WHERE device_type='android'
                                        )  mdt1 ON   mdt1.member_id = mp_.member_id
                                        LEFT JOIN  
                                        (
                                        SELECT DISTINCT(user_id) member_id
                                        FROM member_device_token
                                        WHERE device_type='iphone'
                                        )  mdt2 ON   mdt2.member_id =mp_.member_id
                                        
                                        
                                        WHERE 
                                        
                                        f2_.id IN (:facilityIds) and f4_.name='Facility'
                                        
                                        AND
                                        (DATE_FORMAT(mp_.created_date, '%Y-%m-%d') BETWEEN '".$start."' AND '".$end."') 
                                        
                                        
                                        
                                        GROUP BY DATE_FORMAT(mp_.created_date, '%Y-%M-%d')
                                        
                                        ORDER BY mp_.created_date";
                $statement = $connection->prepare($sql);

            }else{
                $statement = $connection->prepare("SELECT  DATE_FORMAT(mp_.created_date, '%Y-%M-%d') created_at,count(mp_.member_id)  ,count(mdt1.member_id) android_user,count(mdt2.member_id) iphone_user 
                                        FROM  member_package mp_ 
                                        INNER JOIN package p_ ON mp_.package_id=p_.id  
                                        
                                        INNER JOIN fos_user_user f2_ ON p_.facility_id=f2_.id
                                        INNER JOIN fos_user_user_group f3_ ON f2_.id = f3_.user_id
                                        INNER JOIN fos_user_group f4_ ON f3_.group_id = f4_.id
                                        
                                        
                                        LEFT JOIN  
                                        (
                                        SELECT DISTINCT(user_id) member_id
                                        FROM member_device_token
                                        WHERE device_type='android'
                                        )  mdt1 ON   mdt1.member_id = mp_.member_id
                                        LEFT JOIN  
                                        (
                                        SELECT DISTINCT(user_id) member_id
                                        FROM member_device_token
                                        WHERE device_type='iphone'
                                        )  mdt2 ON   mdt2.member_id =mp_.member_id
                                        
                                        
                                        WHERE 
                                        
                                        f2_.id IN (:facilityIds) and f4_.name='Facility'
                                        
                                        AND
                                        (DATE_FORMAT(mp_.created_date, '%Y-%m') BETWEEN '".$start."' AND '".$end."') 
                                        
                                        
                                        
                                        GROUP BY MONTH(mp_.created_date) 
                                        
                                        ORDER BY mp_.created_date");

            }
//            dump($childs);die;
	        $childs = implode(",",$childs);
            $statement->bindValue('facilityIds', $childs);
            $statement->execute();
            $results = $statement->fetchAll();
            return $results;

        } elseif ($userGroup == 'SuperFranchise' || $userGroup == 'Facility') {

	        $em = $this->getEntityManager();
	        $connection = $em->getConnection();
	        if($timeperiod == 1 || $timeperiod == 2 ||$timeperiod == 'today'){
		        $statement = $connection->prepare("SELECT DATE_FORMAT(f1_.created_at, '%Y-%M-%d') created_at , count(mdt1.member_id) android_user,count(mdt2.member_id) iphone_user  
                    FROM fos_user_user f1_
                    INNER JOIN fos_user_user_group f3_ ON f1_.id = f3_.user_id
                    INNER JOIN fos_user_group f2_ ON f2_.id = f3_.group_id 
                    INNER JOIN member_schedule_activity m0_ ON m0_.member_id = f1_.id 
                    INNER JOIN schedule_detail s4_ ON m0_.schedule_detail_id = s4_.id 
                    INNER JOIN activity_schedule a5_ ON s4_.schedule_id = a5_.id
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='android'
                    )  mdt1 ON f1_.id=  mdt1.member_id 
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='iphone'
                    )  mdt2 ON f1_.id=  mdt2.member_id 
                    WHERE a5_.facility_id IN (:facilityIds) AND f2_.code = 'Member' 
                    AND
                    (DATE_FORMAT(f1_.created_at, '%Y-%m-%d') BETWEEN '".$start."' AND '".$end."') 
                    GROUP BY DAY(f1_.created_at) 
                    ORDER BY f1_.created_at");
	        }else{
		        $statement = $connection->prepare("SELECT DATE_FORMAT(f1_.created_at, '%Y-%M-%d') created_at , count(mdt1.member_id) android_user,count(mdt2.member_id) iphone_user  
                    FROM fos_user_user f1_
                    INNER JOIN fos_user_user_group f3_ ON f1_.id = f3_.user_id
                    INNER JOIN fos_user_group f2_ ON f2_.id = f3_.group_id 
                    INNER JOIN member_schedule_activity m0_ ON m0_.member_id = f1_.id 
                    INNER JOIN schedule_detail s4_ ON m0_.schedule_detail_id = s4_.id 
                    INNER JOIN activity_schedule a5_ ON s4_.schedule_id = a5_.id
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='android'
                    )  mdt1 ON f1_.id=  mdt1.member_id 
                    LEFT JOIN  
                    (
                    SELECT DISTINCT(user_id) member_id
                    FROM member_device_token
                    WHERE device_type='iphone'
                    )  mdt2 ON f1_.id=  mdt2.member_id 
                    WHERE a5_.facility_id IN (:facilityIds) AND f2_.code = 'Member' 
                    AND
                    (DATE_FORMAT(f1_.created_at, '%Y-%m-%d') BETWEEN '".$start."' AND '".$end."') 
                    GROUP BY DAY(f1_.created_at) 
                    ORDER BY f1_.created_at");
	        }
//            dump($childs);die;
	        $childs = implode(",",$childs);
	        $statement->bindValue('facilityIds', $childs);
	        $statement->execute();
	        $results = $statement->fetchAll();
	        return $results;

        }

    }
    public function getDeviceSpecificUsersByRolesForDashboardChartDayView($timeperiod, $userGroup, $childs = array(),$deviceType)
    {

        $start = $end = "";
//        dump($timeperiod);exit;
        if ($timeperiod == "1") {
            $start = date('Y-m-d', strtotime('-7 days'));
            $end = date('Y-m-d');

        }
        elseif ($timeperiod == "2") {
            $last_month = date('m', strtotime('last month'));
            $last_year_month = date('Y-m', strtotime('last month'));
            $end_months = array('01', '03', '05', '07', '08', '10', '12');
            if (in_array($last_month, $end_months)) {
                $month_end = '31';
            } else {
                $month_end = '30';
            }

            $start = $last_year_month . '-01';
            $end = $last_year_month . '-' . $month_end;

        }
        elseif ($timeperiod == "today") {
            $start = date('Y-m-d');
            $end = date('Y-m-d');
//            dump($start,$end);die;
        } else {

            $interval = $timeperiod;
            $end = date('Y-m-d');
            $start = date('Y-m-d', strtotime("-" . $interval . " month"));

        }


        $em = $this->getEntityManager();
        if ($userGroup == 'HQ-Admin') {

            $query = $em->createQueryBuilder('u')
                ->select('count(u.id) as no_of_users, DATE_FORMAT(u.createdAt,\'%Y-%M-%d\') as created_at')
                ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
                ->join('u.groups', 'g')
                ->where('u.enabled  = 1 ')
                ->join('App\Entity\MemberDeviceToken','m')
                ->where('u.id = m.id')
                ->andWhere('m.deviceType = :device')
                ->andWhere('g.code = :code')
                ->setParameter('code', 'Member')
                ->setParameter('device', $deviceType)
                ->orderBy('u.createdAt', 'ASC')
                ->groupBy('created_at');
//            echo $query->getQuery()->getSQL(); exit;


        } elseif ($userGroup == 'MasterFranchise' || $userGroup == 'SubFranchise') {

            $query = $em->createQueryBuilder('msa')
                ->select('count(msa.id) as no_of_users, DATE_FORMAT(msa.createdDate,\'%Y-%M-%d\') as created_at')
                ->from('App\Entity\MemberScheduleActivity', 'msa')
                ->innerJoin('msa.member', 'u')
                ->innerJoin('msa.scheduleDetail', 'd')
                ->innerJoin('d.schedule', 's')

                ->join('App\Entity\MemberDeviceToken','m')
                ->where('u.id = m.id')
                ->andWhere('m.deviceType = :device')
                ->setParameter('device', $deviceType)

                ->where('s.facility IN  ( :facility ) ')
                ->setParameter("facility", $childs)

            ;

            if ($timeperiod) {
                $query->andWhere("DATE_FORMAT(msa.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
                    ->setParameter('start', $start)
                    ->setParameter('end', $end);
            }
            $query->groupBy('created_at');

            return $query->getQuery()->getResult();

        } elseif ($userGroup == 'SuperFranchise' || $userGroup == 'Facility') {


            $query = $em->createQueryBuilder('msa')
                ->select('count(msa.id) as no_of_users, DATE_FORMAT(msa.createdDate,\'%Y-%M-%d\') as created_at')
                ->from('App\Entity\MemberScheduleActivity', 'msa')
                ->innerJoin('msa.member', 'u')
                ->innerJoin('msa.scheduleDetail', 'd')
                ->innerJoin('d.schedule', 's')
                ->where('s.facility IN  ( :facility ) ')
                ->setParameter("facility", $childs)
                ->join('App\Entity\MemberDeviceToken','m')
                ->where('u.id = m.id')
                ->andWhere('m.deviceType = :device')
                ->setParameter('device', $deviceType)
                ->groupBy('created_at');

            if ($timeperiod) {
                $query->andWhere("DATE_FORMAT(msa.createdDate,'%Y-%m-%d') BETWEEN :start and :end")
                    ->setParameter('start', $start)
                    ->setParameter('end', $end);
            }
            return $query->getQuery()->getResult();

        }


        if ($timeperiod) {
            $query->andWhere("DATE_FORMAT(u.createdAt,'%Y-%m-%d') BETWEEN :start and :end")
                ->setParameter('start', $start)
                ->setParameter('end', $end);
        }
        return $query->getQuery()->getResult();
    }

    public function getNonPartner($params,$distance)
    {

        $data = array();
        $data['unit'] = 6371;
        $data['distance'] = $distance;
        $data['id'] = $params['id'];
        $data['latitude'] = $params['latitude'];
        $data['longitude'] = $params['longitude'];

        $sql = "SELECT u.id id, (
                                        :unit *
                                        acos(cos(radians(:latitude)) *
                                             cos(radians(u.latitude)) *
                                             cos(radians(u.longitude) -
                                                 radians(:longitude)) +
                                             sin(radians(:latitude)) *
                                             sin(radians(u.latitude)))
                                   ) AS distance
                                FROM
                                  fos_user_user u
                                where
                                  u.id = :id
                                   having distance < :distance";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($data);
        return $stmt->fetchAll();
    }

    public function getAllRefferalUser(User $corporate)
    {

//        dump($corporate);die;
        $qb = $this->createQueryBuilder('u');

        $qb
            ->innerJoin('App\Entity\MemberKey','mk','WITH','u.id = mk.member')
            ->innerJoin('App\Entity\CorporateKey','ck','WITH','ck.id = mk.corporateKey')

            ->andWhere('ck.corporate = :corporate')
            ->andWhere('ck.type =:keyType')
            ->setParameter('corporate', $corporate)
            ->setParameter('keyType', Shared::$KEY_TYPE_Referral);
        return $qb;
    }

    public function forceLoggedOutAllMembers($appVersion = null)
    {

        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder('u')
            ->select('u')
            ->from('App\Application\Sonata\UserBundle\Entity\User', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('u.enabled  = 1 ')
            ->andWhere('g.code  = :code ')
            ->setParameter('code', Shared::$GROUPG_TYPE_MEMBER);

        if($appVersion){

            $query = $query
                ->innerJoin('u.appVersion', 'av')
                ->andWhere('av.id = :id')
                ->setParameter('id', $appVersion);
        }


        $users = $query->getQuery()->getResult();

        /**
         * @var  $user User
         */
        foreach ($users as $user){

            $user->setIsGDPR(false);
            $em->persist($user);
            $em->flush();
        }

    }

    public function getUserChallenges(User $user,$status,$company = null)
    {

        $qb = $this->createQueryBuilder('u');
        $qb
            ->innerJoin('App\Gamification\Bundle\Entity\MemberChallenge','mc','WITH','u.id = mc.member')
            ->innerJoin('App\Gamification\Bundle\Entity\Challenge','c','WITH','c.id = mc.challenge')
            ->where('u.id = :user_id')
            ->andWhere('mc.status = :status')
            ->select('c')
            ->setParameter('user_id',$user->getId())
            ->setParameter('status',$status)
            ->andWhere('c.start_date <= :now')
            ->andWhere('c.isActive = :isActive')
            ->andWhere('c.end_date >= :now')
            ->andWhere('c.isDeleted = :isDeleted')
            ->setParameter('isActive',true)
            ->setParameter('isDeleted',false)
            ->setParameter('now',new \DateTime())
        ;
        if($company){

            $qb
//                ->innerJoin('Application\Sonata\UserBundle\Entity\User','u','u')
                ->andWhere('c.company = :company')
                ->setParameter('company',$company)

            ;
        }
//        dump($qb->getQuery()->getResult(),$status,$company);die;

        return $qb->getQuery();
    }

    public function baseQueryUserChallenge(Challenge $challenge = null,$status = 'confirmed')
    {
        $qb = $this->createQueryBuilder('u')
            ->select('sum(a.value) as total_points')
            ->leftJoin('App\Gamification\Bundle\Entity\MemberActionPoints','map','WITH','u.id = map.member')
             ->innerJoin('App\Gamification\Bundle\Entity\ChallengeAction','ca','WITH','ca.member_action_points = map.id')
            ->innerJoin('App\Gamification\Bundle\Entity\Actions','a','WITH','a.id = map.action')
            ->innerJoin('App\Gamification\Bundle\Entity\Challenge','c','WITH','c.id = ca.challenge')
            ->innerJoin('App\Gamification\Bundle\Entity\MemberChallenge','mc','WITH','c.id = mc.challenge')
        ;
        $qb
            ->andWhere('c.isActive =:isActive')
            ->andWhere('mc.status = :status')
            ->setParameter('isActive',1)
            ->setParameter('status','confirmed')
        ;
        if($challenge) {
            $qb
                ->andWhere('c.id =:challenge_id')
                ->setParameter('challenge_id', $challenge->getId());
        }
        return $qb;
    }

    public function getUsersRank(Challenge $challenge = null,User $user = null,$status = 'Confirmed')
    {

        if($challenge) {
            $challengeId = $challenge->getId();
            $qbString = "SELECT table1.member_id id, IFNULL(table2.points, 0) as points,table1.challenge_id
                      FROM (
                              ( 
                                SELECT DISTINCT(mci.member_id) , mci.challenge_id 
    	                        FROM member_challenge_invite as mci
     	                        where mci.challenge_id = " . $challengeId . " and
                                mci.status = '" . $status . "'
	                          ) as table1 LEFT JOIN
                                (
                                  select u.id, SUM(ga.point) as points 
                                  from fos_user_user as u
    	                          JOIN member_action_point map ON map.member_id = u.id
    	                          JOIN gmf_actions ga ON ga.id = map.action_id
    	                          JOIN challenge_action ca ON ca.member_action_points_id = map.id
    	                          where ca.challenge_id = " . $challengeId . "
    	                          GROUP BY u.id
                                ) as table2 on table1.member_id = table2.id
                      ) ORDER by points DESC";
        }else{

            $qbString = "SELECT table1.member_id id, IFNULL(table2.points, 0) as points 
                          FROM ( 
                                ( SELECT DISTINCT(mci.member_id) FROM member_challenge_invite as mci 
                                  where mci.status = '".$status."' ) as table1 
                                  LEFT JOIN ( 
                                  select u.id, SUM(ga.point) as points from fos_user_user as u 
                                  JOIN member_action_point map ON map.member_id = u.id JOIN gmf_actions ga ON 
                                  ga.id = map.action_id JOIN challenge_action ca ON ca.member_action_points_id = map.id 
                                  GROUP BY u.id ) as table2 on table1.member_id = table2.id ) ORDER by points DESC ";
        }
        $em = $this->getEntityManager();
            $stmt = $em->getConnection()->prepare($qbString);
        $stmt->execute();
        $positions = $stmt->fetchAll();
        $userPointEarned = 0;
        if(empty($positions)){

            return array(0,0);
        }else{

            $userRank = 0;
            foreach ($positions as $key => $position){

                if($position['id'] == $user->getId()){

                    $userRank = $position['points'] == 0 ? 0 : $key+1;
                    $userPointEarned = $position['points'];
                }
            }



            return array($userRank , count($positions),(int)$userPointEarned);
        }
    }

    public function getLeaderBoard($container,Challenge $challenge = null,User $user = null,$isHistory = false,$status = 'Confirmed')
    {

        $em = $this->getEntityManager();

        if($challenge) {
            $challengeId = $challenge->getId();
            $qbString = "SELECT table1.member_id id, IFNULL(table2.points, 0) as points,table1.challenge_id
                      FROM (
                              ( 
                                SELECT DISTINCT(mci.member_id) , mci.challenge_id 
    	                        FROM member_challenge_invite as mci
    	                        JOIN challenge c1 ON c1.id = mci.challenge_id
     	                        where mci.challenge_id = " . $challengeId . " and
                                mci.status = '" . $status . "'  and
                                c1.is_deleted = 0
	                          ) as table1 LEFT JOIN
                                (
                                  select u.id, SUM(ga.point) as points 
                                  from fos_user_user as u
    	                          JOIN member_action_point map ON map.member_id = u.id
    	                          JOIN gmf_actions ga ON ga.id = map.action_id
    	                          JOIN challenge_action ca ON ca.member_action_points_id = map.id
    	                           where ca.challenge_id = " . $challengeId . "
    	                          GROUP BY u.id
                                ) as table2 on table1.member_id = table2.id
                      ) ORDER by points DESC";
        }else{

                $qbString = "SELECT table1.id id, Ifnull(table2.points, 0) AS points
                                FROM   ( (SELECT DISTINCT( u1.id )
                                            FROM   fos_user_user AS u1
                                          JOIN fos_user_user_group uugroup
                 ON u1.id = uugroup.user_id
               JOIN fos_user_group ugroup
                 ON ugroup.id = uugroup.group_id
                    AND ugroup.code = 'Member'
          		JOIN member_action_point map ON map.member_id = u1.id
                                          
          WHERE u1.enabled = 1
         ) AS table1
         LEFT JOIN (SELECT u.id,
                           Sum(ga1.point) AS points
                    FROM   fos_user_user AS u
                           LEFT JOIN member_action_point map1 ON map1.member_id = u.id
                           LEFT JOIN gmf_actions ga1 ON ga1.id = map1.action_id
                    GROUP  BY u.id) AS table2
                ON table1.id = table2.id )
ORDER  BY points DESC";


        }
            $stmt = $em->getConnection()->prepare($qbString);
        $stmt->execute();

        $positions = $stmt->fetchAll();
        $responseArr = array();
        $loggedinUserObject = array();

        if(!$user){

            $finalReposeArr = [];
            $responseToShow = [];
            foreach ($positions as $key =>$position){

                $rankAssign = $this->getUserRanks($key,$responseToShow,$position['points']);
                $userObj = $this->getEntityManager()->getRepository('App\Application\Sonata\UserBundle\Entity\User')->find($position['id']);
                $responseToShow[] = array(
                    "total_points"=>(int)$position['points'],
                    "user" =>$userObj,
                    "rank"=>$position['points'] == 0 ?  $container->getParameter('no_rank_given') : $rankAssign
                );
            }

            foreach ($responseToShow as $response){

                $response['batch_icon'] = $this->getBatchIcon($response['rank'],false,$isHistory);
                $finalReposeArr[] = $response;
            }

            return $finalReposeArr;
        }

        foreach ($positions as $key =>$position){

            $rankAssign = $this->getUserRanks($key,$responseArr,$position['points']);
            $userObj = $this->getEntityManager()->getRepository('App\Application\Sonata\UserBundle\Entity\User')->find($position['id']);
            $responseArr[] = array(
                'total_points' => (int)$position['points'],
                'id' => (int)$position['id'],
                'name' =>$userObj->getFullname() !== " "? $userObj->getFullname(): $userObj->getUsername(),
                'rank' => $position['points'] == 0 ?  $container->getParameter('no_rank_given') : $rankAssign,
                'batch_icon'=> $position['points'] == 0 ? '/challenge/icons/normal_rank.png' : $this->getBatchIcon($key),
                'image_url' =>$userObj->getCompanyLogo(),
            );
        }

        $finalReposeArr = array();
        foreach ($responseArr as $response){

            if($response['id'] == $user->getId()){

                $loggedinUserObject = $response;
                $loggedinUserObject['batch_icon'] = $this->getBatchIcon($response['rank'],true,$isHistory);
            }
            $response['batch_icon'] = $this->getBatchIcon($response['rank'],false,$isHistory);
            $finalReposeArr[] = $response;
        }

        if(empty($loggedinUserObject)){

            $loggedinUserObject = array(
                'total_points' => 0,
                'id' => $user->getId(),
                'name' =>$user->getFullname() !== " "? $user->getFullname(): $user->getUsername(),
                'rank' =>  $container->getParameter('no_rank_given'),
                'batch_icon'=>$isHistory?'/challenge/icons/history_lower.png':'/challenge/icons/normal_rank.png' ,
                'image_url' =>$user->getCompanyLogo(),
            );
        }
        return array($finalReposeArr,$loggedinUserObject);
    }

    public function getTotalPointsExport(Challenge $challenge,User $user,$status = 'Confirmed')
    {

            $em = $this->getEntityManager();

            $challengeId = $challenge->getId();
            $userId = $user->getId();
            $qbString = "SELECT table1.member_id id, IFNULL(table2.points, 0) as points,table1.challenge_id
                      FROM (
                              ( 
                                SELECT DISTINCT(mci.member_id) , mci.challenge_id 
    	                        FROM member_challenge_invite as mci
    	                        JOIN challenge c1 ON c1.id = mci.challenge_id
     	                        where mci.challenge_id = " . $challengeId . " and
                                mci.status = '" . $status . "'  and
                                c1.is_deleted = 0
	                          ) as table1 LEFT JOIN
                                (
                                  select u.id, SUM(ga.point) as points 
                                  from fos_user_user as u
    	                          JOIN member_action_point map ON map.member_id = u.id
    	                          JOIN gmf_actions ga ON ga.id = map.action_id
    	                          JOIN challenge_action ca ON ca.member_action_points_id = map.id
    	                           where ca.challenge_id = " . $challengeId . "
    	                          GROUP BY u.id
                                ) as table2 on table1.member_id = table2.id
                      ) ORDER by points DESC";

            $stmt = $em->getConnection()->prepare($qbString);
        $stmt->execute();

        $positions = $stmt->fetchAll();

        foreach ($positions as $position){

            if($position['id'] == $userId){
                return $position['points'];
            }

        }

    }

    public function getUserRanks($key,$userRankArr,$userPoint)
    {

        if(empty($userRankArr)){

            $rank = $key+1;
        }else{

//            $endArr = end($userRankArr);
            $rank = $key+1;
        }
        foreach ($userRankArr as $item){

            if($item['total_points'] == $userPoint){
                $rank = $item['rank'];
            }
        }
        return (string)$rank;
    }
    public function getBatchIcon($key , $self = false,$isHistory=false)
    {
        $normalIcon = $self ? '/challenge/icons/your_rank_cup.png':'/challenge/icons/normal_rank.png';
        switch ($key){
            case 1:
                return $isHistory ? '/challenge/icons/history_higher.png':'/challenge/icons/first_rank.png';
                break;
            case 2:
                return $isHistory ? '/challenge/icons/history_higher.png':'/challenge/icons/second_rank.png';
                break;
            case 3:
                return $isHistory ? '/challenge/icons/history_higher.png':'/challenge/icons/third_rank.png';
                break;
            default:
                return $isHistory ? '/challenge/icons/history_lower.png': $normalIcon;
                break;
        }

    }


    public function getHistoryOfChallenge($container,User $company,User $user)
    {

        $qbStr = "SELECT c_id, m_id, IFNULL(sum(point),0) as total_points
                    FROM (
	                    SELECT mci1.challenge_id as c_id, mci1.member_id as m_id, mci1.status
                        FROM challenge as c2
                        join member_challenge_invite as mci1 on c2.id = mci1.challenge_id
                        where 
                          c2.company_id = '" . $company->getId() . "' and 
                          c2.is_deleted = 0 AND
                          mci1.status = 'confirmed' AND c2.end_date < now()
    
                        ) as table1 
                        LEFT JOIN
                        ( 
                          SELECT c1.id, c1.title, mci.member_id, ca1.challenge_id, ca1.member_action_points_id, map1.member_id as member1, map1.action_id,ga1.point
	                      from challenge c1
	                      JOIN member_challenge_invite mci on mci.challenge_id = c1.id
	                      LEFT JOIN challenge_action ca1 on ca1.challenge_id = mci.challenge_id
	                      LEFT JOIN member_action_point map1 on map1.id = ca1.member_action_points_id
                          LEFT JOIN gmf_actions ga1 on ga1.id = map1.action_id
	                      WHERE c1.company_id = '" . $company->getId() . "' and mci.member_id = map1.member_id
                        ) as table2
                    on table1.m_id = table2.member_id and table1.c_id = table2.challenge_id
                    GROUP BY c_id, m_id  ORDER BY total_points DESC";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($qbStr);
        $stmt->execute();

        $results = $stmt->fetchAll();
        $challengesArr = array();
        foreach ($results as $result) {

            if (isset($challengesArr[$result['c_id']])) {
                $challengesArr[$result['c_id']][] = $result;
            } else {

                $challengesArr[$result['c_id']][] = $result;
            }
        }
        $response = array();

            foreach ($challengesArr as $challengeId => $data) {

            $challengeObj = $em->getRepository('App\Gamification\Bundle\Entity\Challenge')->find($challengeId);
            $articleCounts= $this->getHistoryCount($user->getId(),$challengeObj->getId());
            list($totalRank,$userRank) = $this->getLeaderBoard($container,$challengeObj,$user);
                $rankString = $userRank['rank'] . '/' .(count($totalRank));

            foreach ($data as $key=>$datum){

                if($datum['m_id'] == $user->getId()) {
                    $response[] = array(
                        "title" => $challengeObj->getTitle(),
                        "id" => $challengeObj->getId(),
                        "company_id" => $company->getId(),
                        "start_date" => $challengeObj->getStartDateApi(),
                        "end_date" => $challengeObj->getEndDateApi(),
                        "duration_text" => $challengeObj->getDurationText(),
                        "image_url" => $company->getCompanyLogo(),
                        "check_in_count" => (int)$articleCounts['check_in_count'],
                        "workout_count" => (int)$articleCounts['workout_count'],
                        "article_count" => (int)$articleCounts['article_count'],
                        'total_points' => (int)$userRank['total_points'],
                        'rank' => $userRank['rank'] == 0 ?  $container->getParameter('no_rank_given'): $rankString,
                        'total_rank' => count($totalRank)
                    );
                }
            }



        }

        return $response;
    }


    public function getHistoryCount($memberId,$challengeId)
    {
        $sql = "select ga.code as code , COUNT(ga.code) as count from challenge_action ca inner join member_action_point map on map.id = ca.member_action_points_id inner join gmf_actions ga on ga.id = map.action_id where challenge_id = ".$challengeId." AND map.member_id = ".$memberId." GROUP BY ga.code ";
        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();

        $results = $stmt->fetchAll();

        $checkInCount = 0;
        $workOutCount = 0;
        $articleCount = 0;
        foreach ($results as $result){


            if(in_array($result['code'] ,array('MANUAL_ACTIVITY_CHECKIN','STEPS_AWARD','CHECKIN','NON_PARTNER_CHECKIN'))){

                $checkInCount += $result['count'];
            }

            elseif($result['code'] == 'ARTICLE'){

                $articleCount = $result['count'];
            }elseif ($result['code'] == 'WORKOUT'){

                $workOutCount = $result['count'];
            }
        }

        return array('check_in_count'=>$checkInCount,'workout_count'=>$workOutCount,'article_count'=>$articleCount);

    }
    public function getCounts($type,$id)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('map')
            ->innerJoin('App\Gamification\Bundle\Entity\MemberActionPoints','map','WITH','map.member = u.id')
            ->innerJoin('App\Gamification\Bundle\Entity\Actions','ga','WITH','ga.id=map.action')
            ->where('ga.code = :code')
            ->andWhere('u.id = :id')
            ->setParameter('code',$type)
            ->setParameter('id',$id);
        $results = $qb->getQuery()->getResult();
        return count($results);
    }

    public function getTotalPoints($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('sum(ga.value) as points')
            ->innerJoin('App\Gamification\Bundle\Entity\MemberActionPoints','map','WITH','map.member = u.id')
            ->innerJoin('App\Gamification\Bundle\Entity\Actions','ga','WITH','ga.id=map.action')
            ->andWhere('u.id = :id')
            ->setParameter('id',$id);

        try{
        $results = $qb->getQuery()->getSingleScalarResult();


        return $results;
        }catch (\Exception $exception){

            return 0;
        }
    }
    public function getUserRowId(User $user)
    {

        $em = $this->getEntityManager();
        $memberDeviceToken = $em->getRepository('App\Entity\MemberDeviceToken')->findOneBy(array(
           'user'=>$user
        ));
        if($memberDeviceToken){

            return $memberDeviceToken->getIdentifierKey();
        }else{
            return null;
        }
    }

    public function getUserByIdAndAuthToken($id, $authToken)
    {
//        return $this->findOneBy(array('id' => $id, 'token' => $authToken));
        return $this->findOneBy(array('id' => $id));
    }
}
