FROM node:alpine
# for api-backend service
WORKDIR /usr/src/app

RUN apk add npm

RUN npm install -g nodemon

COPY package.json package-lock.json ./

RUN npm install

COPY ./ ./

EXPOSE 8000

CMD ["npm", "run", "dev"]
