/* groovylint-disable LineLength */
node {
    app = null
    properties([disableConcurrentBuilds()])

    stage('Set NodeJs') {
        env.NODEJS_HOME = "${tool 'node-14'}"
        env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"
        sh 'npm --version'
    }

    stage('Checkout Repository') {
        checkout scm
        sh 'git rev-parse --short HEAD > .git/commit-id'

        env.COMMIT_ID = readFile('.git/commit-id').trim()
        env.PROJECT_NAME = (env.JOB_NAME.tokenize('/') as String[])[0]
        env.SONAR_KEY = (env.WORKSPACE.tokenize('/') as String[]).last()
        env.IMAGE_TAG = "synavoshub/${env.PROJECT_NAME}:${commit_id}"
        env.BUILD_TAG = "${env.PROJECT_NAME}-${commit_id}"
    }

    sh 'printenv'

    stage('Create Docker Image') {
        app = docker.build(env.IMAGE_TAG, '-f Dockerfile ./')
    }

    stage('Test Build') {
        try {
            stage('Create Network') {
                sh("docker network create ${env.BUILD_TAG}")
            }

            stage('Create Sidecars') {
                establishSideCars()
            }

             stage('Run DB Migrations') {
                sh('docker pull synavoshub/sql-db-manager')
                sh('sleep 10')
                sh("docker run --rm --network ${env.BUILD_TAG} --name ${env.BUILD_TAG}-db-migrator -e TARGET_APP_NAME=febys -v ${env.WORKSPACE}:/data synavoshub/sql-db-manager")
            }

            stage('Run Tests') {
                app.inside("--network ${env.BUILD_TAG} ${containerArgs()}") {
                        sh 'npm i'
                        sh 'npm test'
                }
            }
        }
        finally {
            silent_sh "docker ps --filter name=${env.BUILD_TAG}* --filter status=running -aq | xargs docker stop "
            silent_sh "docker network rm ${env.BUILD_TAG}"
        }
    }

    stage('Code Analysis') {
      def sonarqubeScannerHome = tool name: 'sonar', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
      withCredentials([string(credentialsId: 'sonar', variable: 'sonarLogin')]) {
        sh "${sonarqubeScannerHome}/bin/sonar-scanner -e -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${sonarLogin} -Dsonar.projectName=${env.SONAR_KEY} -Dsonar.projectVersion=${env.BUILD_TAG} -Dsonar.projectKey=${env.SONAR_KEY} -Dsonar.sources=${env.WORKSPACE} -Dsonar.exclusions=**/*.test.js -Dsonar.tests=${env.WORKSPACE} -Dsonar.test.inclusions=**/*.test.js -Dsonar.coverage.exclusions=**/*.boundary.* -Dsonar.cpd.exclusions=**/*.svg.js -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info"
        checkSonarStatus(currentBuild, env)
      }
    }

    stage('Publish') {
        docker.withRegistry('https://index.docker.io/v1/', 'synavoshub') {
            app.push()

            if (env.BRANCH_NAME == 'develop') {
                app.push('develop')
            }

            if (env.BRANCH_NAME ==  'master') {
                app.push('latest')
            }
        }
    }
}

void establishSideCars() {
    sh("docker run --rm --network ${env.BUILD_TAG} --name ${env.BUILD_TAG}-mysql --net-alias docker.mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb")
}

String[] containerArgs() {
    args = []
    args << '-e DB_HOST=docker.mysql'

    return args.join(' ')
}

String planName(String jobName) {
    tokens = jobName.tokenize('/') as String[]
    return tokens[0]
}

void silent_sh(String script) {
    sh("(${script}) || true")
}

String checkSonarStatus(currentBuild, env){
    sh "sleep 20"
    sh "curl -X GET -H 'Accept: application/json' http://sonarqube:9000/api/qualitygates/project_status?projectKey=${env.SONAR_KEY} > status.json"
    def json = readJSON file:'status.json'
    echo "${json.projectStatus.status}"
    if ("${json.projectStatus.status}" == "ERROR") {
        currentBuild.result = 'FAILURE'
        error('SonarQube quality gate failed, please see sonar for details.')
    }
}